displayName=Clue Helper
author=emerald000
support=
description=An example greeter plugin
tags=clues,beginner,easy,medium,hard,elite,master,items,emotes,stashes
plugins=emerald000.cluehelper.ClueHelperPlugin