/*
 * Copyright (c) 2018, Lotto <https://github.com/devLotto>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package emerald000.cluehelper.clues;

import com.google.common.collect.ImmutableList;
import java.util.List;
import javax.annotation.Nullable;
import lombok.Getter;
import lombok.experimental.SuperBuilder;
import net.runelite.client.plugins.achievementdiary.FavourRequirement.Favour;
import static net.runelite.api.ItemID.*;
import static net.runelite.api.NullObjectID.NULL_12266;
import net.runelite.api.ObjectID;
import static net.runelite.api.ObjectID.*;
import net.runelite.api.Quest;
import static net.runelite.api.Quest.*;
import static net.runelite.api.Skill.HUNTER;
import static net.runelite.api.Skill.WOODCUTTING;
import net.runelite.api.coords.WorldPoint;
import static emerald000.cluehelper.clues.requirement.CommonRequirement.CAN_USE_PICKAXE;
import emerald000.cluehelper.clues.requirement.EquipmentRequirement;
import emerald000.cluehelper.clues.requirement.FavourRequirement;
import emerald000.cluehelper.clues.requirement.OrRequirement;
import emerald000.cluehelper.clues.requirement.QuestRequirement;
import emerald000.cluehelper.clues.requirement.RecommendedRequirement;
import emerald000.cluehelper.clues.requirement.SkillRequirement;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.CHRONICLE;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.EXPLORERS_RING_2;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.FREMENNIK_SEA_BOOTS;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.ICY_BASALT;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.KANDARIN_HEADGEAR_3;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.MYTHICAL_CAPE;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.*;

@Getter
@SuperBuilder
public class AnagramClue extends ClueScroll
{
	private static final String ANAGRAM_TEXT = "This anagram reveals who to speak to next: ";
	private static final String ANAGRAM_TEXT_BEGINNER = "The anagram reveals who to speak to next: ";

	private static final List<AnagramClue> CLUES = ImmutableList.of(
		// Beginner
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "AN EARL")
			.npc("Ranael")
			.location(new ClueArea(3315, 3163, 0))
			.area("Al Kharid skirt shop")
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.teleport(GNOME_GLIDER_AL_KHARID)
			.pathObject(new WorldPoint(3315, 3166, 0), CURTAIN_1533)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "CARPET AHOY")
			.npc("Apothecary")
			.location(new ClueArea(3195, 3404, 0))
			.area("Southwest Varrock")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3191, 3403, 0), DOOR_11775)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "DISORDER")
			.npc("Archmage Sedridor")
			.location(new ClueArea(3102, 9570, 0))
			.area("Wizards' Tower basement")
			.teleport(NECKLACE_OF_PASSAGE_WIZARDS_TOWER)
			.teleport(FAIRY_RING_DIS)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(STANDARD_LUMBRIDGE)
			.extraMapPoint(new WorldPoint(3104, 3162, 0))
			.pathObject(new WorldPoint(3109, 3167, 0), DOOR_23972)
			.pathObject(new WorldPoint(3107, 3162, 0), DOOR_23972)
			.pathObject(new WorldPoint(3104, 3162, 0), LADDER_2147)
			.pathObject(new WorldPoint(3108, 9570, 0), DOOR_1535)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "I CORD")
			.npc("Doric")
			.location(new ClueArea(2951, 3450, 0))
			.area("Doric's house, north of Falador")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2949, 3450, 0), DOOR_1535)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "IN BAR")
			.npc("Brian")
			.location(new ClueArea(3026, 3246, 0))
			.area("Port Sarim battleaxe shop")
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.pathObject(new WorldPoint(3026, 3244, 0), DOOR_1535)
			.pathObject(new WorldPoint(3031, 3248, 0), DOOR_1535)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "RAIN COVE")
			.npc("Veronica")
			.location(new ClueArea(3110, 3330, 0))
			.area("Outside Draynor Manor")
			.teleport(ARCEUUS_DRAYNOR_MANOR)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "RUG DETER")
			.npc("Gertrude")
			.location(new ClueArea(3151, 3412, 0))
			.area("Gertrude's house, west of Varrock")
			.teleport(SKILLS_NECKLACE_COOKS_GUILD)
			.teleport(COMBAT_BRACELET_CHAMPIONS_GUILD)
			.teleport(STANDARD_VARROCK)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "SIR SHARE RED")
			.npc("Hairdresser")
			.location(new ClueArea(2944, 3381, 0))
			.area("Falador, hairdresser")
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2949, 3379, 0), DOOR_24050)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT_BEGINNER + "TAUNT ROOF")
			.npc("Fortunato")
			.location(new ClueArea(3080, 3250, 0))
			.area("Draynor Village, market")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(STANDARD_LUMBRIDGE)
			.build(),

		// Medium
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "A BAKER")
			.clueId(CLUE_SCROLL_MEDIUM_12057)
			.npc("Baraek")
			.location(new ClueArea(3217, 3434, 0))
			.area("Varrock square")
			.question("How many stalls are there in Varrock Square?")
			.answer("5")
			.teleport(STANDARD_VARROCK)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "A BAS")
			.clueId(CLUE_SCROLL_MEDIUM_3613)
			.npc("Saba")
			.location(new ClueArea(2269, 4758, 0))
			.area("Death Plateau entrance")
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(MINIGAME_BURTHORPE)
			.extraMapPoint(new WorldPoint(2858, 3578, 0))
			.pathObject(new WorldPoint(2858, 3578, 0), CAVE_ENTRANCE_3735)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "A BASIC ANTI POT")
			.clueId(CLUE_SCROLL_MEDIUM_12061)
			.npc("Captain Tobias")
			.location(new ClueArea(3026, 3216, 0))
			.area("Port Sarim docks")
			.question("How many ships are there docked at Port Sarim currently?")
			.answer("6")
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(EXPLORERS_RING_2)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "A HEART")
			.clueId(CLUE_SCROLL_MEDIUM_19758)
			.npc("Aretha")
			.location(new ClueArea(1814, 3851, 0))
			.area("Soul altar, Arceuus")
			.question("32 - 5x = 22, what is x?")
			.answer("2")
			.teleport(ARCEUUS_HOME)
			.teleport(FAIRY_RING_CIS)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "AHA JAR")
			.clueId(CLUE_SCROLL_MEDIUM_3616)
			.npc("Jaraah")
			.location(new ClueArea(3359, 3276, 0))
			.area("Duel Arena hospital")
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "ARC O LINE")
			.clueId(CLUE_SCROLL_MEDIUM_7280)
			.npc("Caroline")
			.location(new ClueArea(2715, 3302, 0))
			.area("North of Witchaven")
			.question("How many fishermen are there on the fishing platform?")
			.answer("11")
			.teleport(QUEST_CAPE)
			.teleport(STANDARD_ARDOUGNE)
			.teleport(FAIRY_RING_BLR)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "ARE COL")
			.clueId(CLUE_SCROLL_MEDIUM_2851)
			.npc("Oracle")
			.location(new ClueArea(3013, 3501, 0))
			.area("Ice Mountain")
			.question("If x is 15 and y is 3 what is 3x + y?")
			.answer("48")
			.teleport(ANCIENT_LASSAR)
			.teleport(COMBAT_BRACELET_MONASTERY)
			.build(),
		// TODO: https://chisel.weirdgloop.org/varbs/display?varbit=6008
		// The grave multiobj is controlled by this one
		// So the answers 19 if the vals 0 and 20 if the varb val is 1
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "AREA CHEF TREK")
			.clueId(CLUE_SCROLL_MEDIUM_19746)
			.npc("Father Aereck")
			.location(new ClueArea(3243, 3208, 0))
			.area("Lumbridge Church")
			.question("How many gravestones are in the church graveyard?")
			.answer("19 or 20")
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3238, 3210, 0), DOOR_1540)
			.pathObject(new WorldPoint(3244, 3216, 0), LARGE_DOOR_1521)
			.pathObject(new WorldPoint(3243, 3216, 0), LARGE_DOOR_1524)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "ARMCHAIR THE PELT")
			.clueId(CLUE_SCROLL_MEDIUM_19750)
			.npc("Charlie the Tramp")
			.location(new ClueArea(3209, 3392, 0))
			.area("Varrock south entrance")
			.question("How many coins would I have if I have 0 coins and attempt to buy 10 loaves of bread for 3 coins each?")
			.answer("0")
			.teleport(COMBAT_BRACELET_CHAMPIONS_GUILD)
			.teleport(CHRONICLE)
			.teleport(STANDARD_VARROCK)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "BAIL TRIMS")
			.clueId(CLUE_SCROLL_MEDIUM_3612)
			.npc("Brimstail")
			.location(new ClueArea(2402, 3419, 0))
			.area("West of Stronghold Slayer Cave")
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.pathObject(new WorldPoint(2403, 3419, 0), CAVE_ENTRANCE_17209)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "CALAMARI MADE MUD")
			.clueId(CLUE_SCROLL_MEDIUM_23133)
			.npc("Madame Caldarium")
			.location(new ClueArea(2553, 2868, 0))
			.area("Corsair Cove")
			.question("What is 3(5-3)?")
			.answer("6")
			.teleport(HUNTER_CAPE_CARNIVOROUS_CHINCHOMPAS)
			.teleport(SCROLL_FELDIP_HILLS)
			.teleport(SPIRIT_TREE_FELDIP_HILLS)
			.teleport(BOAT_RIMMINGTON_TO_CORSAIR_COVE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "CLASH ION")
			.npc("Nicholas")
			.location(new ClueArea(1841, 3803, 0))
			.area("North of Port Piscarilius fishing shop")
			.question("How many windows are in Tynan's shop?")
			.answer("4")
			.teleport(KHAREDSTS_MEMOIRS_THE_FISHERS_FLUTE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DT RUN B")
			.npc("Brundt the Chieftain")
			.location(new ClueArea(2658, 3670, 0))
			.area("Rellekka main hall")
			.question("How many people are waiting for the next bard to perform?")
			.answer("4")
			.teleport(FREMENNIK_SEA_BOOTS)
			.teleport(ENCHANTED_LYRE_RELLEKKA)
			.teleport(TELEPORT_TO_HOUSE_RELLEKKA)
			.teleport(FAIRY_RING_AJR)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "EEK ZERO OP")
			.clueId(CLUE_SCROLL_MEDIUM_2845)
			.npc("Zoo keeper")
			.location(new ClueArea(2613, 3269, 0))
			.area("Ardougne Zoo")
			.question("How many animals in total are there in the zoo?")
			.answer("40")
			.teleport(ARDOUGNE_CLOAK_MONASTERY)
			.teleport(STANDARD_ARDOUGNE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "EL OW")
			.clueId(CLUE_SCROLL_MEDIUM_2847)
			.npc("Lowe")
			.location(new ClueArea(3233, 3423, 0))
			.area("Varrock archery store")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3233, 3428, 0), DOOR_11775)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "GOBLETS ODD TOES")
			.clueId(CLUE_SCROLL_MEDIUM_12055)
			.npc("Otto Godblessed")
			.location(new ClueArea(2501, 3487, 0))
			.area("Otto's Grotto")
			.question("How many types of dragon are there beneath the whirlpool's cavern?")
			.answer("2")
			.teleport(FISHING_CAPE_OTTOS_GROTTO)
			.teleport(GAMES_NECKLACE_BARBARIAN_OUTPOST)
			.teleport(MINIGAME_BARBARIAN_ASSAULT)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "GOBLIN KERN")
			.clueId(CLUE_SCROLL_MEDIUM_2857)
			.npc("King Bolren")
			.location(new ClueArea(2541, 3170, 0))
			.area("Tree Gnome Village")
			.teleport(SPIRIT_TREE_TREE_GNOME_VILLAGE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "GOT A BOY")
			.clueId(CLUE_SCROLL_MEDIUM_7276)
			.npc("Gabooty")
			.location(new ClueArea(2790, 3066, 0))
			.area("Tai Bwo Wannai")
			.question("How many buildings are in the village?")
			.answer("11")
			.teleport(SCROLL_TAI_BWO_WANNAI)
			.teleport(FAIRY_RING_CKR)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "HALT US")
			.clueId(CLUE_SCROLL_MEDIUM_2858)
			.npc("Luthas")
			.location(new ClueArea(2938, 3152, 0))
			.area("Banana plantation, Karamja")
			.teleport(AMULET_OF_GLORY_KARAMJA)
			.teleport(CHARTER_SHIP_MUSA_POINT)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "HEORIC")
			.clueId(CLUE_SCROLL_MEDIUM_12071)
			.npc("Eohric")
			.location(new ClueArea(2900, 3565, 1))
			.area("Burthorpe Castle, top floor")
			.question("King Arthur and Merlin sit down at the Round Table with 8 knights. How many degrees does each get?")
			.answer("36")
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(MINIGAME_BURTHORPE)
			.pathObject(new WorldPoint(2897, 3567, 0), STAIRS_4626)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "HICK JET")
			.clueId(CLUE_SCROLL_MEDIUM_7278)
			.npc("Jethick")
			.location(new ClueArea(2541, 3305, 0))
			.area("West Ardougne square")
			.question("How many graves are there in the city graveyard?")
			.answer("38")
			.teleport(ARCEUUS_WEST_ARDOUGNE)
			.teleport(SPIRIT_TREE_KHAZARD_BATTLEFIELD)
			.teleport(STANDARD_ARDOUGNE)
			.requirement(new QuestRequirement(Quest.PLAGUE_CITY, true))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "HIS PHOR")
			.clueId(CLUE_SCROLL_MEDIUM_19742)
			.npc("Horphis")
			.location(new ClueArea(1639, 3812, 0))
			.area("Arceuus Library")
			.question("On a scale of 1-10, how helpful is Logosia?")
			.answer("1")
			.teleport(KHAREDSTS_MEMOIRS_A_DARK_DISPOSITION)
			.teleport(FAIRY_RING_CIS)
			.pathObject(new WorldPoint(1634, 3798, 0), DOOR_28460)
			.pathObject(new WorldPoint(1635, 3798, 0), DOOR_28456)
			.pathObject(new WorldPoint(1633, 3817, 0), DOOR_28460)
			.pathObject(new WorldPoint(1632, 3817, 0), DOOR_28456)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "I AM SIR")
			.clueId(CLUE_SCROLL_MEDIUM_19756)
			.npc("Marisi")
			.location(new ClueArea(1737, 3557, 0))
			.area("Hosidius allotment patch")
			.question("How many cities form the Kingdom of Great Kourend?")
			.answer("5")
			.teleport(XERICS_TALISMAN_XERICS_GLADE)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.teleport(SKILLS_NECKLACE_WOODCUTTING_GUILD)
			.teleport(MINIGAME_TITHE_FARM)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "I DOOM ICON INN")
			.clueId(CLUE_SCROLL_MEDIUM_19736)
			.npc("Dominic Onion")
			.location(new ClueArea(2609, 3116, 0))
			.area("Nightmare Zone")
			.question("How many reward points does a herb box cost?")
			.answer("9,500")
			.teleport(MINIGAME_NIGHTMARE_ZONE)
			.teleport(STANDARD_YANILLE)
			.teleport(LUNAR_KHAZARD)
			.teleport(STANDARD_WATCHTOWER)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "I EVEN")
			.clueId(CLUE_SCROLL_MEDIUM_12059)
			.npc("Nieve")
			.location(new ClueArea(2432, 3422, 0))
			.area("Gnome Stronghold")
			.question("How many farming patches are there in Gnome stronghold?")
			.answer("2")
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "ICY FE")
			.clueId(CLUE_SCROLL_MEDIUM_3618)
			.npc("Fycie")
			.location(new ClueArea(2651, 9393, 0))
			.area("East Feldip Hills")
			.teleport(FAIRY_RING_AKS)
			.teleport(SCROLL_FELDIP_HILLS)
			.extraMapPoint(new WorldPoint(2630, 2997, 0))
			.pathObject(new WorldPoint(2630, 2998, 0), CAVE_ENTRANCE_3379)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "KAY SIR")
			.clueId(CLUE_SCROLL_MEDIUM_12069)
			.npc("Sir Kay")
			.location(new ClueArea(2760, 3496, 0))
			.area("Camelot Castle, courtyard")
			.question("How many fountains are there within the grounds of Camelot castle?")
			.answer("6")
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2757, 3482, 0), GATE_26081)
			.pathObject(new WorldPoint(2758, 3482, 0), GATE_26082)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "LARK IN DOG")
			.clueId(CLUE_SCROLL_MEDIUM_7284)
			.npc("King Roald")
			.location(new ClueArea(3220, 3476, 0))
			.area("Varrock Castle")
			.question("How many bookcases are there in the palace library?")
			.answer("24")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3218, 3472, 0), DOOR_11773)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "LEAKEY")
			.clueId(CLUE_SCROLL_MEDIUM_12065)
			.npc("Kaylee")
			.location(new ClueArea(2957, 3370, 0))
			.area("Falador pub")
			.question("How many chairs are there in the Rising Sun?")
			.answer("18")
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2956, 3379, 0), DOOR_24050)
			.pathObject(new WorldPoint(2962, 3372, 0), DOOR_24050)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "LOW LAG")
			.clueId(CLUE_SCROLL_MEDIUM_19738)
			.npc("Gallow")
			.location(new ClueArea(1805, 3566, 0))
			.area("Hosidius Vinery")
			.question("How many vine patches can you find in this vinery")
			.answer("12")
			.teleport(XERICS_TALISMAN_XERICS_GLADE)
			.teleport(MINIGAME_TITHE_FARM)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.teleport(SKILLS_NECKLACE_WOODCUTTING_GUILD)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "ME IF")
			.clueId(CLUE_SCROLL_MEDIUM_3611)
			.npc("Femi")
			.location(new ClueArea(2461, 3382, 0))
			.area("Tree Gnome Stronghold entrance")
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "NOD MED")
			.clueId(CLUE_SCROLL_MEDIUM_7282)
			.npc("Edmond")
			.location(new ClueArea(2566, 3332, 0))
			.area("East Ardougne, north-west house")
			.question("How many pigeon cages are there around the back of Jerico's house?")
			.teleport(LUNAR_FISHING_GUILD)
			.teleport(SKILLS_NECKLACE_FISHING_GUILD)
			.teleport(SPIRIT_TREE_KHAZARD_BATTLEFIELD)
			.teleport(STANDARD_ARDOUGNE)
			.answer("3")
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "OK CO")
			.clueId(CLUE_SCROLL_MEDIUM_2843)
			.npc("Cook")
			.location(new ClueArea(3207, 3214, 0))
			.area("Lumbridge Castle")
			.question("How many cannons does Lumbridge Castle have?")
			.answer("9")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "PACINNG A TAIE")
			.clueId(CLUE_SCROLL_MEDIUM_19734)
			.npc("Captain Ginea")
			.location(new ClueArea(1504, 3632, 0))
			.area("East of Shayzien war tent")
			.question("1 soldier can deal with 6 lizardmen. How many soldiers do we need for an army of 678 lizardmen?")
			.answer("113")
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "PEAK REFLEX")
			.clueId(CLUE_SCROLL_MEDIUM_19752)
			.npc("Flax keeper")
			.location(new ClueArea(2744, 3444, 0))
			.area("Seers' Village flax field")
			.question("If I have 1014 flax, and I spin a third of them into bowstring, how many flax do I have left?")
			.answer("676")
			.teleport(KANDARIN_HEADGEAR_3)
			.teleport(STANDARD_CAMELOT)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "PEATY PERT")
			.clueId(CLUE_SCROLL_MEDIUM_2856)
			.npc("Party Pete")
			.location(new ClueArea(3047, 3376, 0))
			.area("Falador Party Room")
			.teleport(SKILLS_NECKLACE_MINING_GUILD)
			.teleport(RING_OF_WEALTH_FALADOR)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(3045, 3371, 0), CASTLE_DOOR)
			.pathObject(new WorldPoint(3046, 3371, 0), CASTLE_DOOR_24064)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "QUE SIR")
			.clueId(CLUE_SCROLL_MEDIUM_19754)
			.npc("Squire")
			.location(new ClueArea(2975, 3343, 0))
			.area("Falador Castle")
			.question("White knights are superior to black knights. 2 white knights can handle 3 black knights. How many knights do we need for an army of 981 black knights?")
			.answer("654")
			.teleport(RESPAWN_FALADOR)
			.teleport(STANDARD_FALADOR)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "R AK MI")
			.npc("Karim")
			.location(new ClueArea(3273, 3181, 0))
			.area("Al Kharid kebab shop")
			.question("I have 16 kebabs, I eat one myself and then share the rest equally between 3 friends. How many do they have each?")
			.answer("5")
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.pathObject(new WorldPoint(3275, 3180, 0), DOOR_1535)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "R SLICER")
			.clueId(CLUE_SCROLL_MEDIUM_19740)
			.npc("Clerris")
			.location(new ClueArea(1761, 3850, 0))
			.area("Arceuus mine")
			.question("If I have 1,000 blood runes, and cast 131 ice barrage spells, how many blood runes do I have left?")
			.answer("738")
			.teleport(ARCEUUS_HOME)
			.teleport(FAIRY_RING_CIS)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "RATAI")
			.clueId(CLUE_SCROLL_MEDIUM_12063)
			.npc("Taria")
			.location(new ClueArea(2940, 3223, 0))
			.area("Rimmington bush patch")
			.question("How many buildings are there in Rimmington?")
			.answer("7")
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(SKILLS_NECKLACE_CRAFTING_GUILD)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "SAND NUT")
			.clueId(CLUE_SCROLL_MEDIUM_19748)
			.npc("Dunstan")
			.location(new ClueArea(2919, 3574, 0))
			.area("North east Burthorpe")
			.question("How much smithing experience does one receive for smelting a blurite bar?")
			.answer("8")
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(MINIGAME_BURTHORPE)
			.pathObject(new WorldPoint(2921, 3571, 0), DOOR_1535)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "TAMED ROCKS")
			.clueId(CLUE_SCROLL_MEDIUM_19744)
			.npc("Dockmaster")
			.location(new ClueArea(1822, 3739, 0))
			.area("Port Piscarilius, NE of General store")
			.question("What is the cube root of 125?")
			.answer("5")
			.teleport(KHAREDSTS_MEMOIRS_THE_FISHERS_FLUTE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "THICKNO")
			.clueId(CLUE_SCROLL_MEDIUM_12067)
			.npc("Hickton")
			.location(new ClueArea(2822, 3442, 0))
			.area("Catherby, ranging shop")
			.question("How many ranges are there in Catherby?")
			.answer("2")
			.teleport(LUNAR_CATHERBY)
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2822, 3441, 0), DOOR_1535)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "UESNKRL NRIEDDO")
			.clueId(CLUE_SCROLL_MEDIUM_25784)
			.npc("Drunken soldier")
			.location(new ClueArea(1551, 3565, 0))
			.area("Shayzien Pub")
			.question("If 13 Shayzien soldiers kill 46 lizardmen each in a day, how many lizardmen have they killed in a total in a single day?")
			.answer("598")
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "VESTE")
			.clueId(CLUE_SCROLL_MEDIUM_12059)
			.npc("Steve")
			.location(new ClueArea(2432, 3423, 0))
			.area("Gnome Stronghold")
			.question("How many farming patches are there in Gnome stronghold?")
			.answer("2")
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.build(),

		// Hard
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "BAKER CLIMB")
			.clueId(CLUE_SCROLL_HARD_19894)
			.npc("Brambickle")
			.location(new ClueArea(2783, 3861, 0))
			.area("Trollweiss mountain")
			.teleport(STANDARD_TROLLHEIM)
			.requirement(new QuestRequirement(TROLL_STRONGHOLD, true))
			.pathObject(new WorldPoint(2820, 3744, 0), CAVE_ENTRANCE_5007)
			.pathObject(new WorldPoint(2772, 10233, 0), CREVASSE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "BLUE GRIM GUIDED")
			.clueId(CLUE_SCROLL_HARD_19886)
			.npc("Lumbridge Guide")
			.location(new ClueArea(3238, 3220, 0))
			.area("Lumbridge")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "BY LOOK")
			.clueId(CLUE_SCROLL_HARD_7270)
			.npc("Bolkoy")
			.location(new ClueArea(2529, 3162, 1))
			.area("Tree Gnome Village general store")
			.question("How many flowers are there in the clearing below this platform?")
			.answer("13")
			.teleport(SPIRIT_TREE_TREE_GNOME_VILLAGE)
			.pathObject(new WorldPoint(2525, 3162, 0), LADDER_17026)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "C ON GAME HOC")
			.clueId(CLUE_SCROLL_HARD_7268)
			.npc("Gnome Coach")
			.location(new ClueArea(2395, 3486, 0))
			.area("Around Gnome Ball course")
			.question("How many gnomes on the Gnome ball field have red patches on their uniforms?")
			.answer("6")
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "COPPER ORE CRYPTS")
			.clueId(CLUE_SCROLL_HARD_12566)
			.npc("Prospector Percy")
			.location(new ClueArea(3756, 5666, 0))
			.area("Motherlode Mine")
			.question("During a party, everyone shook hands with everybody else. There were 66 handshakes. How many people were at the party?")
			.answer("12")
			.teleport(SKILLS_NECKLACE_MINING_GUILD)
			.teleport(RING_OF_WEALTH_FALADOR)
			.teleport(STANDARD_FALADOR)
			.requirement(new RecommendedRequirement(CAN_USE_PICKAXE.getRequirement()))
			.extraMapPoint(new WorldPoint(3061, 3377, 0))
			.pathObject(new WorldPoint(3061, 3374, 0), DOOR_24057)
			.pathObject(new WorldPoint(3059, 3376, 0), STAIRCASE_16664)
			.pathObject(new WorldPoint(3060, 9765, 0), CAVE_26654)
			.pathObject(new WorldPoint(3731, 5683, 0), ROCKFALL_26680)
			.pathObject(new WorldPoint(3733, 5680, 0), ROCKFALL)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DARN DRAKE")
			.clueId(CLUE_SCROLL_HARD_24493)
			.npc("Daer Krand")
			.location(new ClueArea(3821, 9778, 2))
			.area("Sisterhood Sanctuary")
			.teleport(BOAT_PORT_PHASMATYS_TO_SLEPE)
			.teleport(DRAKANS_MEDALLION_VER_SINHAZA)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.extraMapPoint(new WorldPoint(3728, 3301, 0))
			.pathObject(new WorldPoint(3728, 3300, 0), STAIRS_32637)
			.pathObject(new WorldPoint(3826, 9777, 1), STAIRS_37832)
			.build(),
		// TODO: Add path NPC
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DEKAGRAM")
			.clueId(CLUE_SCROLL_HARD_19888)
			.npc("Dark mage")
			.location(new ClueArea(3039, 4835, 0))
			.area("Centre of the Abyss")
			.question("How many rifts are found here in the abyss?")
			.answer("13")
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(FAIRY_RING_DKR)
			.teleport(STANDARD_GRAND_EXCHANGE)
			.teleport(RING_OF_WEALTH_GRAND_EXCHANGE)
			.requirement(new QuestRequirement(ENTER_THE_ABYSS))
			.extraMapPoint(new WorldPoint(3106, 3558, 0))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DO SAY MORE")
			.clueId(CLUE_SCROLL_HARD_12576)
			.npc("Doomsayer")
			.location(new ClueArea(3232, 3223, 0))
			.area("East of Lumbridge Castle")
			.question("What is 40 divided by 1/2 plus 15?")
			.answer("95")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DR WARDEN FUNK")
			.clueId(CLUE_SCROLL_HARD_19890)
			.npc("Drunken Dwarf")
			.location(new ClueArea(2913, 10221, 0))
			.area("Eastern Keldagrim")
			.teleport(MINIGAME_RAT_PITS_KELDAGRIM)
			.teleport(MINIGAME_BLAST_FURNACE)
			.teleport(MINECART_TO_KELDAGRIM)
			.requirement(new QuestRequirement(THE_GIANT_DWARF, true))
			.extraMapPoint(new WorldPoint(2731, 3713, 0))
			.pathObject(new WorldPoint(2913, 10219, 0), DOOR_6108)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DRAGONS LAMENT")
			.clueId(CLUE_SCROLL_HARD_12568)
			.npc("Strange Old Man")
			.location(new ClueArea(3564, 3288, 0))
			.area("Barrows")
			.question("One pipe fills a barrel in 1 hour while another pipe can fill the same barrel in 2 hours. How many minutes will it take to fill the tank if both pipes are used?")
			.answer("40")
			.teleport(ARCEUUS_BARROWS)
			.teleport(SCROLL_MORTTON)
			.teleport(MORYTANIA_LEGS_3_BURGH_DE_ROTT)
			.teleport(MINIGAME_SHADES_OF_MORTTON)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "MOTHERBOARD")
			.clueId(CLUE_SCROLL_HARD_12574)
			.npc("Brother Omad")
			.location(new ClueArea(2606, 3211, 0))
			.area("Ardougne Monastery")
			.question("What is the next number? 12,13,15,17,111,113,117,119,123 ....?")
			.teleport(ARDOUGNE_CLOAK_MONASTERY)
			.teleport(FAIRY_RING_DJP)
			.teleport(STANDARD_ARDOUGNE)
			.answer("129")
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "MY MANGLE LAL")
			.clueId(CLUE_SCROLL_HARD_19896)
			.npc("Lammy Langle")
			.location(new ClueArea(1688, 3540, 0))
			.area("Hosidius spirit tree patch")
			.teleport(SPIRIT_TREE_HOSIDIUS)
			.teleport(SKILLS_NECKLACE_WOODCUTTING_GUILD)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "O BIRDZ A ZANY EN PC")
			.clueId(CLUE_SCROLL_HARD_7272)
			.npc("Cap'n Izzy No-Beard")
			.location(new ClueArea(2807, 3191, 0))
			.area("Brimhaven Agility Arena")
			.question("How many Banana Trees are there in the plantation?")
			.teleport(DIARY_CAPE_PIRATE_JACKIE_THE_FRUIT)
			.teleport(SPIRIT_TREE_BRIMHAVEN)
			.teleport(TELEPORT_TO_HOUSE_BRIMHAVEN)
			.teleport(BOAT_CAPTAIN_BARNABY_TO_BRIMHAVEN)
			.teleport(AMULET_OF_GLORY_KARAMJA)
			.answer("33")
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "QUIT HORRIBLE TYRANT")
			.clueId(CLUE_SCROLL_HARD_19892)
			.npc("Brother Tranquility")
			.location(new ClueArea(3681, 2963, 0))
			.area("Mos Le'Harmless or Harmony Island")
			.question("If I have 49 bottles of rum to share between 7 pirates, how many would each pirate get?")
			.answer("7")
			.teleport(SCROLL_MOS_LEHARMLESS)
			.teleport(ARCEUUS_HARMONY_ISLAND)
			.teleport(CHARTER_SHIP_MOS_LEHARMLESS)
			.teleport(MINIGAME_TROUBLE_BREWING)
			.requirement(new QuestRequirement(CABIN_FEVER))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "RAT MAT WITHIN")
			.clueId(CLUE_SCROLL_HARD_12570)
			.npc("Martin Thwait")
			.location(new ClueArea(3047, 4976, 1))
			.area("Rogues' Den")
			.question("How many natural fires burn in Rogue's Den?")
			.answer("2")
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(MINIGAME_BURTHORPE)
			.extraMapPoint(new WorldPoint(2906, 3537, 0))
			.pathObject(new WorldPoint(2905, 3537, 0), TRAPDOOR_7257)
			.pathObject(new WorldPoint(3061, 4984, 1), DOOR_7259)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "SLIDE WOMAN")
			.clueId(CLUE_SCROLL_HARD_12572)
			.npc("Wise Old Man")
			.location(new ClueArea(3088, 3253, 0))
			.area("Draynor Village")
			.question("How many bookcases are in the Wise Old Man's house?")
			.answer("28")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3088, 3251, 0), DOOR_1535)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "VEIL VEDA")
			.clueId(CLUE_SCROLL_HARD_19882)
			.npc("Evil Dave")
			.location(new ClueArea(3079, 9892, 0))
			.area("Edgeville")
			.question("What is 333 multiplied by 2?")
			.answer("666")
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(FAIRY_RING_DKR)
			.teleport(STANDARD_GRAND_EXCHANGE)
			.extraMapPoint(new WorldPoint(3077, 3493, 0))
			.requirement(new QuestRequirement(SHADOW_OF_THE_STORM))
			.pathObject(new WorldPoint(3077, 3493, 0), NULL_12266)
			.build(),
		// TODO: Path NPC
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "WOO AN EGG KIWI")
			.clueId(CLUE_SCROLL_HARD_19884)
			.npc("Awowogei")
			.objectId(ObjectID.AWOWOGEI)
			.location(new ClueArea(2802, 2765, 0))
			.area("Ape Atoll")
			.question("If I have 303 bananas, and share them between 31 friends evenly, only handing out full bananas. How many will I have left over?")
			.answer("24")
			.teleport(STANDARD_APE_ATOLL)
			.teleport(FAIRY_RING_CLR)
			.teleport(GNOME_GLIDER_APE_ATOLL)
			.requirement(new QuestRequirement(MONKEY_MADNESS_I, true))
			.requirement(new OrRequirement("Karamjan Greegree",
				new EquipmentRequirement(KARAMJAN_MONKEY_GREEGREE),
				new QuestRequirement(MONKEY_MADNESS_II)))
			.requirement(new OrRequirement("M'speak Amulet",
				new EquipmentRequirement(MSPEAK_AMULET),
				new QuestRequirement(MONKEY_MADNESS_II)))
			.build(),

		// Elite
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "AT HERG")
			.clueId(CLUE_SCROLL_ELITE_19793)
			.npc("Regath")
			.location(new ClueArea(1719, 3723, 0))
			.area("Arceuus, general store")
			.question("What is -5 to the power of 2?")
			.answer("25")
			.teleport(KHAREDSTS_MEMOIRS_A_DARK_DISPOSITION)
			.teleport(STANDARD_KOUREND)
			.teleport(XERICS_TALISMAN_XERICS_HEART)
			.pathObject(new WorldPoint(1718, 3727, 0), DOOR_28459)
			.pathObject(new WorldPoint(1718, 3728, 0), DOOR_28463)
			.build(),
		// Challenge ID: 12139
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "CAREER IN MOON")
			.clueId(CLUE_SCROLL_ELITE_12132)
			.npc("Oneiromancer")
			.location(new ClueArea(2150, 3866, 0))
			.area("Astral altar")
			.question("How many Suqah inhabit Lunar isle?")
			.teleport(LUNAR_MOONCLAN)
			.teleport(SCROLL_LUNAR_ISLE)
			.teleport(LUNAR_HOME_TELEPORT)
			.teleport(BOAT_PIRATES_COVE_TO_LUNAR_ISLE)
			.requirement(new QuestRequirement(LUNAR_DIPLOMACY, true))
			.answer("25")
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "COOL NERD")
			.clueId(CLUE_SCROLL_ELITE_12138)
			.npc("Old crone")
			.location(new ClueArea(3462, 3557, 0))
			.area("East of Slayer Tower")
			.question("What is the combined combat level of each species that live in Slayer tower?")
			.answer("619")
			.teleport(SLAYER_RING_SLAYER_TOWER)
			.teleport(ANCIENT_KHARYRLL)
			.teleport(ARCEUUS_SALVE_GRAVEYARD)
			.teleport(FAIRY_RING_CKS)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.pathObject(new WorldPoint(3461, 3555, 0), DOOR_5244)
			.build(),
		// Challenge ID: 12139
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DR HITMAN")
			.clueId(CLUE_SCROLL_ELITE_12134)
			.npc("Mandrith")
			.location(new ClueArea(3182, 3946, 0))
			.area("Wilderness Resource Area")
			.question("How many scorpions live under the pit?")
			.answer("28")
			.teleport(WILDERNESS_LEVER)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(SCROLL_REVENANT_CAVE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "LADDER MEMO GUV")
			.clueId(CLUE_SCROLL_ELITE_19792)
			.npc("Guard Vemmeldo")
			.location(new ClueArea(2447, 3418, 1))
			.area("Gnome Stronghold Bank")
			.question("How many magic trees can you find inside the Gnome Stronghold?")
			.answer("3")
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.pathObject(new WorldPoint(2444, 3414, 0), STAIRCASE_16675)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "MACHETE CLAM")
			.clueId(CLUE_SCROLL_ELITE_12136)
			.npc("Cam the Camel")
			.location(new ClueArea(3300, 3231, 0))
			.area("Al Kharid, north of the glider")
			.question("How many items can carry water in Gielinor?")
			.answer("6")
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.teleport(GNOME_GLIDER_AL_KHARID)
			.teleport(MINIGAME_CLAN_WARS)
			.build(),
		// Challenge ID: 12139
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "MAJORS LAVA BADS AIR")
			.clueId(CLUE_SCROLL_ELITE_12133)
			.npc("Ambassador Alvijar")
			.location(new ClueArea(2736, 5351, 1))
			.area("Dorgesh-Kaan, NE Middle Level")
			.question("Double the miles before the initial Dorgeshuun veteran.")
			.answer("2505")
			.teleport(DORGESH_KAAN_SPHERE)
			.teleport(FAIRY_RING_AJQ)
			.requirement(new QuestRequirement(DEATH_TO_THE_DORGESHUUN))
			.extraMapPoint(new WorldPoint(3209, 3216, 0))
			.pathObject(new WorldPoint(2729, 5347, 0), STAIRS_22937)
			.pathObject(new WorldPoint(2736, 5353, 1), DOOR_22914)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "NO OWNER")
			.clueId(CLUE_SCROLL_ELITE_12135)
			.npc("Oronwen")
			.location(new ClueArea(1162, 3178, 0))
			.area("Lletya")
			.question("What is the minimum amount of quest points required to reach Lletya?")
			.answer("20")
			.teleport(TELEPORT_CRYSTAL_LLETYA)
			.requirement(new QuestRequirement(MOURNINGS_END_PART_I, true))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "OUR OWN NEEDS")
			.clueId(CLUE_SCROLL_ELITE_19794)
			.npc("Nurse Wooned")
			.location(new ClueArea(1511, 3619, 0))
			.area("Shayzien Infirmary")
			.question("How many wounded soldiers are there in the camp?")
			.answer("16")
			.teleport(XERICS_TALISMAN_XERICS_LOOKOUT)
			.teleport(KHAREDSTS_MEMOIRS_HISTORY_AND_HEARSAY)
			.teleport(FAIRY_RING_DJR)
			.build(),
		// TODO: Question itemId = 12139
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "SNAKES SO I SAIL")
			.clueId(CLUE_SCROLL_ELITE_19795)
			.npc("Lisse Isaakson")
			.location(new ClueArea(2351, 3801, 0))
			.area("Neitiznot")
			.question("How many arctic logs are required to make a large fremennik round shield?")
			.answer("2")
			.teleport(ENCHANTED_LYRE_NEITIZNOT)
			.teleport(BOAT_RELLEKKA_TO_NEITIZNOT)
			.requirement(new QuestRequirement(THE_FREMENNIK_ISLES, true))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "UNLEASH NIGHT MIST")
			.clueId(CLUE_SCROLL_ELITE_12137)
			.npc("Sigli the Huntsman")
			.location(new ClueArea(2660, 3654, 0))
			.area("Rellekka entrance")
			.question("What is the combined slayer requirement of every monster in the slayer cave?")
			.answer("302")
			.teleport(ENCHANTED_LYRE_RELLEKKA)
			.teleport(TELEPORT_TO_HOUSE_RELLEKKA)
			.teleport(FREMENNIK_SEA_BOOTS)
			.teleport(FAIRY_RING_AJR)
			.build(),

		// Master
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "A ELF KNOWS")
			.npc("Snowflake")
			.location(new ClueArea(2872, 3934, 0))
			.area("Weiss")
			.teleport(ICY_BASALT)
			.teleport(BOAT_NORTH_EAST_OF_RELLEKKA_TO_WEISS)
			.requirement(new QuestRequirement(MAKING_FRIENDS_WITH_MY_ARM))
			.build(),
		// TODO
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "BRUCIE CATNAP")
			.npc("Captain Bruce")
			.location(new ClueArea(1520, 3558, 0))
			.area("TODO")
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "CAR IF ICES")
			.npc("Sacrifice")
			.location(new ClueArea(2209, 3056, 0))
			.area("Zul-Andra")
			.teleport(SCROLL_ZUL_ANDRA)
			.teleport(FAIRY_RING_BJS)
			.teleport(CHARTER_SHIP_PORT_TYRAS)
			.requirement(new QuestRequirement(REGICIDE, true))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DED WAR")
			.npc("Edward")
			.location(new ClueArea(3284, 3943, 0))
			.area("Around Rogue's Castle")
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_LEVER)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DIM THARN")
			.npc("Mandrith")
			.location(new ClueArea(3182, 3946, 0))
			.area("Wilderness Resource Area")
			.teleport(WILDERNESS_LEVER)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(SCROLL_REVENANT_CAVE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "DUO PLUG")
			.npc("Dugopul")
			.location(new ClueArea(2803, 2744, 0))
			.area("Ape Atoll graveyard")
			.teleport(STANDARD_APE_ATOLL)
			.teleport(FAIRY_RING_CLR)
			.teleport(GNOME_GLIDER_APE_ATOLL)
			.requirement(new QuestRequirement(MONKEY_MADNESS_I, true))
			.requirement(new OrRequirement("Greegree",
				new EquipmentRequirement(KARAMJAN_MONKEY_GREEGREE),
				new EquipmentRequirement(KRUK_MONKEY_GREEGREE),
				new EquipmentRequirement(NINJA_MONKEY_GREEGREE),
				new EquipmentRequirement(NINJA_MONKEY_GREEGREE_4025),
				new EquipmentRequirement(ANCIENT_GORILLA_GREEGREE),
				new EquipmentRequirement(BEARDED_GORILLA_GREEGREE),
				new EquipmentRequirement(GORILLA_GREEGREE),
				new EquipmentRequirement(ZOMBIE_MONKEY_GREEGREE),
				new EquipmentRequirement(ZOMBIE_MONKEY_GREEGREE_4030),
				new QuestRequirement(MONKEY_MADNESS_II)))
			.requirement(new OrRequirement("M'speak Amulet",
				new EquipmentRequirement(MSPEAK_AMULET),
				new QuestRequirement(MONKEY_MADNESS_II)))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "FORLUN")
			.npc("Runolf")
			.location(new ClueArea(2512, 10256, 0))
			.area("Miscellania Dungeon")
			.teleport(RING_OF_WEALTH_MISCELLANIA)
			.teleport(FAIRY_RING_CIP)
			.teleport(SPIRIT_TREE_ETCETERIA)
			.teleport(BOAT_RELLEKKA_TO_MISCELLANIA)
			.requirement(new QuestRequirement(ROYAL_TROUBLE, true))
			.extraMapPoint(new WorldPoint(2509, 3846, 0))
			.pathObject(new WorldPoint(2509, 3846, 0), LADDER_15116)
			.build(),
		// TODO: Add new crop circles
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "IM N ZEZIM")
			.npc("Immenizz")
			.location(new ClueArea(2592, 4324, 0))
			.area("Puro-Puro")
			.teleport(FAIRY_RING_ZANARIS)
			.requirement(new SkillRequirement(HUNTER, 17))
			.extraMapPoint(new WorldPoint(2427, 4446, 0))
			.extraMapPoint(new WorldPoint(3141, 3461, 0))
			.extraMapPoint(new WorldPoint(3115, 3273, 0))
			.extraMapPoint(new WorldPoint(3160, 3299, 0))
			.extraMapPoint(new WorldPoint(2582, 3104, 0))
			.extraMapPoint(new WorldPoint(2978, 3216, 0))
			.extraMapPoint(new WorldPoint(2647, 3348, 0))
			.extraMapPoint(new WorldPoint(2953, 3444, 0))
			.extraMapPoint(new WorldPoint(2538, 3845, 0))
			.pathObject(new WorldPoint(2427, 4446, 0), CENTRE_OF_CROP_CIRCLE_24991)
			.pathObject(new WorldPoint(3141, 3461, 0), CENTRE_OF_CROP_CIRCLE)
			.pathObject(new WorldPoint(3115, 3273, 0), CENTRE_OF_CROP_CIRCLE)
			.pathObject(new WorldPoint(3160, 3299, 0), CENTRE_OF_CROP_CIRCLE)
			.pathObject(new WorldPoint(2582, 3104, 0), CENTRE_OF_CROP_CIRCLE)
			.pathObject(new WorldPoint(2978, 3216, 0), CENTRE_OF_CROP_CIRCLE)
			.pathObject(new WorldPoint(2647, 3348, 0), CENTRE_OF_CROP_CIRCLE)
			.pathObject(new WorldPoint(2953, 3444, 0), CENTRE_OF_CROP_CIRCLE)
			.pathObject(new WorldPoint(2538, 3845, 0), CENTRE_OF_CROP_CIRCLE)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "MAL IN TAU")
			.npc("Luminata")
			.location(new ClueArea(3508, 3237, 0))
			.area("Burgh de Rott, near general store")
			.teleport(MORYTANIA_LEGS_3_BURGH_DE_ROTT)
			.teleport(SCROLL_MORTTON)
			.teleport(MINIGAME_SHADES_OF_MORTTON)
			.requirement(new QuestRequirement(IN_AID_OF_THE_MYREQUE, true))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "MOLD LA RAN")
			.npc("Old Man Ral")
			.location(new ClueArea(3602, 3209, 0))
			.area("Meiyerditch")
			.teleport(DRAKANS_MEDALLION_VER_SINHAZA)
			.teleport(BOAT_PORT_PHASMATYS_TO_SLEPE)
			.teleport(BOAT_BURGH_DE_ROTT_TO_MEIYERDITCH)
			.requirement(new QuestRequirement(DARKNESS_OF_HALLOWVALE, true))
			.pathObject(new WorldPoint(3606, 3206, 0), DOOR_17601)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "MUS KIL READER")
			.npc("Radimus Erkle")
			.location(new ClueArea(2726, 3368, 0))
			.area("Legends' Guild")
			.teleport(QUEST_CAPE)
			.teleport(FAIRY_RING_BLR)
			.teleport(STANDARD_ARDOUGNE)
			.requirement(new QuestRequirement(LEGENDS_QUEST, true))
			.pathObject(new WorldPoint(2728, 3349, 0), GATE_2391)
			.pathObject(new WorldPoint(2729, 3349, 0), GATE_2392)
			.pathObject(new WorldPoint(2726, 3368, 0), DOOR_1540)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "RIP MAUL")
			.npc("Primula")
			.location(new ClueArea(2454, 2853, 1))
			.area("Myths' Guild, 1st floor")
			.teleport(MYTHICAL_CAPE)
			.teleport(SPIRIT_TREE_FELDIP_HILLS)
			.requirement(new QuestRequirement(DRAGON_SLAYER_II))
			.pathObject(new WorldPoint(2457, 2837, 0), STAIRS_31627)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "RUE GO")
			.npc("Goreu")
			.location(new ClueArea(2335, 3162, 0))
			.area("Lletya")
			.teleport(TELEPORT_CRYSTAL_LLETYA)
			.requirement(new QuestRequirement(MOURNINGS_END_PART_I, true))
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "SLAM DUSTER GRAIL")
			.npc("Guildmaster Lars")
			.location(new ClueArea(1649, 3498, 0))
			.area("Woodcutting Guild, Hosidius")
			.teleport(SKILLS_NECKLACE_WOODCUTTING_GUILD)
			.teleport(SPIRIT_TREE_HOSIDIUS)
			.teleport(XERICS_TALISMAN_XERICS_LOOKOUT)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.requirement(new SkillRequirement(WOODCUTTING, 60))
			.requirement(new FavourRequirement(Favour.HOSIDIUS, 75))
			.pathObject(new WorldPoint(1657, 3504, 0), GATE_28852)
			.pathObject(new WorldPoint(1657, 3505, 0), GATE_28851)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "TEN WIGS ON")
			.npc("Wingstone")
			.location(new ClueArea(3389, 2877, 0))
			.area("North of Agility Pyramid")
			.teleport(SCROLL_NARDAH)
			.teleport(DESERT_AMULET_2_NARDAH)
			.teleport(PHARAOHS_SCEPTER_JALEUSTROPHOS)
			.teleport(FAIRY_RING_DLQ)
			.build(),
		AnagramClue.builder()
			.text(ANAGRAM_TEXT + "TWENTY CURE IRON")
			.npc("New Recruit Tony")
			.location(new ClueArea(1503, 3553, 0))
			.area("Shayzien Graveyard")
			.teleport(KHAREDSTS_MEMOIRS_HISTORY_AND_HEARSAY)
			.teleport(XERICS_TALISMAN_XERICS_LOOKOUT)
			.teleport(FAIRY_RING_DJR)
			.build()
	);

	private final String type = "Anagram Clue";

	@Nullable
	public static AnagramClue forText(String text)
	{
		for (AnagramClue clue : CLUES)
		{
			if (text.equalsIgnoreCase(clue.getText())
				|| text.equalsIgnoreCase(clue.getQuestion()))
			{
				return clue;
			}
		}

		return null;
	}
}
