/*
 * Copyright (c) 2018, Lotto <https://github.com/devLotto>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package emerald000.cluehelper.clues;

import com.google.common.collect.ImmutableList;
import java.util.List;
import javax.annotation.Nullable;
import lombok.Getter;
import lombok.experimental.SuperBuilder;
import lombok.extern.slf4j.Slf4j;
import static net.runelite.client.plugins.achievementdiary.FavourRequirement.Favour.HOSIDIUS;
import static net.runelite.client.plugins.achievementdiary.FavourRequirement.Favour.SHAYZIEN;
import static net.runelite.api.ItemID.*;
import static net.runelite.api.ItemID.ROPE;
import static net.runelite.api.ItemID.SPADE;
import static net.runelite.api.NullObjectID.NULL_18122;
import static net.runelite.api.NullObjectID.NULL_29916;
import static net.runelite.api.ObjectID.*;
import static net.runelite.api.ObjectID.ROCK;
import net.runelite.api.Quest;
import static net.runelite.api.Quest.WATCHTOWER;
import static net.runelite.api.Quest.*;
import static net.runelite.api.Skill.AGILITY;
import static net.runelite.api.Skill.FARMING;
import net.runelite.api.Varbits;
import net.runelite.api.coords.WorldPoint;
import static emerald000.cluehelper.clues.Enemy.ANCIENT_WIZARDS;
import static emerald000.cluehelper.clues.Enemy.ARMADYLEAN_GUARD;
import static emerald000.cluehelper.clues.Enemy.ARMADYLEAN_OR_BANDOSIAN_GUARD;
import static emerald000.cluehelper.clues.Enemy.BANDOSIAN_GUARD;
import static emerald000.cluehelper.clues.Enemy.BRASSICAN_MAGE;
import static emerald000.cluehelper.clues.Enemy.SARADOMIN_WIZARD;
import static emerald000.cluehelper.clues.Enemy.ZAMORAK_WIZARD;
import emerald000.cluehelper.clues.requirement.AndRequirement;
import static emerald000.cluehelper.clues.requirement.CommonRequirement.CAN_USE_GHOSTSPEAK_AMULET;
import static emerald000.cluehelper.clues.requirement.CommonRequirement.HAS_FACEMASK;
import emerald000.cluehelper.clues.requirement.DiaryRequirement;
import static emerald000.cluehelper.clues.requirement.DiaryRequirement.DiaryLevel.ELITE;
import static emerald000.cluehelper.clues.requirement.DiaryRequirement.DiaryRegion.KARAMJA;
import emerald000.cluehelper.clues.requirement.EquipmentRequirement;
import emerald000.cluehelper.clues.requirement.FavourRequirement;
import emerald000.cluehelper.clues.requirement.InventoryRequirement;
import emerald000.cluehelper.clues.requirement.KharaziJungleEntranceRequirement;
import emerald000.cluehelper.clues.requirement.MountainCampRequirement;
import emerald000.cluehelper.clues.requirement.OrRequirement;
import emerald000.cluehelper.clues.requirement.QuestRequirement;
import emerald000.cluehelper.clues.requirement.RecommendedRequirement;
import emerald000.cluehelper.clues.requirement.ResourceAreaEntranceRequirement;
import emerald000.cluehelper.clues.requirement.SkillRequirement;
import emerald000.cluehelper.clues.requirement.WaterbirthIslandAccessRequirement;
import emerald000.cluehelper.clues.teleport.CombinedTeleport;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.*;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.CHRONICLE;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.ECTOPHIAL;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.FARMING_CAPE;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.FREMENNIK_SEA_BOOTS;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.ICY_BASALT;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.ROYAL_SEED_POD;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.SKULL_SCEPTRE;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.STONY_BASALT;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.WESTERN_BANNER_3;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.WILDERNESS_CRABS_TELEPORT;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.WILDERNESS_SWORD_3;

@Getter
@SuperBuilder
@Slf4j
public class CoordinateClue extends ClueScroll
{
	private static final List<CoordinateClue> CLUES = ImmutableList.of(
		// Medium
		CoordinateClue.builder()
			.text("00 degrees 05 minutes south 01 degrees 13 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2809)
			.location(new ClueArea(2478, 3157, 2480, 3159, 0))
			.area("West of Tree Gnome Village")
			.teleport(FAIRY_RING_CIQ)
			.teleport(STANDARD_YANILLE)
			.build(),
		CoordinateClue.builder()
			.text("00 degrees 13 minutes south 13 degrees 58 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_3588)
			.location(new ClueArea(2886, 3153, 2888, 3155, 0))
			.area("Karamja, west of banana plantation")
			.teleport(AMULET_OF_GLORY_KARAMJA)
			.teleport(CHARTER_SHIP_MUSA_POINT)
			.build(),
		CoordinateClue.builder()
			.text("00 degrees 18 minutes south 09 degrees 28 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_3590)
			.location(new ClueArea(2742, 3150, 2744, 3152, 0))
			.area("Brimhaven Dungeon, outside north entrance")
			.teleport(TELEPORT_TO_HOUSE_BRIMHAVEN)
			.teleport(SPIRIT_TREE_BRIMHAVEN)
			.teleport(BOAT_CAPTAIN_BARNABY_TO_BRIMHAVEN)
			.build(),
		CoordinateClue.builder()
			.text("00 degrees 20 minutes south 23 degrees 15 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_7313)
			.location(new ClueArea(3183, 3149, 3185, 3151, 0))
			.area("South of Lumbridge Swamp")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		CoordinateClue.builder()
			.text("00 degrees 30 minutes north 24 degrees 16 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2823)
			.location(new ClueArea(3216, 3176, 3218, 3178, 0))
			.area("East of Lumbridge Swamp")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		CoordinateClue.builder()
			.text("00 degrees 31 minutes south 17 degrees 43 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2819)
			.location(new ClueArea(3006, 3143, 3008, 3145, 0))
			.area("Asgarnian Ice Dungeon, outside entrance")
			.teleport(FAIRY_RING_AIQ)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.build(),
		CoordinateClue.builder()
			.text("01 degrees 18 minutes south 14 degrees 15 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_7309)
			.location(new ClueArea(2895, 3118, 2897, 3120, 0))
			.area("Karamja, Karambwan fishing spot")
			.teleport(FAIRY_RING_DKP)
			.build(),
		CoordinateClue.builder()
			.text("01 degrees 26 minutes north 08 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2805)
			.location(new ClueArea(2696, 3206, 2698, 3208, 0))
			.area("Moss Giant Island, west of Brimhaven.")
			.teleport(TELEPORT_TO_HOUSE_BRIMHAVEN)
			.teleport(SPIRIT_TREE_BRIMHAVEN)
			.teleport(BOAT_CAPTAIN_BARNABY_TO_BRIMHAVEN)
			.requirement(new SkillRequirement(AGILITY, 10))
			.pathObject(new WorldPoint(2707, 3209, 0), ROPESWING_23568)
			.build(),
		CoordinateClue.builder()
			.text("01 degrees 35 minutes south 07 degrees 28 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2803)
			.location(new ClueArea(2678, 3109, 2680, 3111, 0))
			.area("North of Hazelmere")
			.teleport(FAIRY_RING_CLS)
			.teleport(STANDARD_YANILLE)
			.teleport(MINIGAME_NIGHTMARE_ZONE)
			.build(),
		CoordinateClue.builder()
			.text("2 degrees 16 minutes north 12 degrees 7 minutes east")
			.location(new ClueArea(2827, 3233, 2829, 3235, 0))
			.area("Crandor island south coast")
			.teleport(AMULET_OF_GLORY_KARAMJA)
			.teleport(SPIRIT_TREE_BRIMHAVEN)
			.teleport(TELEPORT_TO_HOUSE_BRIMHAVEN)
			.teleport(CHARTER_SHIP_MUSA_POINT)
			.requirement(new QuestRequirement(Quest.DRAGON_SLAYER_I, true))
			.extraMapPoint(new WorldPoint(2856, 3168, 0))
			.pathObject(new WorldPoint(2856, 3168, 0), ROCKS_11441)
			.pathObject(new WorldPoint(2836, 9600, 0), WALL_2606)
			.pathObject(new WorldPoint(2833, 9657, 0), CLIMBING_ROPE_25213)
			.build(),
		CoordinateClue.builder()
			.text("02 degrees 43 minutes south 33 degrees 26 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_12035)
			.location(new ClueArea(3509, 3073, 3511, 3075, 0))
			.area("East of Uzer")
			.teleport(NECKLACE_OF_PASSAGE_EAGLES_EYRIE)
			.teleport(FAIRY_RING_DLQ)
			.build(),
		CoordinateClue.builder()
			.text("02 degrees 48 minutes north 22 degrees 30 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM) // 2801
			.location(new ClueArea(3159, 3250, 3161, 3252, 0))
			.area("H.A.M. Hideout entrance")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		CoordinateClue.builder()
			.text("02 degrees 50 minutes north 06 degrees 20 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2813)
			.location(new ClueArea(2642, 3251, 2644, 3253, 0))
			.area("North of Tower of Life")
			.teleport(ARDOUGNE_CLOAK_MONASTERY)
			.teleport(STANDARD_ARDOUGNE)
			.teleport(FAIRY_RING_DJP)
			.build(),
		CoordinateClue.builder()
			.text("03 degrees 07 minutes south 03 degrees 41 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_12041)
			.location(new ClueArea(2321, 3060, 2323, 3062, 0))
			.area("South-west of Castle Wars")
			.teleport(FAIRY_RING_BKP)
			.teleport(RING_OF_DUELING_CASTLE_WARS)
			.build(),
		CoordinateClue.builder()
			.text("03 degrees 35 minutes south 13 degrees 35 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_7317)
			.location(new ClueArea(2874, 3045, 2876, 3047, 0))
			.area("Karamja, north of nature altar")
			.teleport(SCROLL_TAI_BWO_WANNAI)
			.teleport(FAIRY_RING_CKR)
			.build(),
		CoordinateClue.builder()
			.text("04 degrees 00 minutes south 12 degrees 46 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2817)
			.location(new ClueArea(2848, 3032, 2850, 3034, 0))
			.area("Tai Bwo Wannai mine")
			.teleport(SCROLL_TAI_BWO_WANNAI)
			.teleport(FAIRY_RING_CKR)
			.build(),
		CoordinateClue.builder()
			.text("04 degrees 13 minutes north 12 degrees 45 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2815)
			.location(new ClueArea(2847, 3295, 2849, 3297, 0))
			.area("Crandor island north coast")
			.teleport(AMULET_OF_GLORY_KARAMJA)
			.teleport(SPIRIT_TREE_BRIMHAVEN)
			.teleport(TELEPORT_TO_HOUSE_BRIMHAVEN)
			.teleport(CHARTER_SHIP_MUSA_POINT)
			.requirement(new QuestRequirement(Quest.DRAGON_SLAYER_I, true))
			.extraMapPoint(new WorldPoint(2856, 3168, 0))
			.pathObject(new WorldPoint(2856, 3168, 0), ROCKS_11441)
			.pathObject(new WorldPoint(2836, 9600, 0), WALL_2606)
			.pathObject(new WorldPoint(2833, 9657, 0), CLIMBING_ROPE_25213)
			.build(),
		CoordinateClue.builder()
			.text("05 degrees 20 minutes south 04 degrees 28 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_7307)
			.location(new ClueArea(2582, 2989, 2584, 2991, 0))
			.area("Feldip Hills, south-east of Gu'Tanoth")
			.teleport(FAIRY_RING_AKS)
			.teleport(GNOME_GLIDER_FELDIP_HILLS)
			.teleport(SCROLL_FELDIP_HILLS)
			.build(),
		CoordinateClue.builder()
			.text("05 degrees 43 minutes north 23 degrees 05 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2825)
			.location(new ClueArea(3178, 3343, 3180, 3345, 0))
			.area("Lumbridge, north cow pen")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3176, 3315, 0), GATE_883)
			.pathObject(new WorldPoint(3177, 3315, 0), GATE_23917)
			.build(),
		CoordinateClue.builder()
			.text("06 degrees 31 minutes north 01 degrees 46 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_2807)
			.location(new ClueArea(2382, 3369, 2384, 3371, 0))
			.area("West of the Outpost")
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.build(),
		CoordinateClue.builder()
			.text("06 degrees 41 minutes north 27 degrees 15 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_12051)
			.location(new ClueArea(3311, 3374, 3313, 3376, 0))
			.area("Digsite hill, NW of exam center")
			.teleport(SCROLL_DIGSITE)
			.teleport(ANCIENT_SENNTISTEN)
			.teleport(DIGSITE_PENDANT_DIGSITE)
			.build(),
		CoordinateClue.builder()
			.text("06 degrees 58 minutes north 21 degrees 16 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_12043)
			.location(new ClueArea(3120, 3383, 3122, 3385, 0))
			.area("North-east of Draynor Manor")
			.teleport(SKULL_SCEPTRE)
			.teleport(COMBAT_BRACELET_CHAMPIONS_GUILD)
			.teleport(ARCEUUS_DRAYNOR_MANOR)
			.teleport(CHRONICLE)
			.build(),
		CoordinateClue.builder()
			.text("07 degrees 05 minutes north 30 degrees 56 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_3584)
			.location(new ClueArea(3429, 3387, 3431, 3389, 0))
			.area("West of Mort Myre Swamp")
			.teleport(FAIRY_RING_BKR)
			.teleport(ARCEUUS_SALVE_GRAVEYARD)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.build(),
		CoordinateClue.builder()
			.text("07 degrees 33 minutes north 15 degrees 00 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2821)
			.location(new ClueArea(2919, 3402, 2921, 3404, 0))
			.area("Taverley, near Lady of the Lake")
			.teleport(HOT_AIR_BALLOON_TAVERLEY)
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.build(),
		CoordinateClue.builder()
			.text("08 degrees 11 minutes south 04 degrees 48 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_12033)
			.location(new ClueArea(2593, 2898, 2595, 2900, 0))
			.area("South-east of Feldip Hills")
			.teleport(HUNTER_CAPE_CARNIVOROUS_CHINCHOMPAS)
			.teleport(SCROLL_FELDIP_HILLS)
			.teleport(FAIRY_RING_AKS)
			.build(),
		CoordinateClue.builder()
			.text("08 degrees 33 minutes north 01 degrees 39 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_3592)
			.location(new ClueArea(2386, 3434, 2388, 3436, 0))
			.area("Tree Gnome Stronghold, terrorbirds pen")
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.pathObject(new WorldPoint(2384, 3436, 0), GATE_1558)
			.pathObject(new WorldPoint(2384, 3437, 0), GATE_1560)
			.build(),
		CoordinateClue.builder()
			.text("09 degrees 33 minutes north 02 degrees 15 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_2811)
			.location(new ClueArea(2511, 3466, 2513, 3468, 0))
			.area("Baxtorian Falls")
			.teleport(GAMES_NECKLACE_BARBARIAN_OUTPOST)
			.teleport(MINIGAME_BARBARIAN_ASSAULT)
			.requirement(new QuestRequirement(WATERFALL_QUEST, true))
			.requirement(new InventoryRequirement(ROPE))
			.pathObject(new WorldPoint(2528, 3495, 0), GATE_1558)
			.pathObject(new WorldPoint(2528, 3496, 0), GATE_1560)
			.pathObject(new WorldPoint(2525, 3495, 0), DOOR_1540)
			.pathObject(new WorldPoint(2513, 3494, 0), GATE_1558)
			.pathObject(new WorldPoint(2513, 3495, 0), GATE_1560)
			.pathObject(new WorldPoint(2509, 3493, 0), LOG_RAFT)
			.pathObject(new WorldPoint(2512, 3468, 0), ROCK)
			.build(),
		CoordinateClue.builder()
			.text("09 degrees 35 minutes north 01 degrees 50 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_12045)
			.location(new ClueArea(2380, 3467, 2382, 3469, 0))
			.area("Tree Gnome Stronghold, north of terrorbirds pen")
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.pathObject(new WorldPoint(2384, 3436, 0), GATE_1558)
			.pathObject(new WorldPoint(2384, 3437, 0), GATE_1560)
			.build(),
		CoordinateClue.builder()
			.text("09 degrees 48 minutes north 17 degrees 39 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_7311)
			.location(new ClueArea(3004, 3474, 3006, 3476, 0))
			.area("Ice Mountain")
			.teleport(ANCIENT_LASSAR)
			.teleport(COMBAT_BRACELET_MONASTERY)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.build(),
		CoordinateClue.builder()
			.text("10 degrees 45 minutes north 04 degrees 31 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_12049)
			.location(new ClueArea(2584, 3504, 2586, 3506, 0))
			.area("North of the Coal Trucks")
			.teleport(COMBAT_BRACELET_RANGING_GUILD)
			.teleport(FAIRY_RING_ALS)
			.pathObject(new WorldPoint(2602, 3477, 0), LOG_BALANCE_23274)
			.build(),
		CoordinateClue.builder()
			.text("11 degrees 03 minutes north 31 degrees 20 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_3582)
			.location(new ClueArea(3442, 3514, 3444, 3516, 0))
			.area("South of Slayer Tower")
			.teleport(SLAYER_RING_SLAYER_TOWER)
			.teleport(FAIRY_RING_CKS)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.build(),
		CoordinateClue.builder()
			.text("11 degrees 05 minutes north 00 degrees 45 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_3594)
			.location(new ClueArea(2415, 3515, 2417, 3517, 0))
			.area("Tree Gnome Stronghold swamp")
			.teleport(ROYAL_SEED_POD)
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.build(),
		CoordinateClue.builder()
			.text("11 degrees 18 minutes north 30 degrees 54 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_12053)
			.location(new ClueArea(3428, 3522, 3430, 3524, 0))
			.area("South of Slayer Tower")
			.teleport(SLAYER_RING_SLAYER_TOWER)
			.teleport(FAIRY_RING_CKS)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.build(),
		CoordinateClue.builder()
			.text("11 degrees 33 minutes north 02 degrees 24 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_12047)
			.location(new ClueArea(2362, 3530, 2364, 3532, 0))
			.area("North-east of Eagles' Peak")
			.teleport(new CombinedTeleport("Scroll: Piscatoris (Take Boat)",
				SCROLL_PISCATORIS,
				BOAT_PISCATORIS_TO_GNOME_STRONGHOLD))
			.teleport(FAIRY_RING_AKQ)
			.build(),
		CoordinateClue.builder()
			.text("11 degrees 41 minutes north 14 degrees 58 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_3586)
			.location(new ClueArea(2918, 3534, 2920, 3536, 0))
			.area("Burthorpe pub")
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(MINIGAME_BURTHORPE)
			.pathObject(new WorldPoint(2907, 3544, 0), DOOR_1540)
			.pathObject(new WorldPoint(2916, 3537, 0), DOOR_1540)
			.build(),
		CoordinateClue.builder()
			.text("12 degrees 28 minutes north 34 degrees 37 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_12037)
			.location(new ClueArea(3547, 3559, 3549, 3561, 0))
			.area("Fenkenstrain's Castle")
			.teleport(ARCEUUS_FENKENSTRAINS_CASTLE)
			.teleport(FAIRY_RING_ALQ)
			.teleport(ECTOPHIAL)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.pathObject(new WorldPoint(3548, 3535, 0), DOOR_5183)
			.pathObject(new WorldPoint(3549, 3535, 0), DOOR_5186)
			.pathObject(new WorldPoint(3548, 3543, 0), DOOR_5183)
			.pathObject(new WorldPoint(3549, 3543, 0), DOOR_5186)
			.pathObject(new WorldPoint(3548, 3551, 0), DOOR_5183)
			.pathObject(new WorldPoint(3549, 3551, 0), DOOR_5186)
			.pathObject(new WorldPoint(3549, 3558, 0), DOOR_5183)
			.pathObject(new WorldPoint(3548, 3558, 0), DOOR_5186)
			.build(),
		// TODO: Moved
		CoordinateClue.builder()
			.text("14 degrees 20 minutes north 30 degrees 45 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_19774)
			.location(new ClueArea(1455, 3619, 1457, 3621, 0))
			.area("South of Chasm of Fire")
			.teleport(KHAREDSTS_MEMOIRS_HISTORY_AND_HEARSAY)
			.teleport(FAIRY_RING_DJR)
			.build(),
		CoordinateClue.builder()
			.text("14 degrees 54 minutes north 09 degrees 13 minutes east")
			.location(new ClueArea(2734, 3637, 2736, 3639, 0))
			.area("East of Rellekka, by swaying tree")
			.teleport(SLAYER_RING_FREMENNIK_SLAYER_DUNGEON)
			.teleport(TELEPORT_TO_HOUSE_RELLEKKA)
			.teleport(FAIRY_RING_AJR)
			.build(),
		CoordinateClue.builder()
			.text("15 degrees 22 minutes north 07 degrees 31 minutes east")
			.location(new ClueArea(2680, 3652, 2682, 3654, 0))
			.area("Rellekka, south-east garden")
			.teleport(ENCHANTED_LYRE_RELLEKKA)
			.teleport(TELEPORT_TO_HOUSE_RELLEKKA)
			.teleport(FREMENNIK_SEA_BOOTS)
			.build(),
		CoordinateClue.builder()
			.text("17 degrees 39 minutes north 37 degrees 16 minutes west")
			.clueId(CLUE_SCROLL_MEDIUM_23135)
			.location(new ClueArea(1246, 3725, 1248, 3727, 0))
			.area("Farming Guild")
			.teleport(SKILLS_NECKLACE_FARMING_GUILD)
			.teleport(FARMING_CAPE)
			.teleport(FAIRY_RING_CIR)
			.requirement(new SkillRequirement(FARMING, 45))
			.requirement(new FavourRequirement(HOSIDIUS, 60))
			.pathObject(new WorldPoint(1248, 3723, 0), DOOR_34463)
			.pathObject(new WorldPoint(1249, 3723, 0), DOOR_34464)
			.build(),
		CoordinateClue.builder()
			.text("22 degrees 30 minutes north 03 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_7305)
			.location(new ClueArea(2536, 3880, 2538, 3882, 0))
			.area("Miscellania")
			.teleport(RING_OF_WEALTH_MISCELLANIA)
			.teleport(FAIRY_RING_CIP)
			.teleport(SPIRIT_TREE_ETCETERIA)
			.teleport(BOAT_RELLEKKA_TO_MISCELLANIA)
			.build(),
		CoordinateClue.builder()
			.text("23 degrees 1 minute north 41 degrees 33 minutes east")
			.clueId(CLUE_SCROLL_MEDIUM_23137)
			.location(new ClueArea(3769, 3897, 3771, 3899, 0))
			.area("Fossil Island, north-east island")
			.teleport(DIGSITE_PENDANT_DIGSITE)
			.teleport(SCROLL_DIGSITE)
			.requirement(new QuestRequirement(BONE_VOYAGE))
			.pathObject(new WorldPoint(3724, 3805, 0), ROWBOAT_30914)
			.pathObject(new WorldPoint(3735, 3894, 0), ROWBOAT_30915)
			.build(),

		// Hard
		CoordinateClue.builder()
			.text("00 degrees 00 minutes north 07 degrees 13 minutes west")
			.clueId(CLUE_SCROLL_HARD_3560)
			.location(new ClueArea(2208, 3160, 2210, 3162, 0))
			.area("North-east of Tyras Camp")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_BJS)
			.teleport(CHARTER_SHIP_PORT_TYRAS)
			.teleport(SCROLL_ZUL_ANDRA)
			.requirement(new QuestRequirement(REGICIDE, true))
			.pathObject(new WorldPoint(2188, 3163, 0), DENSE_FOREST_3999)
			.pathObject(new WorldPoint(2188, 3166, 0), DENSE_FOREST_3939)
			.pathObject(new WorldPoint(2188, 3169, 0), DENSE_FOREST_3998)
			.pathObject(new WorldPoint(2201, 3169, 0), STICKS)
			.build(),
		CoordinateClue.builder()
			.text("01 degrees 24 minutes north 08 degrees 05 minutes west")
			.clueId(CLUE_SCROLL_HARD_3562)
			.location(new ClueArea(2180, 3205, 2182, 3207, 0))
			.area("South of Iorwerth Camp")
			.enemy(SARADOMIN_WIZARD)
			.teleport(SCROLL_IORWERTH_CAMP)
			.teleport(TELEPORT_CRYSTAL_PRIFDDINAS)
			.teleport(TELEPORT_TO_HOUSE_PRIFDDINAS)
			.teleport(FAIRY_RING_BJS)
			.teleport(CHARTER_SHIP_PORT_TYRAS)
			.requirement(new QuestRequirement(REGICIDE, true))
			.pathObject(new WorldPoint(2181, 3209, 0), STICKS)
			.build(),
		CoordinateClue.builder()
			.text("01 degrees 30 minutes north 20 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_HARD_12554)
			.location(new ClueArea(3080, 3208, 3082, 3210, 0))
			.area("Island near Draynor Village")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_CLP)
			.requirement(new QuestRequirement(FAIRYTALE_II__CURE_A_QUEEN, true))
			.build(),
		CoordinateClue.builder()
			.text("02 degrees 39 minutes north 29 degrees 58 minutes east")
			.clueId(CLUE_SCROLL_HARD_3554)
			.location(new ClueArea(3398, 3245, 3400, 3247, 0))
			.area("Behind the Duel Arena")
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.build(),
		CoordinateClue.builder()
			.text("02 degrees 48 minutes north 08 degrees 05 minutes east")
			.location(new ClueArea(2698, 3250, 2700, 3252, 0))
			.area("Island near Ardougne")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_AIR)
			.requirement(new QuestRequirement(FAIRYTALE_II__CURE_A_QUEEN, true))
			.build(),
		CoordinateClue.builder()
			.text("2 degrees 48 minutes north 34 degrees 33 minutes east")
			.clueId(CLUE_SCROLL_HARD_19844)
			.location(new ClueArea(3545, 3250, 3547, 3252, 0))
			.area("East of Burgh de Rott")
			.enemy(SARADOMIN_WIZARD)
			.teleport(MORYTANIA_LEGS_3_BURGH_DE_ROTT)
			.teleport(SCROLL_MORTTON)
			.teleport(MINIGAME_SHADES_OF_MORTTON)
			.requirement(new QuestRequirement(IN_AID_OF_THE_MYREQUE, true))
			.build(),
		CoordinateClue.builder()
			.text("02 degrees 58 minutes north 34 degrees 30 minutes east")
			.clueId(CLUE_SCROLL_HARD_12562)
			.location(new ClueArea(3543, 3255, 3545, 3257, 0))
			.area("East of Burgh de Rott")
			.enemy(SARADOMIN_WIZARD)
			.teleport(MORYTANIA_LEGS_3_BURGH_DE_ROTT)
			.teleport(SCROLL_MORTTON)
			.teleport(MINIGAME_SHADES_OF_MORTTON)
			.requirement(new QuestRequirement(IN_AID_OF_THE_MYREQUE, true))
			.build(),
		CoordinateClue.builder()
			.text("03 degrees 18 minutes north 12 degrees 31 minutes east")
			.clueId(CLUE_SCROLL_HARD_12560)
			.location(new ClueArea(2840, 3266, 2842, 3268, 0))
			.area("Center of Crandor island")
			.enemy(SARADOMIN_WIZARD)
			.teleport(AMULET_OF_GLORY_KARAMJA)
			.teleport(SPIRIT_TREE_BRIMHAVEN)
			.teleport(TELEPORT_TO_HOUSE_BRIMHAVEN)
			.teleport(CHARTER_SHIP_MUSA_POINT)
			.requirement(new QuestRequirement(Quest.DRAGON_SLAYER_I, true))
			.extraMapPoint(new WorldPoint(2856, 3168, 0))
			.pathObject(new WorldPoint(2856, 3168, 0), ROCKS_11441)
			.pathObject(new WorldPoint(2836, 9600, 0), WALL_2606)
			.pathObject(new WorldPoint(2833, 9657, 0), CLIMBING_ROPE_25213)
			.build(),
		CoordinateClue.builder()
			.text("03 degrees 45 minutes south 22 degrees 45 minutes east")
			.clueId(CLUE_SCROLL_HARD_3552)
			.location(new ClueArea(3167, 3040, 3169, 3042, 0))
			.area("Bedabin Camp")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_BIQ)
			.teleport(MAGIC_CARPET_BEDABIN_CAMP)
			.build(),
		// TODO: Shortcut: 71 agility + watchtower completion
		CoordinateClue.builder()
			.text("04 degrees 03 minutes south 03 degrees 11 minutes east")
			.clueId(CLUE_SCROLL_HARD_3546)
			.location(new ClueArea(2541, 3030, 2543, 3032, 0))
			.area("Gu'Tanoth")
			.enemy(SARADOMIN_WIZARD)
			.teleport(STANDARD_YANILLE)
			.teleport(FAIRY_RING_CIQ)
			.teleport(RING_OF_DUELING_CASTLE_WARS)
			.requirement(new QuestRequirement(WATCHTOWER, true))
			.requirement(new InventoryRequirement(COINS_995, 20))
			.pathObject(new WorldPoint(2504, 3062, 0), CITY_GATE_2788)
			.pathObject(new WorldPoint(2504, 3063, 0), CITY_GATE_2789)
			.pathObject(new WorldPoint(2507, 3012, 0), BATTLEMENT)
			.pathObject(new WorldPoint(2507, 3011, 0), BATTLEMENT)
			.pathObject(new WorldPoint(2530, 3026, 0), GAP)
			.build(),
		CoordinateClue.builder()
			.text("04 degrees 05 minutes south 04 degrees 24 minutes east")
			.clueId(CLUE_SCROLL_HARD_3548)
			.location(new ClueArea(2580, 3029, 2582, 3031, 0))
			.area("Gu'Tanoth island")
			.enemy(SARADOMIN_WIZARD)
			.teleport(GNOME_GLIDER_FELDIP_HILLS)
			.teleport(FAIRY_RING_AKS)
			.teleport(RING_OF_DUELING_CASTLE_WARS)
			.extraMapPoint(new WorldPoint(2499, 2989, 0))
			.pathObject(new WorldPoint(2499, 2989, 0), CAVE_ENTRANCE_2811)
			.build(),
		CoordinateClue.builder()
			.text("04 degrees 16 minutes south 16 degrees 16 minutes east")
			.clueId(CLUE_SCROLL_HARD_3538)
			.location(new ClueArea(2960, 3023, 2962, 3025, 0))
			.area("Karamja Ship Yard")
			.enemy(SARADOMIN_WIZARD)
			.teleport(CHARTER_SHIP_SHIP_YARD)
			.teleport(GNOME_GLIDER_KARAMJA)
			.teleport(FAIRY_RING_DKP)
			.requirement(new QuestRequirement(THE_GRAND_TREE, true))
			.build(),
		CoordinateClue.builder()
			.text("04 degrees 41 minutes north 03 degrees 09 minutes west")
			.clueId(CLUE_SCROLL_HARD_7256)
			.location(new ClueArea(2338, 3310, 2340, 3312, 0))
			.area("Arandar pass")
			.enemy(SARADOMIN_WIZARD)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.teleport(TELEPORT_CRYSTAL_PRIFDDINAS)
			.teleport(TELEPORT_TO_HOUSE_PRIFDDINAS)
			.requirement(new QuestRequirement(REGICIDE, true))
			.build(),
		CoordinateClue.builder()
			.text("05 degrees 37 minutes north 31 degrees 15 minutes east")
			.clueId(CLUE_SCROLL_HARD_3542)
			.location(new ClueArea(3439, 3340, 3441, 3342, 0))
			.area("Nature Spirit's grotto")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_BIP)
			.teleport(FAIRY_RING_BKR)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.pathObject(new WorldPoint(3440, 3329, 0), BRIDGE_3522)
			.pathObject(new WorldPoint(3441, 3329, 0), BRIDGE_3522)
			.build(),
		CoordinateClue.builder()
			.text("05 degrees 50 minutes south 10 degrees 05 minutes east")
			.clueId(CLUE_SCROLL_HARD_3530)
			.location(new ClueArea(2762, 2973, 2764, 2975, 0))
			.area("Cairn Isle, Karamja")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_CKR)
			.teleport(SCROLL_TAI_BWO_WANNAI)
			.requirement(new SkillRequirement(AGILITY, 15))
			.pathObject(new WorldPoint(2794, 2978, 0), ROCKS_2231)
			.pathObject(new WorldPoint(2794, 2979, 0), ROCKS_2231)
			.pathObject(new WorldPoint(2794, 2980, 0), ROCKS_2231)
			.build(),
		CoordinateClue.builder()
			.text("06 degrees 00 minutes south 21 degrees 48 minutes east")
			.clueId(CLUE_SCROLL_HARD_7258)
			.location(new ClueArea(3137, 2968, 3139, 2970, 0))
			.area("Desert, West of Bandit Camp")
			.enemy(SARADOMIN_WIZARD)
			.teleport(CAMULET_ENTRANCE)
			.teleport(PHARAOHS_SCEPTER_JALDRAOCHT)
			.teleport(FAIRY_RING_BIQ)
			.teleport(MAGIC_CARPET_BEDABIN_CAMP)
			.build(),
		CoordinateClue.builder()
			.text("06 degrees 11 minutes south 15 degrees 07 minutes east")
			.clueId(CLUE_SCROLL_HARD_3540)
			.location(new ClueArea(2923, 2962, 2925, 2964, 0))
			.area("Eastern Karamja, south end")
			.enemy(SARADOMIN_WIZARD)
			.teleport(GNOME_GLIDER_KARAMJA)
			.teleport(CHARTER_SHIP_SHIP_YARD)
			.teleport(FAIRY_RING_DKP)
			.build(),
		CoordinateClue.builder()
			.text("07 degrees 43 minutes south 12 degrees 26 minutes east")
			.clueId(CLUE_SCROLL_HARD_3534)
			.location(new ClueArea(2837, 2913, 2839, 2915, 0))
			.area("Kharazi Jungle, water pool")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_CKR)
			.requirement(new QuestRequirement(LEGENDS_QUEST, true))
			.requirement(new KharaziJungleEntranceRequirement())
			.build(),
		CoordinateClue.builder()
			.text("08 degrees 03 minutes north 31 degrees 16 minutes east")
			.clueId(CLUE_SCROLL_HARD_3544)
			.location(new ClueArea(3440, 3418, 3442, 3420, 0))
			.area("Mort Myre Swamp, south of Canifis")
			.enemy(SARADOMIN_WIZARD)
			.teleport(ARCEUUS_SALVE_GRAVEYARD)
			.teleport(FAIRY_RING_BKR)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.build(),
		CoordinateClue.builder()
			.text("08 degrees 05 minutes south 15 degrees 56 minutes east")
			.clueId(CLUE_SCROLL_HARD_3536)
			.location(new ClueArea(2949, 2901, 2951, 2903, 0))
			.area("South-east of Kharazi Jungle")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_CKR)
			.requirement(new QuestRequirement(LEGENDS_QUEST, true))
			.requirement(new KharaziJungleEntranceRequirement())
			.build(),
		CoordinateClue.builder()
			.text("08 degrees 26 minutes south 10 degrees 28 minutes east")
			.clueId(CLUE_SCROLL_HARD_3532)
			.location(new ClueArea(2774, 2890, 2776, 2892, 0))
			.area("South-west of Kharazi Jungle")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_CKR)
			.requirement(new QuestRequirement(LEGENDS_QUEST, true))
			.requirement(new KharaziJungleEntranceRequirement())
			.build(),
		CoordinateClue.builder()
			.text("10 degrees 3 minutes north 32 degrees 13 minutes west")
			.clueId(CLUE_SCROLL_HARD_25790)
			.location(new ClueArea(1408, 3482, 1410, 3484, 0))
			.area("Southern end of Shayziens' Wall")
			.enemy(SARADOMIN_WIZARD)
			.build(),
		// TODO: Ferox Enclave
		CoordinateClue.builder()
			.text("13 degrees 46 minutes north 21 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_HARD_7262)
			.location(new ClueArea(3112, 3601, 3114, 3603, 0))
			.area("Wilderness, north of Edgeville, level 11")
			.enemy(ZAMORAK_WIZARD)
			.teleport(WILDERNESS_OBELISK_13)
			.teleport(ANCIENT_CARRALLANGAR)
			.teleport(BURNING_AMULET_BANDIT_CAMP)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 03 minutes north 14 degrees 07 minutes east")
			.clueId(CLUE_SCROLL_HARD_3526)
			.location(new ClueArea(2891, 3674, 2893, 3676, 0))
			.area("Trollheim summit")
			.enemy(SARADOMIN_WIZARD)
			.teleport(STANDARD_TROLLHEIM)
			.requirement(new QuestRequirement(TROLL_STRONGHOLD, true))
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 07 minutes north 22 degrees 45 minutes east")
			.clueId(CLUE_SCROLL_HARD_2743)
			.location(new ClueArea(3167, 3676, 3169, 3678, 0))
			.area("Wilderness, Graveyard of Shadows, level 20")
			.enemy(ZAMORAK_WIZARD)
			.teleport(ANCIENT_CARRALLANGAR)
			.teleport(GAMES_NECKLACE_CORPOREAL_BEAST)
			.teleport(WILDERNESS_OBELISK_19)
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 31 minutes north 12 degrees 54 minutes east")
			.clueId(CLUE_SCROLL_HARD_3528)
			.location(new ClueArea(2852, 3689, 2854, 3691, 0))
			.area("Troll Stronghold entrance")
			.enemy(SARADOMIN_WIZARD)
			.teleport(STONY_BASALT)
			.teleport(STANDARD_TROLLHEIM)
			.requirement(new QuestRequirement(TROLL_STRONGHOLD, true))
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 35 minutes north 27 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_HARD_7264)
			.location(new ClueArea(3304, 3691, 3306, 3693, 0))
			.area("Wilderness, black salamanders, level 22")
			.enemy(ZAMORAK_WIZARD)
			.teleport(BURNING_AMULET_CHAOS_TEMPLE)
			.teleport(WILDERNESS_CRABS_TELEPORT)
			.teleport(WILDERNESS_OBELISK_19)
			.teleport(GAMES_NECKLACE_CORPOREAL_BEAST)
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 43 minutes north 19 degrees 13 minutes east")
			.clueId(CLUE_SCROLL_HARD_2745)
			.location(new ClueArea(3054, 3695, 3056, 3697, 0))
			.area("Wilderness, Bandit Camp, level 23")
			.enemy(ZAMORAK_WIZARD)
			.teleport(BURNING_AMULET_BANDIT_CAMP)
			.teleport(WILDERNESS_OBELISK_27)
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 43 minutes north 26 degrees 56 minutes east")
			.clueId(CLUE_SCROLL_HARD_12564)
			.location(new ClueArea(3301, 3695, 3303, 3697, 0))
			.area("Wilderness, black salamanders, level 23")
			.enemy(ZAMORAK_WIZARD)
			.teleport(BURNING_AMULET_CHAOS_TEMPLE)
			.teleport(WILDERNESS_CRABS_TELEPORT)
			.teleport(WILDERNESS_OBELISK_19)
			.teleport(GAMES_NECKLACE_CORPOREAL_BEAST)
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 48 minutes north 30 degrees 1 minute west")
			.clueId(CLUE_SCROLL_HARD_19840)
			.location(new ClueArea(1478, 3698, 1480, 3700, 0))
			.area("Lizardman Canyon")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_DJR)
			.teleport(KHAREDSTS_MEMOIRS_HISTORY_AND_HEARSAY)
			.requirement(new FavourRequirement(SHAYZIEN, 5))
			.pathObject(new WorldPoint(1471, 3687, 0), HANDHOLDS)
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 45 minutes north 3 degrees 5 minutes west")
			.clueId(CLUE_SCROLL_HARD_23167)
			.location(new ClueArea(2340, 3696, 2342, 3698, 0))
			.area("North of Piscatoris Fishing Colony")
			.enemy(SARADOMIN_WIZARD)
			.teleport(WESTERN_BANNER_3)
			.teleport(SCROLL_PISCATORIS)
			.teleport(FAIRY_RING_AKQ)
			.requirement(new QuestRequirement(SWAN_SONG))
			.build(),
		CoordinateClue.builder()
			.text("17 degrees 50 minutes north 08 degrees 30 minutes east")
			.clueId(CLUE_SCROLL_HARD_7266)
			.location(new ClueArea(2711, 3731, 2713, 3733, 0))
			.area("North-east of Rellekka")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_DKS)
			.build(),
		CoordinateClue.builder()
			.text("18 degrees 22 minutes north 16 degrees 33 minutes east")
			.clueId(CLUE_SCROLL_HARD_7260)
			.location(new ClueArea(2969, 3748, 2971, 3750, 0))
			.area("Wilderness, Forgotten Cemetery, level 29")
			.enemy(ZAMORAK_WIZARD)
			.teleport(ARCEUUS_CEMETERY)
			.teleport(ANCIENT_DAREEYAK)
			.teleport(WILDERNESS_OBELISK_27)
			.teleport(BURNING_AMULET_BANDIT_CAMP)
			.build(),
		CoordinateClue.builder()
			.text("18 degrees 50 minutes north 20 degrees 26 minutes east")
			.clueId(CLUE_SCROLL_HARD_3556)
			.location(new ClueArea(3093, 3763, 3095, 3765, 0))
			.area("Wilderness, hobgoblin mine, level 31")
			.enemy(ZAMORAK_WIZARD)
			.teleport(HUNTER_CAPE_BLACK_CHINCHOMPAS)
			.teleport(WILDERNESS_OBELISK_35)
			.teleport(SCROLL_REVENANT_CAVE)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.build(),
		CoordinateClue.builder()
			.text("19 degrees 00 minutes north 27 degrees 13 minutes east")
			.clueId(CLUE_SCROLL_HARD_2747)
			.location(new ClueArea(3310, 3768, 3312, 3770, 0))
			.area("Wilderness, north of Venenatis, level 32")
			.enemy(ZAMORAK_WIZARD)
			.teleport(WILDERNESS_CRABS_TELEPORT)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(BURNING_AMULET_CHAOS_TEMPLE)
			.teleport(GAMES_NECKLACE_CORPOREAL_BEAST)
			.teleport(WILDERNESS_OBELISK_19)
			.build(),
		CoordinateClue.builder()
			.text("19 degrees 9 minutes north 21 degrees 58 minutes east")
			.clueId(CLUE_SCROLL_HARD_23168)
			.location(new ClueArea(3142, 3773, 3144, 3775, 0))
			.area("Wilderness, black chinchompas, level 32")
			.enemy(ZAMORAK_WIZARD)
			.teleport(HUNTER_CAPE_BLACK_CHINCHOMPAS)
			.teleport(SCROLL_REVENANT_CAVE)
			.teleport(WILDERNESS_OBELISK_35)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.build(),
		CoordinateClue.builder()
			.text("19 degrees 24 minutes north 30 degrees 37 minutes west")
			.clueId(CLUE_SCROLL_HARD_19842)
			.location(new ClueArea(1459, 3781, 1461, 3783, 0))
			.area("Lovakengj, near burning man.")
			.enemy(SARADOMIN_WIZARD)
			.teleport(XERICS_TALISMAN_XERICS_INFERNO)
			.teleport(KHAREDSTS_MEMOIRS_JEWELRY_OF_JUBILATION)
			.teleport(FAIRY_RING_DJR)
			.build(),
		CoordinateClue.builder()
			.text("19 degrees 43 minutes north 25 degrees 07 minutes east")
			.clueId(CLUE_SCROLL_HARD_2741)
			.location(new ClueArea(3243, 3791, 3245, 3793, 0))
			.area("Wilderness, south-east of Lava Dragon Isle, level 35")
			.enemy(ZAMORAK_WIZARD)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(HUNTER_CAPE_CARNIVOROUS_CHINCHOMPAS)
			.teleport(WILDERNESS_CRABS_TELEPORT)
			.teleport(SCROLL_REVENANT_CAVE)
			.teleport(WILDERNESS_OBELISK_35)
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 05 minutes north 21 degrees 52 minutes east")
			.clueId(CLUE_SCROLL_HARD_2733)
			.location(new ClueArea(3139, 3803, 3141, 3805, 0))
			.area("Wilderness, north of black chinchompas, level 36")
			.enemy(ZAMORAK_WIZARD)
			.teleport(HUNTER_CAPE_BLACK_CHINCHOMPAS)
			.teleport(SCROLL_REVENANT_CAVE)
			.teleport(WILDERNESS_OBELISK_35)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 33 minutes north 15 degrees 48 minutes east")
			.location(new ClueArea(2945, 3818, 2947, 3820, 0))
			.area("Wilderness, Chaos Temple, level 38")
			.enemy(ZAMORAK_WIZARD)
			.teleport(ANCIENT_GHORROCK)
			.teleport(ARCEUUS_CEMETERY)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(WILDERNESS_OBELISK_44)
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 45 minutes north 41 degrees 35 minutes east")
			.clueId(CLUE_SCROLL_HARD_21526)
			.location(new ClueArea(3770, 3824, 3772, 3826, 0))
			.area("Fossil Island, east of camp")
			.enemy(SARADOMIN_WIZARD)
			.teleport(DIGSITE_PENDANT_DIGSITE)
			.teleport(SCROLL_DIGSITE)
			.requirement(new QuestRequirement(BONE_VOYAGE))
			.build(),
		CoordinateClue.builder()
			.text("21 degrees 24 minutes north 17 degrees 54 minutes east")
			.clueId(CLUE_SCROLL_HARD_2737)
			.location(new ClueArea(3012, 3845, 3014, 3847, 0))
			.area("Wilderness, KBD's lair entrance, level 41")
			.enemy(ZAMORAK_WIZARD)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(ANCIENT_GHORROCK)
			.teleport(WILDERNESS_OBELISK_44)
			.pathObject(new WorldPoint(3008, 3850, 0), GATE_1728)
			.pathObject(new WorldPoint(3008, 3849, 0), GATE_1727)
			.build(),
		CoordinateClue.builder()
			.text("22 degrees 35 minutes north 19 degrees 18 minutes east")
			.clueId(CLUE_SCROLL_HARD_2723)
			.location(new ClueArea(3057, 3883, 3059, 3885, 0))
			.area("Wilderness, runite rocks north of Lava Maze, level 46")
			.enemy(ZAMORAK_WIZARD)
			.teleport(ANCIENT_GHORROCK)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(WILDERNESS_OBELISK_44)
			.build(),
		CoordinateClue.builder()
			.text("22 degrees 45 minutes north 26 degrees 33 minutes east")
			.clueId(CLUE_SCROLL_HARD_2731)
			.location(new ClueArea(3289, 3888, 3291, 3890, 0))
			.area("Wilderness, Demonic Ruins, level 47")
			.enemy(ZAMORAK_WIZARD)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(WILDERNESS_SWORD_3)
			.build(),
		CoordinateClue.builder()
			.text("23 degrees 0 minutes north 41 degrees 33 minutes east")
			.clueId(CLUE_SCROLL_HARD_21527)
			.location(new ClueArea(3769, 3896, 3771, 3898, 0))
			.area("Fossil Island, north-east island")
			.enemy(SARADOMIN_WIZARD)
			.teleport(DIGSITE_PENDANT_DIGSITE)
			.teleport(SCROLL_DIGSITE)
			.requirement(new QuestRequirement(BONE_VOYAGE))
			.pathObject(new WorldPoint(3724, 3805, 0), ROWBOAT_30914)
			.pathObject(new WorldPoint(3735, 3894, 0), ROWBOAT_30915)
			.build(),
		CoordinateClue.builder()
			.text("23 degrees 03 minutes north 02 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_HARD_12556)
			.location(new ClueArea(2504, 3898, 2506, 3900, 0))
			.area("Miscellania penguin island")
			.enemy(SARADOMIN_WIZARD)
			.teleport(FAIRY_RING_AJS)
			.requirement(new QuestRequirement(FAIRYTALE_II__CURE_A_QUEEN, true))
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 22 minutes north 17 degrees 15 minutes east")
			.clueId(CLUE_SCROLL_HARD_23169)
			.location(new ClueArea(2991, 3940, 2993, 3942, 0))
			.area("Wilderness, agility course, level 53")
			.enemy(ZAMORAK_WIZARD)
			.teleport(LUNAR_ICE_PLATEAU)
			.teleport(ANCIENT_GHORROCK)
			.teleport(WILDERNESS_OBELISK_44)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(WILDERNESS_LEVER)
			.requirement(new SkillRequirement(AGILITY, 52))
			.pathObject(new WorldPoint(2998, 3917, 0), DOOR_23555)
			.pathObject(new WorldPoint(3001, 3945, 0), LOG_BALANCE_23542)
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 24 minutes north 26 degrees 24 minutes east")
			.clueId(CLUE_SCROLL_HARD_3558)
			.location(new ClueArea(3284, 3941, 3286, 3943, 0))
			.area("Wilderness, Rogues' Castle backyard, level 53")
			.enemy(ZAMORAK_WIZARD)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_LEVER)
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 56 minutes north 22 degrees 28 minutes east")
			.clueId(CLUE_SCROLL_HARD_2727)
			.location(new ClueArea(3158, 3958, 3160, 3960, 0))
			.area("Wilderness, north of lever, level 55")
			.enemy(ZAMORAK_WIZARD)
			.teleport(WILDERNESS_LEVER)
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 58 minutes north 18 degrees 43 minutes east")
			.clueId(CLUE_SCROLL_HARD_2739)
			.location(new ClueArea(3038, 3959, 3040, 3961, 0))
			.area("Wilderness, Pirates' Hideout, level 56")
			.enemy(ZAMORAK_WIZARD)
			.teleport(LUNAR_ICE_PLATEAU)
			.teleport(ANCIENT_GHORROCK)
			.teleport(WILDERNESS_OBELISK_44)
			.teleport(WILDERNESS_LEVER)
			.build(),
		CoordinateClue.builder()
			.text("25 degrees 03 minutes north 17 degrees 05 minutes east")
			.clueId(CLUE_SCROLL_HARD_2725)
			.location(new ClueArea(2986, 3962, 2988, 3964, 0))
			.area("Wilderness, west of agility course, level 56")
			.enemy(ZAMORAK_WIZARD)
			.teleport(LUNAR_ICE_PLATEAU)
			.teleport(ANCIENT_GHORROCK)
			.teleport(WILDERNESS_OBELISK_44)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(WILDERNESS_LEVER)
			.build(),
		CoordinateClue.builder()
			.text("25 degrees 03 minutes north 23 degrees 24 minutes east")
			.clueId(CLUE_SCROLL_HARD_2729)
			.location(new ClueArea(3188, 3962, 3190, 3964, 0))
			.area("Wilderness, magic axe hut, level 56")
			.enemy(ZAMORAK_WIZARD)
			.teleport(WILDERNESS_LEVER)
			.build(),
		// TODO: "Lake Molch dock west of Shayzien Encampment"

		// Elite
		CoordinateClue.builder()
			.text("00 degrees 18 minutes south 02 degrees 35 minutes west")
			.clueId(CLUE_SCROLL_ELITE_12089)
			.location(new ClueArea(2357, 3151,  0))
			.area("Lletya, south-east corner")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(TELEPORT_CRYSTAL_LLETYA)
			.requirement(new QuestRequirement(REGICIDE, true))
			.build(),
		CoordinateClue.builder()
			.text("00 degrees 35 minutes north 35 degrees 50 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12091)
			.location(new ClueArea(3587, 3180, 0))
			.area("Meiyerditch, north of boat")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(BOAT_BURGH_DE_ROTT_TO_MEIYERDITCH)
			.teleport(DRAKANS_MEDALLION_VER_SINHAZA)
			.requirement(new QuestRequirement(DARKNESS_OF_HALLOWVALE, true))
			.pathObject(new WorldPoint(3605, 3163, 1), ROCK_17958)
			.pathObject(new WorldPoint(3604, 3163, 1), ROCK_17959)
			.pathObject(new WorldPoint(3589, 3173, 1), NULL_18122)
			.pathObject(new WorldPoint(3591, 3180, 0), WALL_RUBBLE_18038)
			.build(),
		CoordinateClue.builder()
			.text("02 degrees 35 minutes south 11 degrees 52 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12110)
			.location(new ClueArea(2820, 3078, 0))
			.area("Tai Bwo Wannai, Hardwood Grove")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(SCROLL_TAI_BWO_WANNAI)
			.teleport(FAIRY_RING_CKR)
			.requirement(new QuestRequirement(JUNGLE_POTION))
			// TODO: Prettify
			.requirement(new OrRequirement("100 Trading Sticks",
				new InventoryRequirement(TRADING_STICKS, 100),
				new DiaryRequirement(KARAMJA, ELITE)))
			.pathObject(new WorldPoint(2817, 3083, 0), HARDWOOD_GROVE_DOORS)
			.pathObject(new WorldPoint(2817, 3084, 0), HARDWOOD_GROVE_DOORS_9039)
			.build(),
		CoordinateClue.builder()
			.text("03 degrees 09 minutes south 42 degrees 50 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12086)
			.location(new ClueArea(3811, 3060, 0))
			.area("Mos Le'Harmless hardwood island")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.firePitVarbits(Varbits.FIRE_PIT_MOS_LE_HARMLESS)
			.teleport(SCROLL_MOS_LEHARMLESS)
			.teleport(MINIGAME_TROUBLE_BREWING)
			.teleport(CHARTER_SHIP_MOS_LEHARMLESS)
			.requirement(new QuestRequirement(CABIN_FEVER))
			.extraMapPoint(new WorldPoint(3784, 2973, 0))
			.pathObject(new WorldPoint(3784, 2973, 0), CAVE_ENTRANCE_3650)
			.pathObject(new WorldPoint(3814, 9462, 0), STAIRCASE_5269)
			.build(),
		CoordinateClue.builder()
			.text("03 degrees 46 minutes north 08 degrees 07 minutes west")
			.clueId(CLUE_SCROLL_ELITE_12111)
			.location(new ClueArea(2180, 3282, 0))
			.area("North of Iorwerth Camp")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(SCROLL_IORWERTH_CAMP)
			.teleport(TELEPORT_CRYSTAL_PRIFDDINAS)
			.teleport(TELEPORT_TO_HOUSE_PRIFDDINAS)
			.requirement(new QuestRequirement(REGICIDE, true))
			.build(),
		CoordinateClue.builder()
			.text("05 degrees 07 minutes south 13 degrees 26 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12107)
			.location(new ClueArea(2870, 2997, 0))
			.area("Shilo Village, north-east corner")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(KARAMJA_GLOVES_3_GEM_MINE)
			.teleport(CART_TO_SHILO_VILLAGE)
			.teleport(FAIRY_RING_CKR)
			.requirement(new QuestRequirement(SHILO_VILLAGE))
			.build(),
		CoordinateClue.builder()
			.text("5 degrees 18 minutes north 6 degrees 48 minutes west")
			.clueId(CLUE_SCROLL_ELITE_23770)
			.location(new ClueArea(3246, 6083, 0))
			.area("Prifddinas, west of the Tower of Voices")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(TELEPORT_TO_HOUSE_PRIFDDINAS)
			.teleport(TELEPORT_CRYSTAL_PRIFDDINAS)
			.teleport(CHARTER_SHIP_PRIFDDINAS)
			.requirement(new QuestRequirement(SONG_OF_THE_ELVES))
			.build(),
		CoordinateClue.builder()
			.text("05 degrees 24 minutes south 26 degrees 56 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12100)
			.location(new ClueArea(3302, 2988, 0))
			.area("West of Pollnivneach, on top of a cliff")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(CAMULET_ENTRANCE)
			.teleport(PHARAOHS_SCEPTER_JALDRAOCHT)
			.teleport(TELEPORT_TO_HOUSE_POLLNIVNEACH)
			.build(),
		CoordinateClue.builder()
			.text("05 degrees 39 minutes south 02 degrees 13 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12098)
			.location(new ClueArea(2511, 2980, 0))
			.area("Feldip Hills, west of glider")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(GNOME_GLIDER_FELDIP_HILLS)
			.teleport(SCROLL_FELDIP_HILLS)
			.teleport(FAIRY_RING_AKS)
			.build(),
		CoordinateClue.builder()
			.text("6 degrees 28 minutes south 3 degrees 48 minutes west")
			.location(new ClueArea(2318, 2954, 0))
			.area("Isle of Souls, north-east corner")
			.enemy(BANDOSIAN_GUARD)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(MINIGAME_SOUL_WARS)
			.teleport(RING_OF_DUELING_FEROX_ENCLAVE)
			.build(),
		CoordinateClue.builder()
			.text("06 degrees 35 minutes north 09 degrees 07 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12102)
			.location(new ClueArea(2732, 3372, 0))
			.area("Legends' Guild")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(QUEST_CAPE)
			.teleport(FAIRY_RING_BLR)
			.teleport(STANDARD_ARDOUGNE)
			.requirement(new QuestRequirement(LEGENDS_QUEST, true))
			.pathObject(new WorldPoint(2728, 3349, 0), GATE_2391)
			.pathObject(new WorldPoint(2729, 3349, 0), GATE_2392)
			.build(),
		CoordinateClue.builder()
			.text("08 degrees 15 minutes north 35 degrees 24 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12103)
			.location(new ClueArea(3573, 3425, 0))
			.area("East of the Hollows, north of graveyard")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(BOAT_MORTTON_TO_THE_HOLLOWS)
			.teleport(FAIRY_RING_BKR)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.build(),
		CoordinateClue.builder()
			.text("8 degrees 30 minutes south 10 degrees 48 minutes west")
			.clueId(CLUE_SCROLL_ELITE_25498)
			.location(new ClueArea(2094, 2889, 0))
			.area("Isle of Souls, west side")
			.enemy(ARMADYLEAN_GUARD)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(MINIGAME_SOUL_WARS)
			.teleport(RING_OF_DUELING_FEROX_ENCLAVE)
			.build(),
		CoordinateClue.builder()
			.text("09 degrees 46 minutes south 43 degrees 22 minutes east")
			.location(new ClueArea(3828, 2848, 0))
			.area("East of Harmony Island")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(ARCEUUS_HARMONY_ISLAND)
			.teleport(SCROLL_MOS_LEHARMLESS)
			.teleport(CHARTER_SHIP_MOS_LEHARMLESS)
			.requirement(new QuestRequirement(THE_GREAT_BRAIN_ROBBERY))
			.build(),
		CoordinateClue.builder()
			.text("10 degrees 05 minutes south 24 degrees 31 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12099)
			.location(new ClueArea(3225, 2838, 0))
			.area("North of Menaphos")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(CAMULET_ENTRANCE)
			.teleport(PHARAOHS_SCEPTER_JALDRAOCHT)
			.teleport(TELEPORT_TO_HOUSE_POLLNIVNEACH)
			.build(),
		CoordinateClue.builder()
			.text("10 degrees 52 minutes north 30 degrees 54 minutes west")
			.clueId(CLUE_SCROLL_ELITE_25787)
			.location(new ClueArea(1451, 3509, 0))
			.area("Shayzien, Ruins of Morra")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.build(),
		CoordinateClue.builder()
			.text("10 degrees 54 minutes north 20 degrees 50 minutes west")
			.clueId(CLUE_SCROLL_ELITE_19813)
			.location(new ClueArea(1773, 3510, 0))
			.area("Hosidius, north of the mine")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.teleport(XERICS_TALISMAN_XERICS_GLADE)
			.teleport(MINIGAME_TITHE_FARM)
			.teleport(SKILLS_NECKLACE_WOODCUTTING_GUILD)
			.build(),
		CoordinateClue.builder()
			.text("12 degrees 31 minutes north 43 degrees 11 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12085)
			.location(new ClueArea(3822, 3562, 0))
			.area("North-east of Dragontooth Island")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(CHARTER_SHIP_PORT_PHASMATYS)
			.teleport(ECTOPHIAL)
			.requirement(new QuestRequirement(GHOSTS_AHOY))
			.requirement(CAN_USE_GHOSTSPEAK_AMULET.getRequirement())
			// TODO: Check for free transport
			.requirement(new OrRequirement("25 Ecto-tokens",
				new InventoryRequirement(ECTOTOKEN, 25),
				new AndRequirement(
					new InventoryRequirement(ECTOTOKEN, 10),
					new EquipmentRequirement(RING_OF_CHAROSA))))
			.build(),
		CoordinateClue.builder()
			.text("12 degrees 35 minutes north 36 degrees 20 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12108)
			.location(new ClueArea(3603, 3564, 0))
			.area("North of Morytania herb patch")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(ARCEUUS_FENKENSTRAINS_CASTLE)
			.teleport(ECTOPHIAL)
			.teleport(FAIRY_RING_ALQ)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.requirement(new SkillRequirement(AGILITY, 25))
			.pathObject(new WorldPoint(3609, 3543, 0), SHIPS_LADDER_16111)
			.pathObject(new WorldPoint(3605, 3546, 1), GANGPLANK_16651)
			.pathObject(new WorldPoint(3604, 3550, 0), ROCK_16115)
			.pathObject(new WorldPoint(3599, 3552, 0), ROCK_16115)
			.pathObject(new WorldPoint(3595, 3554, 0), ROCK_16115)
			.pathObject(new WorldPoint(3597, 3559, 0), ROCK_16115)
			.pathObject(new WorldPoint(3599, 3564, 0), ROCK_16115)
			.build(),
		CoordinateClue.builder()
			.text("13 degrees 45 minutes south 15 degrees 30 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12106)
			.location(new ClueArea(2936, 2721, 0))
			.area("Crash Island, east shore")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(ROYAL_SEED_POD)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(ARCEUUS_APE_ATOLL)
			.requirement(new QuestRequirement(MONKEY_MADNESS_I, true))
			.extraMapPoint(new WorldPoint(2482, 3486, 1))
			.extraMapPoint(new WorldPoint(2802, 2706, 0))
			.build(),
		// TODO Requirements
		CoordinateClue.builder()
			.text("14 degrees 13 minutes south 27 degrees 26 minutes east")
			.location(new ClueArea(3318, 2706, 0))
			.area("Necropolis mine")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.build(),
		CoordinateClue.builder()
			.text("14 degrees 15 minutes south 08 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12096)
			.location(new ClueArea(2697, 2705, 0))
			.area("South-west of Ape Atoll")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(ARCEUUS_APE_ATOLL)
			.teleport(GNOME_GLIDER_APE_ATOLL)
			.teleport(FAIRY_RING_CLR)
			.teleport(STANDARD_APE_ATOLL)
			.requirement(new QuestRequirement(MONKEY_MADNESS_I, true))
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 9 minutes north 10 degrees 33 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12104)
			.location(new ClueArea(2778, 3678, 0))
			.area("Mountain Camp")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(FAIRY_RING_AJR)
			.teleport(SLAYER_RING_FREMENNIK_SLAYER_DUNGEON)
			.teleport(TELEPORT_TO_HOUSE_RELLEKKA)
			.requirement(new MountainCampRequirement())
			.build(),
		CoordinateClue.builder()
			.text("17 degrees 58 minutes north 19 degrees 5 minutes east")
			.clueId(CLUE_SCROLL_ELITE_23146)
			.location(new ClueArea(3051, 3736, 0))
			.area("Wilderness, east of level 27 obelisk, level 28")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(WILDERNESS_OBELISK_27)
			.teleport(ARCEUUS_CEMETERY)
			.teleport(ANCIENT_DAREEYAK)
			.teleport(BURNING_AMULET_BANDIT_CAMP)
			.build(),
		CoordinateClue.builder()
			.text("18 degrees 05 minutes north 12 degrees 05 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12090)
			.location(new ClueArea(2827, 3740, 0))
			.area("North-west of Trollheim, next to troll child")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(STANDARD_TROLLHEIM)
			.teleport(STONY_BASALT)
			.requirement(new QuestRequirement(TROLL_STRONGHOLD, true))
			.build(),
		CoordinateClue.builder()
			.text("19 degrees 56 minutes north 02 degrees 31 minutes west")
			.clueId(CLUE_SCROLL_ELITE_12094)
			.location(new ClueArea(2359, 3799, 0))
			.area("South-east of Neitiznot")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(ENCHANTED_LYRE_NEITIZNOT)
			.teleport(BOAT_RELLEKKA_TO_NEITIZNOT)
			.requirement(new QuestRequirement(THE_FREMENNIK_ISLES, true))
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 11 minutes north 07 degrees 41 minutes west")
			.clueId(CLUE_SCROLL_ELITE_12105)
			.location(new ClueArea(2194, 3807, 0))
			.area("Pirates' Cove")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(FREMENNIK_SEA_BOOTS)
			.teleport(LUNAR_MOONCLAN)
			.teleport(SCROLL_LUNAR_ISLE)
			.requirement(new QuestRequirement(LUNAR_DIPLOMACY, true))
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 13 minutes north 08 degrees 07 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12087)
			.location(new ClueArea(2700, 3808, 0))
			.area("North-west of Rellekka Hunter area")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(FAIRY_RING_DKS)
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 24 minutes north 3 degrees 52 minutes west")
			.clueId(CLUE_SCROLL_ELITE_23148)
			.location(new ClueArea(2316, 3814, 0))
			.area("West of Neitiznot")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(ENCHANTED_LYRE_NEITIZNOT)
			.teleport(BOAT_RELLEKKA_TO_NEITIZNOT)
			.requirement(new QuestRequirement(THE_FREMENNIK_ISLES, true))
			.build(),
		CoordinateClue.builder()
			.text("21 degrees 03 minutes north 24 degrees 13 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12109)
			.location(new ClueArea(3215, 3835, 0))
			.area("Wilderness, Lava Dragon Isle, level 40")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(SCROLL_REVENANT_CAVE)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_OBELISK_35)
			.build(),
		CoordinateClue.builder()
			.text("22 degrees 54 minutes north 29 degrees 01 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12101)
			.location(new ClueArea(3369, 3894,  0))
			.area("Wilderness, Fountain of Rune, level 47")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(WILDERNESS_SWORD_3)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(WILDERNESS_CRABS_TELEPORT)
			.build(),
		CoordinateClue.builder()
			.text("23 degrees 48 minutes north 11 degrees 43 minutes west")
			.location(new ClueArea(2065, 3923, 0))
			.area("Lunar Isle, outside western wall")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(LUNAR_MOONCLAN)
			.teleport(SCROLL_LUNAR_ISLE)
			.requirement(new QuestRequirement(LUNAR_DIPLOMACY, true))
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 07 minutes north 23 degrees 22 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12095)
			.location(new ClueArea(3188, 3933, 0))
			.area("Wilderness, Resource Area, level 52")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(WILDERNESS_LEVER)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_OBELISK_50)
			.requirement(new ResourceAreaEntranceRequirement())
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 15 minutes north 13 degrees 30 minutes east")
			.clueId(CLUE_SCROLL_ELITE_23147)
			.location(new ClueArea(2872, 3937, 0))
			.area("Center of Weiss")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(ICY_BASALT)
			.teleport(BOAT_NORTH_EAST_OF_RELLEKKA_TO_WEISS)
			.requirement(new QuestRequirement(MAKING_FRIENDS_WITH_MY_ARM))
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 45 minutes north 17 degrees 24 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12097)
			.location(new ClueArea(2997, 3953, 0))
			.area("Wilderness, agility course, level 55")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(LUNAR_ICE_PLATEAU)
			.teleport(ANCIENT_GHORROCK)
			.teleport(WILDERNESS_OBELISK_44)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(WILDERNESS_LEVER)
			.requirement(new SkillRequirement(AGILITY, 52))
			.pathObject(new WorldPoint(2998, 3917, 0), DOOR_23555)
			.build(),
		CoordinateClue.builder()
			.text("25 degrees 03 minutes north 29 degrees 22 minutes east")
			.clueId(CLUE_SCROLL_ELITE_12093)
			.location(new ClueArea(3380, 3963, 0))
			.area("Wilderness, north-east of volcano, level 56")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_SWORD_3)
			.build(),
		CoordinateClue.builder()
			.text("25 degrees 48 minutes north 35 degrees 0 minutes east")
			.clueId(CLUE_SCROLL_ELITE_22000)
			.location(new ClueArea(3560, 3987, 0))
			.area("Lithkren")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(DIGSITE_PENDANT_LITHKREN)
			.teleport(BOAT_MUSHROOM_FOREST_TO_LITHKREN)
			.requirement(new QuestRequirement(DRAGON_SLAYER_II, true))
			.pathObject(new WorldPoint(3547, 10445, 0), STAIRCASE_32112)
			.pathObject(new WorldPoint(3554, 3998, 0), LADDER_32083)
			.pathObject(new WorldPoint(3558, 4004, 1), STAIRS_32082)
			.pathObject(new WorldPoint(3658, 3849, 1), NULL_29916)
			.build(),
		CoordinateClue.builder()
			.text("26 degrees 43 minutes north 1 degree 22 minutes east")
			.clueId(CLUE_SCROLL_ELITE_24253)
			.location(new ClueArea(2484, 4016, 0))
			.area("North-east of the Island of Stone")
			.enemy(ARMADYLEAN_OR_BANDOSIAN_GUARD)
			.teleport(BOAT_RELLEKKA_TO_ISLAND_OF_STONE)
			.requirement(new QuestRequirement(THE_FREMENNIK_EXILES, true))
			.build(),

		// Master
		CoordinateClue.builder()
			.text("1 degree 30 minutes north 8 degrees 11 minutes west")
			.location(new ClueArea(2177, 3208, 2179, 3210, 0))
			.area("South of Iorwerth Camp")
			.enemy(BRASSICAN_MAGE)
			.teleport(SCROLL_IORWERTH_CAMP)
			.teleport(TELEPORT_CRYSTAL_PRIFDDINAS)
			.teleport(TELEPORT_TO_HOUSE_PRIFDDINAS)
			.teleport(FAIRY_RING_BJS)
			.teleport(CHARTER_SHIP_PORT_TYRAS)
			.requirement(new QuestRequirement(REGICIDE, true))
			.pathObject(new WorldPoint(2181, 3210, 0), STICKS)
			.build(),
		CoordinateClue.builder()
			.text("1 degree 54 minutes south 8 degrees 54 minutes west")
			.location(new ClueArea(2154, 3099, 2156, 3101, 0))
			.area("South of Port Tyras")
			.enemy(BRASSICAN_MAGE)
			.teleport(FAIRY_RING_BJS)
			.teleport(SCROLL_ZUL_ANDRA)
			.teleport(CHARTER_SHIP_PORT_TYRAS)
			.requirement(new QuestRequirement(REGICIDE, true))
			.build(),
		CoordinateClue.builder()
			.text("2 degrees 9 minutes south 6 degrees 58 minutes west")
			.location(new ClueArea(2216, 3091, 2218, 3093, 0))
			.area("Island in the Poison Waste")
			.enemy(BRASSICAN_MAGE)
			.teleport(FAIRY_RING_DLR)
			.requirement(new QuestRequirement(FAIRYTALE_II__CURE_A_QUEEN, true))
			.build(),
		CoordinateClue.builder()
			.text("3 degrees 9 minutes south 43 degrees 26 minutes east")
			.location(new ClueArea(3829, 3059, 3831, 3061, 0))
			.area("Mos Le'Harmless hardwood island")
			.enemy(BRASSICAN_MAGE)
			.firePitVarbits(Varbits.FIRE_PIT_MOS_LE_HARMLESS)
			.teleport(SCROLL_MOS_LEHARMLESS)
			.teleport(MINIGAME_TROUBLE_BREWING)
			.teleport(CHARTER_SHIP_MOS_LEHARMLESS)
			.requirement(new QuestRequirement(CABIN_FEVER))
			.extraMapPoint(new WorldPoint(3784, 2973, 0))
			.pathObject(new WorldPoint(3784, 2973, 0), CAVE_ENTRANCE_3650)
			.pathObject(new WorldPoint(3829, 9462, 0), STAIRCASE_5269)
			.build(),
		CoordinateClue.builder()
			.text("3 degrees 26 minutes north 12 degrees 18 minutes east")
			.location(new ClueArea(2833, 3270, 2835, 3272, 0))
			.area("Center of Crandor island")
			.enemy(BRASSICAN_MAGE)
			.teleport(AMULET_OF_GLORY_KARAMJA)
			.teleport(SPIRIT_TREE_BRIMHAVEN)
			.teleport(TELEPORT_TO_HOUSE_BRIMHAVEN)
			.teleport(CHARTER_SHIP_MUSA_POINT)
			.requirement(new QuestRequirement(Quest.DRAGON_SLAYER_I, true))
			.extraMapPoint(new WorldPoint(2856, 3168, 0))
			.pathObject(new WorldPoint(2856, 3168, 0), ROCKS_11441)
			.pathObject(new WorldPoint(2836, 9600, 0), WALL_2606)
			.pathObject(new WorldPoint(2833, 9657, 0), CLIMBING_ROPE_25213)
			.build(),
		CoordinateClue.builder()
			.text("3 degrees 50 minutes north 9 degrees 7 minutes east")
			.location(new ClueArea(2731, 3283, 2733, 3285, 0))
			.area("Witchaven")
			.enemy(BRASSICAN_MAGE)
			.teleport(QUEST_CAPE)
			.teleport(STANDARD_ARDOUGNE)
			.teleport(FAIRY_RING_BLR)
			.build(),
		CoordinateClue.builder()
			.text("4 degrees 58 minutes north 36 degrees 56 minutes east")
			.location(new ClueArea(3621, 3319, 3623, 3321, 0))
			.area("Meiyerditch, next to Darkmeyer entrance")
			.enemy(BRASSICAN_MAGE)
			.teleport(DRAKANS_MEDALLION_DARKMEYER)
			.teleport(DRAKANS_MEDALLION_VER_SINHAZA)
			.teleport(BOAT_BURGH_DE_ROTT_TO_MEIYERDITCH)
			.requirement(new QuestRequirement(DARKNESS_OF_HALLOWVALE, true))
			.build(),
		CoordinateClue.builder()
			.text("5 degrees 13 minutes north 4 degrees 16 minutes west")
			.location(new ClueArea(2302, 3327, 2304, 3329, 0))
			.area("Outside Prifddinas east gate")
			.enemy(BRASSICAN_MAGE)
			.teleport(TELEPORT_CRYSTAL_PRIFDDINAS)
			.teleport(TELEPORT_TO_HOUSE_PRIFDDINAS)
			.teleport(NECKLACE_OF_PASSAGE_OUTPOST)
			.requirement(new QuestRequirement(REGICIDE, true))
			.build(),
		CoordinateClue.builder()
			.text("7 degrees 37 minutes north 35 degrees 18 minutes east")
			.location(new ClueArea(3569, 3404, 3571, 3406, 0))
			.area("East of the Hollows, north of graveyard")
			.enemy(BRASSICAN_MAGE)
			.teleport(BOAT_MORTTON_TO_THE_HOLLOWS)
			.teleport(FAIRY_RING_BKR)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.build(),
		// TODO: Fare to island
		CoordinateClue.builder()
			.text("8 degrees 1 minute north 20 degrees 58 minutes west")
			.location(new ClueArea(1768, 3417, 1770, 3419, 0))
			.area("Crabclaw Isle")
			.enemy(ANCIENT_WIZARDS)
			.build(),
		// TODO: Prettify
		CoordinateClue.builder()
			.text("8 degrees 11 minutes north 12 degrees 30 minutes east")
			.location(new ClueArea(2839, 3422, 2841, 3424, 0))
			.area("Obelisk of Water")
			.enemy(BRASSICAN_MAGE)
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(HOT_AIR_BALLOON_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.requirement(new OrRequirement("Dusty Key",
				new SkillRequirement(AGILITY, 70),
				new InventoryRequirement(DUSTY_KEY)))
			.extraMapPoint(new WorldPoint(2884, 3397, 0))
			.pathObject(new WorldPoint(2884, 3397, 0), LADDER_16680)
			.build(),
		CoordinateClue.builder()
			.text("12 degrees 35 minutes north 36 degrees 22 minutes east")
			.location(new ClueArea(3603, 3563, 3605, 3565, 0))
			.area("North of Morytania herb patch")
			.enemy(BRASSICAN_MAGE)
			.teleport(ARCEUUS_FENKENSTRAINS_CASTLE)
			.teleport(ECTOPHIAL)
			.teleport(FAIRY_RING_ALQ)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.requirement(new SkillRequirement(AGILITY, 25))
			.pathObject(new WorldPoint(3609, 3543, 0), SHIPS_LADDER_16111)
			.pathObject(new WorldPoint(3605, 3546, 1), GANGPLANK_16651)
			.pathObject(new WorldPoint(3604, 3550, 0), ROCK_16115)
			.pathObject(new WorldPoint(3599, 3552, 0), ROCK_16115)
			.pathObject(new WorldPoint(3595, 3554, 0), ROCK_16115)
			.pathObject(new WorldPoint(3597, 3559, 0), ROCK_16115)
			.pathObject(new WorldPoint(3599, 3564, 0), ROCK_16115)
			.build(),
		CoordinateClue.builder()
			.text("12 degrees 45 minutes north 20 degrees 9 minutes east")
			.location(new ClueArea(3084, 3568, 3086, 3570, 0))
			.area("Wilderness, Obelisk of Air, level 7")
			.enemy(BRASSICAN_MAGE)
			.teleport(ANCIENT_PADDEWWA)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(FAIRY_RING_DKR)
			.extraMapPoint(new WorldPoint(3097, 3468, 0))
			.pathObject(new WorldPoint(3097, 3468, 0), TRAPDOOR_1581)
			.pathObject(new WorldPoint(3097, 3468, 0), TRAPDOOR_1579)
			.build(),
		CoordinateClue.builder()
			.text("13 degrees 33 minutes south 15 degrees 26 minutes east")
			.location(new ClueArea(2933, 2726, 2935, 2728, 0))
			.area("Crash Island, east shore")
			.enemy(BRASSICAN_MAGE)
			.teleport(ROYAL_SEED_POD)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(ARCEUUS_APE_ATOLL)
			.requirement(new QuestRequirement(MONKEY_MADNESS_I, true))
			.extraMapPoint(new WorldPoint(2482, 3486, 1))
			.extraMapPoint(new WorldPoint(2802, 2706, 0))
			.build(),
		CoordinateClue.builder()
			.text("16 degrees 41 minutes north 30 degrees 54 minutes west")
			.location(new ClueArea(1450, 3694, 1452, 3696, 0))
			.area("Lizardman Canyon")
			.enemy(ANCIENT_WIZARDS)
			.teleport(FAIRY_RING_DJR)
			.teleport(KHAREDSTS_MEMOIRS_HISTORY_AND_HEARSAY)
			.requirement(new FavourRequirement(SHAYZIEN, 100))
			.pathObject(new WorldPoint(1459, 3690, 0), HANDHOLDS)
			.build(),
		CoordinateClue.builder()
			.text("18 degrees 3 minutes north 3 degrees 3 minutes east")
			.location(new ClueArea(2537, 3738, 2539, 3740, 0))
			.area("Waterbirth Island, next to Askeladden")
			.enemy(BRASSICAN_MAGE)
			.teleport(LUNAR_WATERBIRTH)
			.teleport(ENCHANTED_LYRE_WATERBIRTH)
			.teleport(BOAT_RELLEKKA_TO_WATERBIRTH_ISLAND)
			.requirement(new WaterbirthIslandAccessRequirement())
			.requirement(new RecommendedRequirement(new InventoryRequirement(PET_ROCK)))
			.requirement(new RecommendedRequirement(new InventoryRequirement(RUNE_THROWNAXE)))
			.extraMapPoint(new WorldPoint(2520, 3739, 0))
			.pathObject(new WorldPoint(2520, 3739, 0), CAVE_ENTRANCE_8929)
			.build(),
		// TODO: Spirit Tree
		CoordinateClue.builder()
			.text("18 degrees 26 minutes north 37 degrees 15 minutes west")
			.location(new ClueArea(1247, 3750, 1249, 3752, 0))
			.area("Farming Guild, north wing")
			.enemy(BRASSICAN_MAGE)
			.teleport(SKILLS_NECKLACE_FARMING_GUILD)
			.teleport(FARMING_CAPE)
			.teleport(FAIRY_RING_CIR)
			.requirement(new SkillRequirement(FARMING, 85))
			.requirement(new FavourRequirement(HOSIDIUS, 60))
			.pathObject(new WorldPoint(1248, 3723, 0), DOOR_34463)
			.pathObject(new WorldPoint(1249, 3723, 0), DOOR_34464)
			.build(),
		CoordinateClue.builder()
			.text("19 degrees 43 minutes north 23 degrees 11 minutes west")
			.location(new ClueArea(1697, 3791, 1699, 3793, 0))
			.area("Arceuus church")
			.enemy(ANCIENT_WIZARDS)
			.teleport(KHAREDSTS_MEMOIRS_A_DARK_DISPOSITION)
			.teleport(FAIRY_RING_CIS)
			.pathObject(new WorldPoint(1678, 3785, 0), DOOR_28461)
			.pathObject(new WorldPoint(1678, 3784, 0), DOOR_28459)
			.pathObject(new WorldPoint(1680, 3785, 0), STAIRS_27853)
			.pathObject(new WorldPoint(1680, 3783, 0), STAIRS_27854)
			.pathObject(new WorldPoint(1690, 3793, 1), STAIRS_27852)
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 35 minutes north 15 degrees 58 minutes east")
			.location(new ClueArea(2950, 3819, 2952, 3821, 0))
			.area("Wilderness, Chaos Temple, level 38")
			.enemy(ANCIENT_WIZARDS)
			.teleport(ANCIENT_GHORROCK)
			.teleport(ARCEUUS_CEMETERY)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(WILDERNESS_OBELISK_44)
			.build(),
		CoordinateClue.builder()
			.text("20 degrees 45 minutes north 7 degrees 26 minutes west")
			.location(new ClueArea(2201, 3824, 2203, 3826, 0))
			.area("Pirates' Cove")
			.enemy(ANCIENT_WIZARDS)
			.teleport(FREMENNIK_SEA_BOOTS)
			.teleport(LUNAR_MOONCLAN)
			.teleport(SCROLL_LUNAR_ISLE)
			.requirement(new QuestRequirement(LUNAR_DIPLOMACY, true))
			.build(),
		CoordinateClue.builder()
			.text("21 degrees 37 minutes north 21 degrees 13 minutes west")
			.location(new ClueArea(1760, 3852, 1762, 3854, 0))
			.area("Arceuus essence mine")
			.enemy(BRASSICAN_MAGE)
			.teleport(ARCEUUS_HOME)
			.teleport(FAIRY_RING_CIS)
			.build(),
		CoordinateClue.builder()
			.text("21 degrees 56 minutes north 10 degrees 56 minutes west")
			.location(new ClueArea(2089, 3862, 2091, 3864, 0))
			.area("Lunar Isle, west of Astral altar")
			.enemy(ANCIENT_WIZARDS)
			.teleport(LUNAR_MOONCLAN)
			.teleport(SCROLL_LUNAR_ISLE)
			.requirement(new QuestRequirement(LUNAR_DIPLOMACY, true))
			.build(),
		CoordinateClue.builder()
			.text("22 degrees 24 minutes north 31 degrees 11 minutes west")
			.location(new ClueArea(1441, 3877, 1443, 3879, 0))
			.area("Lovakengj sulphur mine")
			.enemy(BRASSICAN_MAGE)
			.teleport(XERICS_TALISMAN_XERICS_INFERNO)
			.teleport(KHAREDSTS_MEMOIRS_JEWELRY_OF_JUBILATION)
			.teleport(FAIRY_RING_DJR)
			.requirement(new RecommendedRequirement(HAS_FACEMASK.getRequirement()))
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 0 minutes north 29 degrees 22 minutes east")
			.location(new ClueArea(3379, 3928, 3381, 3930, 0))
			.area("Wilderness, volcano, level 51")
			.enemy(ANCIENT_WIZARDS)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_SWORD_3)
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 18 minutes north 23 degrees 22 minutes east")
			.location(new ClueArea(3187, 3938, 3189, 3940, 0))
			.area("Wilderness, Resource Area, level 52")
			.enemy(BRASSICAN_MAGE)
			.teleport(WILDERNESS_LEVER)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_OBELISK_50)
			.requirement(new ResourceAreaEntranceRequirement())
			.build(),
		CoordinateClue.builder()
			.text("24 degrees 22 minutes north 27 degrees 0 minutes east")
			.location(new ClueArea(3303, 3940, 3305, 3942, 0))
			.area("Wilderness, east of Rogues' Castle, level 53")
			.enemy(ANCIENT_WIZARDS)
			.teleport(WILDERNESS_OBELISK_50)
			.teleport(ANCIENT_ANNAKARL)
			.teleport(WILDERNESS_LEVER)
			.build(),
		CoordinateClue.builder()
			.text("25 degrees 0 minutes north 17 degrees 18 minutes east")
			.location(new ClueArea(2993, 3960, 2995, 3962, 0))
			.area("Wilderness, agility course, level 55")
			.enemy(BRASSICAN_MAGE)
			.teleport(LUNAR_ICE_PLATEAU)
			.teleport(ANCIENT_GHORROCK)
			.teleport(WILDERNESS_OBELISK_44)
			.teleport(BURNING_AMULET_LAVA_MAZE)
			.teleport(WILDERNESS_LEVER)
			.requirement(new SkillRequirement(AGILITY, 52))
			.pathObject(new WorldPoint(2998, 3917, 0), DOOR_23555)
			.build());
	// TODO: "Crabclaw Isle"

	private final String type = "Coordinate Clue";

	/**
	 * Example input: "00 degrees 00 minutes north 07 degrees 13 minutes west"
	 * Note: some clues use "1 degree" instead of "01 degrees"
	 */
	@Nullable
	public static CoordinateClue forText(String text)
	{
		for (CoordinateClue clue : CLUES)
		{
			if (text.equalsIgnoreCase(clue.getText()))
			{
				return clue;
			}
		}

		return null;
	}

	private static final class CoordinateClueBuilderImpl extends CoordinateClueBuilder<CoordinateClue, CoordinateClueBuilderImpl>
	{
		public CoordinateClue build()
		{
			// Spade is required for all the coordinate clue steps.
			requirement(new InventoryRequirement(SPADE));
			return new CoordinateClue(this);
		}
	}
}
