/*
 * Copyright (c) 2018, Lotto <https://github.com/devLotto>
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package emerald000.cluehelper.clues;

import com.google.common.collect.ImmutableList;
import java.util.List;
import javax.annotation.Nullable;
import lombok.Getter;
import lombok.experimental.SuperBuilder;
import static net.runelite.api.ItemID.*;
import static net.runelite.api.NullObjectID.NULL_1293;
import static net.runelite.api.ObjectID.*;
import static net.runelite.api.ObjectID.COFFIN;
import static net.runelite.api.Quest.PRIEST_IN_PERIL;
import net.runelite.api.coords.WorldPoint;
import emerald000.cluehelper.clues.requirement.QuestRequirement;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.*;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.CHRONICLE;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.EXPLORERS_RING_2;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.ROYAL_SEED_POD;
import static emerald000.cluehelper.clues.teleport.CommonTeleport.SKULL_SCEPTRE;

@Getter
@SuperBuilder
public class CrypticClue extends ClueScroll
{
	public static final List<CrypticClue> CLUES = ImmutableList.of(
		// Beginner
		CrypticClue.builder()
			.text("Always walking around the castle grounds and somehow knows everyone's age.")
			.npc("Hans")
			.location(new ClueArea(3221, 3218, 0))
			.area("Lumbridge Castle courtyard")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		CrypticClue.builder()
			.text("In a village of barbarians, I am the one who guards the village from up high.")
			.npc("Hunding")
			.location(new ClueArea(3097, 3432, 2))
			.area("Barbarian Village, east tower, 2nd floor")
			.teleport(SKULL_SCEPTRE)
			.teleport(SKILLS_NECKLACE_COOKS_GUILD)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3098, 3426, 0), DOOR_11616)
			.pathObject(new WorldPoint(3096, 3433, 0), LADDER_17026)
			.pathObject(new WorldPoint(3097, 3433, 1), LADDER_17026)
			.pathObject(new WorldPoint(3096, 3429, 2), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("In the place Duke Horacio calls home, talk to a man with a hat dropped by goblins.")
			.npc("Cook")
			.location(new ClueArea(3208, 3213, 0))
			.area("Lumbridge Castle kitchen")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		CrypticClue.builder()
			.text("Near the open desert I reside, to get past me you must abide. Go forward if you dare, for when you pass me, you'll be sweating by your hair.")
			.npc("Shantay")
			.location(new ClueArea(3303, 3123, 0))
			.area("Shantay Pass")
			.teleport(DIARY_CAPE_JARR)
			.teleport(DESERT_AMULET_4_KALPHITE_CAVE)
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(FAIRY_RING_BIQ)
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.build(),
		CrypticClue.builder()
			.text("Talk to Charlie the Tramp in Varrock.")
			.npc("Charlie the Tramp")
			.location(new ClueArea(3209, 3390, 0))
			.area("Varrock south entrance")
			.teleport(COMBAT_BRACELET_CHAMPIONS_GUILD)
			.teleport(CHRONICLE)
			.teleport(STANDARD_VARROCK)
			.build(),

		// Easy
		CrypticClue.builder()
			.text("A crate found in the tower of a church is your next location.")
			.objectId(CRATE_357)
			.location(new ClueArea(2612, 3304, 1))
			.area("East Ardougne church, 1st floor")
			.teleport(STANDARD_ARDOUGNE)
			.teleport(SPIRIT_TREE_KHAZARD_BATTLEFIELD)
			.teleport(FAIRY_RING_DJP)
			.pathObject(new WorldPoint(2612, 3309, 0), DOOR_1540)
			.pathObject(new WorldPoint(2610, 3307, 0), DOOR_1535)
			.pathObject(new WorldPoint(2610, 3306, 0), LADDER_16683)
			.build(),
		CrypticClue.builder()
			.text("Belladonna, my dear. If only I had gloves, then I could hold you at last.")
			.clueId(CLUE_SCROLL_EASY_19823)
			.npc("Tool Leprechaun")
			.location(new ClueArea(3088, 3357, 0))
			.area("Draynor Manor, belladonna patch")
			.teleport(ARCEUUS_DRAYNOR_MANOR)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.build(),
		CrypticClue.builder()
			.text("Dig between some ominous stones in Falador.")
			.clueId(CLUE_SCROLL_EASY_12170)
			.location(new ClueArea(3039, 3398, 3041, 3400, 0))
			.area("North of Falador, next to standing stones")
			.teleport(SKULL_SCEPTRE)
			.teleport(STANDARD_FALADOR)
			.build(),
		// TODO
		CrypticClue.builder()
			.text("Dig by the Giant's Den entrance, looking out over Lake Molch.")
			.clueId(CLUE_SCROLL_EASY_25788)
			// TODO: Full Area
			.location(new ClueArea(1418, 3591, 0))
			.area("Shayzien, entrance to Giant's Den")
			.teleport(KHAREDSTS_MEMOIRS_HISTORY_AND_HEARSAY)
			.teleport(FAIRY_RING_DJR)
			.teleport(XERICS_TALISMAN_XERICS_LOOKOUT)
			.build(),
		CrypticClue.builder()
			.text("Dig in the centre of a great kingdom of 5 cities.")
			.clueId(CLUE_SCROLL_EASY_19826)
			.location(new ClueArea(1630, 3665, 1643, 3681, 0))
			.area("Kourend Castle courtyard")
			.teleport(STANDARD_KOUREND)
			.teleport(XERICS_TALISMAN_XERICS_HEART)
			.build(),
		CrypticClue.builder()
			.text("Dig near some giant mushrooms, behind the Grand Tree.")
			.clueId(CLUE_SCROLL_EASY_3510)
			.location(new ClueArea(2458, 3504, 2460, 3506, 0))
			.area("Northwest of the Grand Tree")
			.teleport(ROYAL_SEED_POD)
			.teleport(SPIRIT_TREE_GNOME_STRONGHOLD)
			.teleport(SLAYER_RING_STRONGHOLD_SLAYER_CAVE)
			.build(),
		CrypticClue.builder()
			.text("Dig under Ithoi's cabin.")
			.clueId(CLUE_SCROLL_EASY_22001)
			.location(new ClueArea(2528, 2836, 2531, 2840, 0))
			.area("Corsair Cove, under Ithoi's cabin")
			.teleport(SPIRIT_TREE_FELDIP_HILLS)
			.teleport(BOAT_RIMMINGTON_TO_CORSAIR_COVE)
			.build(),
		CrypticClue.builder()
			.text("Dig where only the skilled, the wealthy, or the brave can choose not to visit again.")
			.clueId(CLUE_SCROLL_EASY_19814)
			.location(new ClueArea(3218, 3212, 3225, 3223, 0))
			.area("Lumbridge castle courtyard")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		CrypticClue.builder()
			.text("I wonder how many bronze swords he has handed out.")
			.clueId(CLUE_SCROLL_EASY_19816)
			.npc("Vannaka")
			.location(new ClueArea(3164, 9913, 0))
			.area("Edgeville Dungeon")
			.teleport(ANCIENT_PADDEWWA)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(FAIRY_RING_DKR)
			.extraMapPoint(new WorldPoint(3097, 3468, 0))
			.pathObject(new WorldPoint(3097, 3468, 0), TRAPDOOR_1581)
			.pathObject(new WorldPoint(3097, 3468, 0), TRAPDOOR_1579)
			.build(),
		CrypticClue.builder()
			.text("I would make a chemistry joke, but I'm afraid I wouldn't get a reaction.")
			.clueId(CLUE_SCROLL_EASY_19822)
			.npc("Chemist")
			.location(new ClueArea(2932, 3212, 0))
			.area("Rimmington")
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(SKILLS_NECKLACE_CRAFTING_GUILD)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.pathObject(new WorldPoint(2932, 3214, 0), DOOR_1540)
			.build(),
		CrypticClue.builder()
			.text("I wouldn't wear this jean on my legs.")
			.clueId(CLUE_SCROLL_EASY_19820)
			.npc("Father Jean")
			.location(new ClueArea(1734, 3576, 0))
			.area("Hosidius church")
			.teleport(XERICS_TALISMAN_XERICS_GLADE)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.teleport(KHAREDSTS_MEMOIRS_LUNCH_BY_THE_LANCALLIUMS)
			.teleport(MINIGAME_TITHE_FARM)
			.build(),
		CrypticClue.builder()
			.text("Look in the ground floor crates of houses in Falador.")
			.clueId(CLUE_SCROLL_EASY_2712)
			.objectId(CRATES_24088)
			.location(new ClueArea(3029, 3355, 0))
			.area("Falador, house west of fountain")
			.teleport(RING_OF_WEALTH_FALADOR)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(3028, 3356, 0), DOOR_24050)
			.build(),
		CrypticClue.builder()
			.text("Monk's residence in the far west. See robe storage device.")
			.clueId(CLUE_SCROLL_EASY_19818)
			.objectId(DRAWERS_350)
			.location(new ClueArea(1746, 3490, 0))
			.area("Hosidius, monk camp, south of PoH portal")
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.teleport(XERICS_TALISMAN_XERICS_GLADE)
			.teleport(SKILLS_NECKLACE_WOODCUTTING_GUILD)
			.teleport(MINIGAME_TITHE_FARM)
			.build(),
		CrypticClue.builder()
			.text("One of the sailors in Port Sarim is your next destination.")
			.clueId(CLUE_SCROLL_EASY_3496)
			.npc("Captain Tobias")
			.location(new ClueArea(3026, 3216, 0))
			.area("Port Sarim docks")
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(EXPLORERS_RING_2)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.build(),
		CrypticClue.builder()
			.text("Salty peter.")
			.clueId(CLUE_SCROLL_EASY_19825)
			.npc("Konoo")
			.location(new ClueArea(1709, 3548, 0))
			.area("Hosidius, saltpeter mine")
			.teleport(SKILLS_NECKLACE_WOODCUTTING_GUILD)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.teleport(XERICS_TALISMAN_XERICS_GLADE)
			.teleport(MINIGAME_TITHE_FARM)
			.extraMapPoint(new WorldPoint(1717, 3521, 0))
			.extraMapPoint(new WorldPoint(1703, 3511, 0))
			.extraMapPoint(new WorldPoint(1688, 3515, 0))
			.extraMapPoint(new WorldPoint(1687, 3532, 0))
			.build(),
		CrypticClue.builder()
			.text("Search a bookcase in Lumbridge swamp.")
			.clueId(CLUE_SCROLL_EASY_12166)
			.objectId(BOOKCASE_9523)
			.location(new ClueArea(3146, 3177, 0))
			.area("Lumbridge Swamp, Father Urhney's house")
			.teleport(NECKLACE_OF_PASSAGE_WIZARDS_TOWER)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3147, 3172, 0), DOOR_11616)
			.build(),
		CrypticClue.builder()
			.text("Search a bookcase in the Wizards tower.")
			.clueId(CLUE_SCROLL_EASY_12167)
			.objectId(BOOKCASE_12539)
			.location(new ClueArea(3113, 3159, 0))
			.area("Wizards' Tower, ground floor")
			.teleport(NECKLACE_OF_PASSAGE_WIZARDS_TOWER)
			.teleport(FAIRY_RING_DIS)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.pathObject(new WorldPoint(3109, 3167, 0), DOOR_23972)
			.pathObject(new WorldPoint(3111, 3162, 0), DOOR_23972)
			.build(),
		CrypticClue.builder()
			.text("Search a wardrobe in Draynor.")
			.clueId(CLUE_SCROLL_EASY_12168)
			.objectId(WARDROBE_5622)
			.location(new ClueArea(3087, 3261, 0))
			.area("Draynor Village, Aggie's house")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3088, 3258, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search chests found in the upstairs of shops in Port Sarim.")
			.clueId(CLUE_SCROLL_EASY_3495)
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(3016, 3205, 1))
			.area("Port Sarim, Food Store, 1st floor")
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(EXPLORERS_RING_2)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.pathObject(new WorldPoint(3016, 3206, 0), DOOR_1535)
			.pathObject(new WorldPoint(3013, 3203, 0), LADDER_16683)
			.build(),
		CrypticClue.builder()
			.text("Search for a crate in a building in Hemenster.")
			.clueId(CLUE_SCROLL_EASY_3506)
			.objectId(CRATE_357)
			.location(new ClueArea(2636, 3453, 0))
			.area("Hemenster, north-west house")
			.teleport(COMBAT_BRACELET_RANGING_GUILD)
			.teleport(STANDARD_SEERS)
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2641, 3452, 0), DOOR_1540)
			.build(),
		CrypticClue.builder()
			.text("Search for a crate in Varrock Castle.")
			.clueId(CLUE_SCROLL_EASY_3515)
			.objectId(CRATE_5113)
			.location(new ClueArea(3224, 3492, 0))
			.area("Varrock Castle kitchen")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3217, 3492, 0), DOOR_11773)
			.build(),
		CrypticClue.builder()
			.text("Search for a crate on the ground floor of a house in Seers' Village.")
			.clueId(CLUE_SCROLL_EASY_3509)
			.objectId(CRATE_25775)
			.location(new ClueArea(2699, 3470, 0))
			.area("Seers' Village, house south of pub")
			.teleport(STANDARD_SEERS)
			.teleport(COMBAT_BRACELET_RANGING_GUILD)
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2701, 3477, 0), DOOR_25819)
			.build(),
		CrypticClue.builder()
			.text("Search the bookcase in the monastery.")
			.clueId(CLUE_SCROLL_EASY_12177)
			.objectId(BOOKCASE_380)
			.location(new ClueArea(3054, 3484, 0))
			.area("Edgeville Monastery")
			.teleport(COMBAT_BRACELET_MONASTERY)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.build(),
		CrypticClue.builder()
			.text("Search the boxes in a shop in Taverley.")
			.clueId(CLUE_SCROLL_EASY_3499)
			.objectId(BOXES_360)
			.location(new ClueArea(2886, 3449, 0))
			.area("Taverley, Two-Handed Shop")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(MINIGAME_BURTHORPE)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2885, 3453, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the boxes in one of the tents in Al Kharid.")
			.clueId(CLUE_SCROLL_EASY_3501)
			.objectId(BOXES_361)
			.location(new ClueArea(3308, 3206, 0))
			.area("Al Kharid, tent west of cactus patch")
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(GNOME_GLIDER_AL_KHARID)
			.build(),
		CrypticClue.builder()
			.text("Search the boxes in the goblin house near Lumbridge.")
			.clueId(CLUE_SCROLL_EASY_2679)
			.objectId(BOXES)
			.location(new ClueArea(3245, 3245, 0))
			.area("Lumbridge, goblin house, east of river")
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3246, 3244, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the boxes in the house near the south entrance to Varrock.")
			.clueId(CLUE_SCROLL_EASY_2685)
			.objectId(BOXES_5111)
			.location(new ClueArea(3203, 3384, 0))
			.area("Varrock, south entrance, west house")
			.teleport(COMBAT_BRACELET_CHAMPIONS_GUILD)
			.teleport(CHRONICLE)
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3208, 3385, 0), DOOR_11777)
			.build(),
		CrypticClue.builder()
			.text("Search the boxes just outside the Armour shop in East Ardougne.")
			.clueId(CLUE_SCROLL_EASY_2705)
			.objectId(BOXES_361)
			.location(new ClueArea(2654, 3299, 0))
			.area("East Ardougne marketplace")
			.teleport(STANDARD_ARDOUGNE)
			.teleport(FAIRY_RING_DJP)
			.build(),
		CrypticClue.builder()
			.text("Search the boxes next to a chest that needs a crystal key.")
			.clueId(CLUE_SCROLL_EASY_23149)
			.objectId(BOXES_360)
			.location(new ClueArea(2915, 3452, 0))
			.area("Taverley, next to crystal chest")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(MINIGAME_BURTHORPE)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2896, 3450, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the boxes of Falador's general store.")
			.clueId(CLUE_SCROLL_EASY_2692)
			.objectId(CRATES_24088)
			.location(new ClueArea(2955, 3390, 0))
			.area("Falador, general store")
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2958, 3384, 0), DOOR_24056)
			.build(),
		CrypticClue.builder()
			.text("Search the bucket in the Port Sarim jail.")
			.clueId(CLUE_SCROLL_EASY_12192)
			.objectId(BUCKET_9568)
			.location(new ClueArea(3013, 3179, 0))
			.area("Shantay Pass, talk to Shantay, dialogue options: 1-1-2-2")
			.teleport(DIARY_CAPE_JARR)
			.teleport(DESERT_AMULET_4_KALPHITE_CAVE)
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(FAIRY_RING_BIQ)
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.build(),
		CrypticClue.builder()
			.text("Search the bush at the digsite centre.")
			.objectId(BUSH_2357)
			.location(new ClueArea(3345, 3378, 0))
			.area("Digsite, bush next to west walkway")
			.teleport(SCROLL_DIGSITE)
			.teleport(ANCIENT_SENNTISTEN)
			.teleport(DIGSITE_PENDANT_DIGSITE)
			.build(),
		CrypticClue.builder()
			.text("Search the chest in Barbarian Village.")
			.clueId(CLUE_SCROLL_EASY_12172)
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(3085, 3429, 0))
			.area("Barbarian Village, north-east house")
			.teleport(SKULL_SCEPTRE)
			.teleport(SKILLS_NECKLACE_COOKS_GUILD)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(STANDARD_VARROCK)
			.build(),
		CrypticClue.builder()
			.text("Search the chest in Fred the Farmer's bedroom.")
			.clueId(CLUE_SCROLL_EASY_23151)
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(3185, 3274, 0))
			.area("North-west of Lumbridge, Fred the Farmer's house")
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3189, 3279, 0), GATE_12987)
			.pathObject(new WorldPoint(3188, 3279, 0), GATE_12986)
			.pathObject(new WorldPoint(3189, 3275, 0), DOOR_13001)
			.pathObject(new WorldPoint(3188, 3272, 0), DOOR_13001)
			.build(),
		CrypticClue.builder()
			.text("Search the chest in the Duke of Lumbridge's bedroom.")
			.clueId(CLUE_SCROLL_EASY)
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(3209, 3218, 1))
			.area("Lumbridge castle, 1st floor")
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3204, 3229, 0), STAIRCASE_16671)
			.pathObject(new WorldPoint(3207, 3222, 1), DOOR_1543)
			.build(),
		CrypticClue.builder()
			.text("Search the chest in the left-hand tower of Camelot Castle.")
			.clueId(CLUE_SCROLL_EASY_2703)
			.objectId(CLOSED_CHEST_25592)
			.location(new ClueArea(2748, 3495, 2))
			.area("Camelot, west tower, second floor")
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2757, 3482, 0), GATE_26081)
			.pathObject(new WorldPoint(2758, 3482, 0), GATE_26082)
			.pathObject(new WorldPoint(2757, 3503, 0), LARGE_DOOR_25638)
			.pathObject(new WorldPoint(2758, 3503, 0), LARGE_DOOR_25640)
			.pathObject(new WorldPoint(2750, 3503, 0), DOOR_25642)
			.pathObject(new WorldPoint(2750, 3496, 0), DOOR_25642)
			.pathObject(new WorldPoint(2747, 3493, 0), LADDER_26107)
			.pathObject(new WorldPoint(2749, 3491, 1), LADDER_26107)
			.build(),
		CrypticClue.builder()
			.text("Search the chests in the Dwarven Mine.")
			.clueId(CLUE_SCROLL_EASY_3493)
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(3000, 9798, 0))
			.area("Dwarven Mine, Hura's Crossbow Shop")
			.teleport(SKILLS_NECKLACE_MINING_GUILD)
			.teleport(ANCIENT_LASSAR)
			.teleport(RING_OF_WEALTH_FALADOR)
			.teleport(STANDARD_FALADOR)
			.extraMapPoint(new WorldPoint(3058, 3376, 0))
			.extraMapPoint(new WorldPoint(3019, 3450, 0))
			.pathObject(new WorldPoint(3019, 3450, 0), TRAPDOOR_11867)
			.pathObject(new WorldPoint(3061, 3374, 0), DOOR_24057)
			.pathObject(new WorldPoint(3058, 3376, 0), STAIRCASE_16664)
			.build(),
		CrypticClue.builder()
			.text("Search the chests upstairs in Al Kharid Palace.")
			.clueId(CLUE_SCROLL_EASY_2680)
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(3301, 3169, 1))
			.area("Al Kharid palace, 1st floor")
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.pathObject(new WorldPoint(3284, 3165, 0), LADDER_16683)
			.build(),
		CrypticClue.builder()
			.text("Search the Coffin in Edgeville.")
			.clueId(CLUE_SCROLL_EASY_12174)
			.objectId(COFFIN)
			.location(new ClueArea(3091, 3477, 0))
			.area("Edgeville, near wilderness lever")
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(ANCIENT_PADDEWWA)
			.teleport(FAIRY_RING_DKR)
			.build(),
		CrypticClue.builder()
			.text("Search the crate in Rommiks crafting shop in Rimmington.")
			.clueId(CLUE_SCROLL_EASY_23153)
			.objectId(CRATE_9533)
			.location(new ClueArea(2946, 3207, 0))
			.area("Rimmington, crafting shop")
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(SKILLS_NECKLACE_CRAFTING_GUILD)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.pathObject(new WorldPoint(2951, 3207, 0), DOOR_1540)
			.build(),
		CrypticClue.builder()
			.text("Search the crate in the left-hand tower of Lumbridge Castle.")
			.clueId(CLUE_SCROLL_EASY_2678)
			.objectId(CRATE_357)
			.location(new ClueArea(3228, 3212, 1))
			.area("Lumbridge Castle, south entrance tower, 1st floor")
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3226, 3214, 0), DOOR_1535)
			.pathObject(new WorldPoint(3229, 3213, 0), LADDER_16683)
			.build(),
		CrypticClue.builder()
			.text("Search the crate in the Toad and Chicken pub.")
			.clueId(CLUE_SCROLL_EASY_12185)
			.objectId(CRATE_354)
			.location(new ClueArea(2913, 3536, 0))
			.area("Burthorpe pub")
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(MINIGAME_BURTHORPE)
			.pathObject(new WorldPoint(2907, 3544, 0), DOOR_1540)
			.build(),
		CrypticClue.builder()
			.text("Search the crate near a cart in Port Khazard.")
			.clueId(CLUE_SCROLL_EASY_3504)
			.objectId(CRATE_366)
			.location(new ClueArea(2660, 3149, 0))
			.area("Port Khazard, south general store")
			.teleport(LUNAR_KHAZARD)
			.teleport(MINIGAME_FISHING_TRAWLER)
			.teleport(ARDOUGNE_CLOAK_MONASTERY)
			.teleport(FAIRY_RING_DJP)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in a bank in Varrock.")
			.clueId(CLUE_SCROLL_EASY_12176)
			.objectId(CRATE_5107)
			.location(new ClueArea(3187, 9825, 0))
			.area("Varrock, west bank basement")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3186, 3434, 0), DOOR_11775)
			.pathObject(new WorldPoint(3187, 3433, 0), STAIRCASE_11800)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in a house in Yanille that has a piano.")
			.clueId(CLUE_SCROLL_EASY_3491)
			.objectId(CRATE_357)
			.location(new ClueArea(2598, 3105, 0))
			.area("Yanille, house north of Wizards' Guild")
			.teleport(STANDARD_YANILLE)
			.teleport(TELEPORT_TO_HOUSE_YANILLE)
			.teleport(MINIGAME_NIGHTMARE_ZONE)
			.teleport(FAIRY_RING_CIQ)
			.pathObject(new WorldPoint(2594, 3102, 0), LARGE_DOOR_17089)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in Canifis.")
			.clueId(CLUE_SCROLL_EASY_7238)
			.objectId(CRATE_24344)
			.location(new ClueArea(3509, 3497, 0))
			.area("Canifis, food shop")
			.teleport(ANCIENT_KHARYRLL)
			.teleport(ARCEUUS_SALVE_GRAVEYARD)
			.teleport(FAIRY_RING_CKS)
			.teleport(SLAYER_RING_SLAYER_TOWER)
			.requirement(new QuestRequirement(PRIEST_IN_PERIL))
			.pathObject(new WorldPoint(3504, 3492, 0), DOOR_24366)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in Draynor Manor.")
			.clueId(CLUE_SCROLL_EASY_3502)
			.objectId(CRATE_11485)
			.location(new ClueArea(3106, 3369, 2))
			.area("Draynor Manor, top floor")
			.teleport(ARCEUUS_DRAYNOR_MANOR)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.pathObject(new WorldPoint(3108, 3353, 0), LARGE_DOOR_134)
			.pathObject(new WorldPoint(3109, 3353, 0), LARGE_DOOR_135)
			.pathObject(new WorldPoint(3109, 3358, 0), DOOR_11470)
			.pathObject(new WorldPoint(3108, 3362, 0), STAIRCASE_11498)
			.pathObject(new WorldPoint(3104, 3362, 1), STAIRCASE_11511)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in East Ardougne's general store.")
			.clueId(CLUE_SCROLL_EASY_2706)
			.objectId(CRATE_357)
			.location(new ClueArea(2615, 3291, 0))
			.area("East Ardougne, general store")
			.teleport(STANDARD_ARDOUGNE)
			.teleport(SPIRIT_TREE_KHAZARD_BATTLEFIELD)
			.teleport(ARDOUGNE_CLOAK_MONASTERY)
			.pathObject(new WorldPoint(2614, 3295, 0), DOOR_1540)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in Falador General store.")
			.clueId(CLUE_SCROLL_EASY_23154)
			.objectId(CRATES_24088)
			.location(new ClueArea(2955, 3390, 0))
			.area("Falador, general store")
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2958, 3384, 0), DOOR_24056)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in Horvik's armoury.")
			.clueId(CLUE_SCROLL_EASY_2688)
			.objectId(CRATE_5106)
			.location(new ClueArea(3228, 3433, 0))
			.area("Varrock, platebody shop")
			.teleport(STANDARD_VARROCK)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the Barbarian Village helmet shop.")
			.clueId(CLUE_SCROLL_EASY_2690)
			.objectId(CRATES_11600)
			.location(new ClueArea(3073, 3430, 0))
			.area("Barbarian Village, helmet shop")
			.teleport(SKULL_SCEPTRE)
			.teleport(SKILLS_NECKLACE_COOKS_GUILD)
			.teleport(AMULET_OF_GLORY_EDGEVILLE)
			.teleport(STANDARD_VARROCK)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the Dwarven mine.")
			.clueId(CLUE_SCROLL_EASY_12178)
			.objectId(CRATE_357)
			.location(new ClueArea(3035, 9849, 0))
			.area("Dwarven Mine, north-east mining shop")
			.teleport(ANCIENT_LASSAR)
			.teleport(COMBAT_BRACELET_MONASTERY)
			.teleport(SKILLS_NECKLACE_MINING_GUILD)
			.extraMapPoint(new WorldPoint(3058, 3376, 0))
			.extraMapPoint(new WorldPoint(3019, 3450, 0))
			.pathObject(new WorldPoint(3019, 3450, 0), TRAPDOOR_11867)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the fruit store just east of the Hosidius town centre.")
			.clueId(CLUE_SCROLL_EASY_25789)
			.objectId(CRATES_27533)
			.location(new ClueArea(1799, 3613, 0))
			.area("Hosidius, east of town centre")
			.teleport(XERICS_TALISMAN_XERICS_GLADE)
			.teleport(KHAREDSTS_MEMOIRS_LUNCH_BY_THE_LANCALLIUMS)
			.teleport(TELEPORT_TO_HOUSE_HOSIDIUS)
			.teleport(MINIGAME_TITHE_FARM)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the guard house of the northern gate of East Ardougne.")
			.clueId(CLUE_SCROLL_EASY_2704)
			.objectId(CRATE_356)
			.location(new ClueArea(2645, 3338, 0))
			.area("East Ardougne, north-east of the Handelmort mansion")
			.teleport(STANDARD_ARDOUGNE)
			.teleport(ARDOUGNE_CLOAK_2_FARM)
			.pathObject(new WorldPoint(2644, 3333, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the most north-western house in Al Kharid.")
			.clueId(CLUE_SCROLL_EASY_2682)
			.objectId(CRATE_358)
			.location(new ClueArea(3289, 3202, 0))
			.area("Al Kharid, northmost house")
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(GNOME_GLIDER_AL_KHARID)
			.pathObject(new WorldPoint(3292, 3206, 0), CURTAIN_1533)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the outhouse of the long building in Taverley.")
			.clueId(CLUE_SCROLL_EASY_12191)
			.objectId(CRATE_357)
			.location(new ClueArea(2914, 3433, 0))
			.area("Taverley, outhouse south of crystal chest")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2917, 3438, 0), STILE)
			.pathObject(new WorldPoint(2914, 3435, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the Port Sarim Fishing shop.")
			.clueId(CLUE_SCROLL_EASY_2695)
			.objectId(CRATE_9534)
			.location(new ClueArea(3012, 3222, 0))
			.area("Port Sarim, fishing shop")
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.pathObject(new WorldPoint(3014, 3219, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the crates in the shed just north of East Ardougne.")
			.clueId(CLUE_SCROLL_EASY_2707)
			.objectId(CRATE_355)
			.location(new ClueArea(2617, 3347, 0))
			.area("East Ardougne, shed north of northern bank")
			.teleport(SKILLS_NECKLACE_FISHING_GUILD)
			.teleport(LUNAR_FISHING_GUILD)
			.teleport(STANDARD_ARDOUGNE)
			.pathObject(new WorldPoint(2616, 3345, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the crates near a cart in Varrock.")
			.clueId(CLUE_SCROLL_EASY_2709)
			.objectId(CRATE_5107)
			.location(new ClueArea(3226, 3452, 0))
			.area("Varrock, south-east of castle, next to tree patch")
			.teleport(STANDARD_VARROCK)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers above Varrock's shops.")
			.clueId(CLUE_SCROLL_EASY_2708)
			.objectId(DRAWERS_7194)
			.location(new ClueArea(3206, 3419, 1))
			.area("Varrock, Thessalia's clothing shop, 1st floor")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3209, 3415, 0), DOOR_11775)
			.pathObject(new WorldPoint(3202, 3416, 0), LADDER_11794)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers found upstairs in East Ardougne's houses.")
			.clueId(CLUE_SCROLL_EASY_2710)
			.objectId(DRAWERS)
			.location(new ClueArea(2574, 3326, 1))
			.area("East Ardougne, pub north of castle, 1st floor")
			.teleport(SPIRIT_TREE_KHAZARD_BATTLEFIELD)
			.teleport(LUNAR_FISHING_GUILD)
			.teleport(SKILLS_NECKLACE_FISHING_GUILD)
			.teleport(STANDARD_ARDOUGNE)
			.pathObject(new WorldPoint(2576, 3320, 0), DOOR_1540)
			.pathObject(new WorldPoint(2572, 3325, 0), STAIRCASE_16671)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers in a house in Draynor Village.")
			.clueId(CLUE_SCROLL_EASY_3512)
			.objectId(DRAWERS_350)
			.location(new ClueArea(3097, 3277, 0))
			.area("Draynor Village, northernmost house")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3100, 3276, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers in Catherby's Archery shop.")
			.clueId(CLUE_SCROLL_EASY_2700)
			.objectId(DRAWERS_350)
			.location(new ClueArea(2825, 3442, 0))
			.area("Catherby, ranging shop")
			.teleport(LUNAR_CATHERBY)
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2822, 3441, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers in Falador's chain mail shop.")
			.clueId(CLUE_SCROLL_EASY_2694)
			.objectId(DRAWERS)
			.location(new ClueArea(2969, 3311, 0))
			.area("Falador, chainmail shop")
			.teleport(SKILLS_NECKLACE_CRAFTING_GUILD)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2972, 3315, 0), 23972)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers in one of Gertrude's bedrooms.")
			.clueId(CLUE_SCROLL_EASY_2689)
			.objectId(DRAWERS_7194)
			.location(new ClueArea(3156, 3406, 0))
			.area("Gertrude's house, west of varrock")
			.teleport(SKILLS_NECKLACE_COOKS_GUILD)
			.teleport(COMBAT_BRACELET_CHAMPIONS_GUILD)
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3151, 3412, 0), DOOR_11775)
			.pathObject(new WorldPoint(3154, 3405, 0), DOOR_11780)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers in the ground floor of a shop in Yanille.")
			.clueId(CLUE_SCROLL_EASY_3492)
			.objectId(DRAWERS_350)
			.location(new ClueArea(2570, 3085, 0))
			.area("Yanille, hunter shop")
			.teleport(TELEPORT_TO_HOUSE_YANILLE)
			.teleport(STANDARD_YANILLE)
			.teleport(FAIRY_RING_CIQ)
			.teleport(MINIGAME_NIGHTMARE_ZONE)
			.pathObject(new WorldPoint(2563, 3082, 0), DOOR_1540)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers in the house next to the Port Sarim mage shop.")
			.clueId(CLUE_SCROLL_EASY_12188)
			.objectId(DRAWERS)
			.location(new ClueArea(3024, 3259, 0))
			.area("Port Sarim, northernmost house")
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.pathObject(new WorldPoint(3028, 3258, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers in the upstairs of a house in Catherby.")
			.clueId(CLUE_SCROLL_EASY_3507)
			.objectId(DRAWERS_350)
			.location(new ClueArea(2809, 3451, 1))
			.area("Catherby, north-west house")
			.teleport(LUNAR_CATHERBY)
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2806, 3452, 0), DOOR_1540)
			.pathObject(new WorldPoint(2807, 3454, 0), LADDER_16683)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers of houses in Burthorpe.")
			.clueId(CLUE_SCROLL_EASY_3490)
			.objectId(DRAWERS)
			.location(new ClueArea(2929, 3570, 0))
			.area("Burthorpe, north-east house")
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(MINIGAME_BURTHORPE)
			.pathObject(new WorldPoint(2932, 3564, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers on the ground floor of a building facing Ardougne's Market.")
			.clueId(CLUE_SCROLL_EASY_3505)
			.objectId(DRAWERS_350)
			.location(new ClueArea(2653, 3320, 0))
			.area("East Ardougne, house north of market")
			.teleport(STANDARD_ARDOUGNE)
			.teleport(ARDOUGNE_CLOAK_MONASTERY)
			.teleport(FAIRY_RING_DJP)
			.pathObject(new WorldPoint(2659, 3320, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers upstairs in Falador's shield shop.")
			.clueId(CLUE_SCROLL_EASY_2691)
			.objectId(DRAWERS)
			.location(new ClueArea(2971, 3386, 1))
			.area("Falador, shield shop, 1st floor")
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2971, 3383, 0), DOOR_24050)
			.pathObject(new WorldPoint(2973, 3384, 0), STAIRCASE_24075)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers downstairs of houses in the eastern part of Falador.")
			.clueId(CLUE_SCROLL_EASY_3498)
			.objectId(DRAWERS_350)
			.location(new ClueArea(3039, 3342, 0))
			.area("Falador, house south of fountain")
			.teleport(RING_OF_WEALTH_FALADOR)
			.teleport(SKILLS_NECKLACE_MINING_GUILD)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(3037, 3347, 0), DOOR_24050)
			.build(),
		CrypticClue.builder()
			.text("Search the drawers, upstairs in the bank to the East of Varrock.")
			.clueId(CLUE_SCROLL_EASY_2687)
			.objectId(DRAWERS_7194)
			.location(new ClueArea(3250, 3420, 1))
			.area("Varrock, east bank")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3255, 3421, 0), STAIRCASE_11789)
			.build(),
		// TODO: Duplicate? Does this really exist?
		CrypticClue.builder()
			.text("Search the eastern bookcase in Father Urhney's house.")
			.objectId(BOOKCASE_9523)
			.location(new ClueArea(3149, 3177, 0))
			.area("Lumbridge Swamp, Father Urhney's house")
			.teleport(NECKLACE_OF_PASSAGE_WIZARDS_TOWER)
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3147, 3172, 0), DOOR_11616)
			.build(),
		CrypticClue.builder()
			.text("Search the open crate found in the Hosidius kitchens.")
			.clueId(CLUE_SCROLL_EASY_19829)
			.objectId(CRATES_27533)
			.location(new ClueArea(1683, 3616, 0))
			.area("Hosidius, kitchens south-east of castle")
			.teleport(KHAREDSTS_MEMOIRS_LUNCH_BY_THE_LANCALLIUMS)
			.teleport(SCROLL_WATSON)
			.teleport(XERICS_TALISMAN_XERICS_HEART)
			.teleport(STANDARD_KOUREND)
			.pathObject(new WorldPoint(1679, 3614, 0), DOOR_7452)
			.build(),
		CrypticClue.builder()
			.text("Search the single crate in Horvik's smithy in Varrock.")
			.clueId(CLUE_SCROLL_EASY_23152)
			.objectId(CRATE_5106)
			.location(new ClueArea(3228, 3433, 0))
			.area("Varrock, platebody shop")
			.teleport(STANDARD_VARROCK)
			.build(),
		CrypticClue.builder()
			.text("Search the tents in the Imperial Guard camp in Burthorpe for some boxes.")
			.objectId(BOXES_3686)
			.location(new ClueArea(2885, 3540, 0))
			.area("Burthorpe, Imperial camp, north-west tent")
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(MINIGAME_BURTHORPE)
			.build(),
		CrypticClue.builder()
			.text("Search the wheelbarrow in Rimmington mine.")
			.clueId(CLUE_SCROLL_EASY_12189)
			.objectId(WHEELBARROW_9625)
			.location(new ClueArea(2978, 3239, 0))
			.area("Rimmington mine")
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(SKILLS_NECKLACE_CRAFTING_GUILD)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.build(),
		CrypticClue.builder()
			.text("Search through chests found in the upstairs of houses in eastern Falador.")
			.clueId(CLUE_SCROLL_EASY_3497)
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(3041, 3364, 1))
			.area("Falador, house north of fountain, 1st floor")
			.teleport(RING_OF_WEALTH_FALADOR)
			.teleport(SKILLS_NECKLACE_MINING_GUILD)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(3038, 3361, 0), DOOR_24050)
			.pathObject(new WorldPoint(3034, 3362, 0), STAIRCASE_24075)
			.build(),
		CrypticClue.builder()
			.text("Search through some drawers found in Taverley's houses.")
			.clueId(CLUE_SCROLL_EASY_3500)
			.objectId(DRAWERS_350)
			.location(new ClueArea(2894, 3418, 0))
			.area("Taverley, house south of herbalist")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2893, 3421, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Search through some drawers in the upstairs of a house in Rimmington.")
			.clueId(CLUE_SCROLL_EASY_3494)
			.objectId(DRAWERS_352)
			.location(new ClueArea(2970, 3214, 1))
			.area("Rimmington, north-east house, 1st floor")
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(SKILLS_NECKLACE_CRAFTING_GUILD)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.pathObject(new WorldPoint(2962, 3213, 0), DOOR_1540)
			.pathObject(new WorldPoint(2965, 3215, 0), STAIRCASE_18991)
			.build(),
		CrypticClue.builder()
			.text("Search upstairs in the houses of Seers' Village for some drawers.")
			.clueId(CLUE_SCROLL_EASY_3508)
			.objectId(DRAWERS_25766)
			.location(new ClueArea(2716, 3471, 1))
			.area("Seers' Village, south house with spinning wheel, 1st floor")
			.teleport(STANDARD_SEERS)
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2716, 3472, 0), DOOR_25819)
			.pathObject(new WorldPoint(2715, 3470, 0), LADDER_25938)
			.build(),
		CrypticClue.builder()
			.text("Someone watching the fights in the Duel Arena is your next destination.")
			.clueId(CLUE_SCROLL_EASY_3514)
			.npc("Jeed")
			.location(new ClueArea(3360, 3242, 0))
			.area("Duel Arena, upper floor, center-north")
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.build(),
		CrypticClue.builder()
			.text("Speak to Arhein in Catherby.")
			.clueId(CLUE_SCROLL_EASY_2701)
			.npc("Arhein")
			.location(new ClueArea(2803, 3430, 0))
			.area("Catherby docks")
			.teleport(LUNAR_CATHERBY)
			.teleport(STANDARD_CAMELOT)
			.build(),
		CrypticClue.builder()
			.text("Speak to Doric, who lives north of Falador.")
			.clueId(CLUE_SCROLL_EASY_2698)
			.npc("Doric")
			.location(new ClueArea(2951, 3451, 0))
			.area("Doric's house, north of Falador")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2949, 3450, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Speak to Ellis in Al Kharid.")
			.clueId(CLUE_SCROLL_EASY_2684)
			.npc("Ellis")
			.location(new ClueArea(3276, 3191, 0))
			.area("Al Kharid, tanner")
			.teleport(AMULET_OF_GLORY_AL_KHARID)
			.teleport(RING_OF_DUELING_DUEL_ARENA)
			.teleport(GNOME_GLIDER_AL_KHARID)
			.pathObject(new WorldPoint(3277, 3191, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Speak to Gaius in Taverley.")
			.clueId(CLUE_SCROLL_EASY_2699)
			.npc("Gaius")
			.location(new ClueArea(2884, 3450, 0))
			.area("Taverley, Two-Handed Shop")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(COMBAT_BRACELET_WARRIORS_GUILD)
			.teleport(GAMES_NECKLACE_BURTHORPE)
			.teleport(MINIGAME_BURTHORPE)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2885, 3453, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Speak to Hans to solve the clue.")
			.clueId(CLUE_SCROLL_EASY_2681)
			.npc("Hans")
			.location(new ClueArea(3211, 3219, 0))
			.area("Lumbridge, castle courtyard")
			.teleport(STANDARD_LUMBRIDGE)
			.build(),
		CrypticClue.builder()
			.text("Speak to Jatix in Taverley.")
			.clueId(CLUE_SCROLL_EASY_12184)
			.npc("Jatix")
			.location(new ClueArea(2898, 3428, 0))
			.area("Taverley, herbalist")
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(2902, 3428, 0), DOOR_1535)
			.pathObject(new WorldPoint(2894, 3428, 0), DOOR_1535)
			.build(),
		CrypticClue.builder()
			.text("Speak to Ned in Draynor Village.")
			.clueId(CLUE_SCROLL_EASY_2697)
			.npc("Ned")
			.location(new ClueArea(3098, 3258, 0))
			.area("Draynor Village, house north-east of bank")
			.teleport(AMULET_OF_GLORY_DRAYNOR_VILLAGE)
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(EXPLORERS_RING_2)
			.teleport(STANDARD_LUMBRIDGE)
			.pathObject(new WorldPoint(3101, 3258, 0), DOOR_1535)
			.build(),
		// TODO: Swap talk-to
		CrypticClue.builder()
			.text("Speak to Rusty north of Falador.")
			.clueId(CLUE_SCROLL_EASY_12187)
			.npc("Rusty")
			.location(new ClueArea(2979, 3435, 0))
			.area("North of Falador, south of Miazrqa's tower")
			.teleport(STANDARD_FALADOR)
			.build(),
		CrypticClue.builder()
			.text("Speak to Sarah at Falador farm.")
			.clueId(CLUE_SCROLL_EASY_12186)
			.npc("Sarah")
			.location(new ClueArea(3038, 3292, 0))
			.area("Falador farm")
			.teleport(EXPLORERS_RING_2)
			.teleport(SPIRIT_TREE_PORT_SARIM)
			.teleport(MINIGAME_RAT_PITS_PORT_SARIM)
			.teleport(TELEPORT_TO_HOUSE_RIMMINGTON)
			.teleport(STANDARD_FALADOR)
			.pathObject(new WorldPoint(3039, 3297, 0), DOOR_8695)
			.pathObject(new WorldPoint(3034, 3291, 0), DOOR_8695)
			.build(),
		CrypticClue.builder()
			.text("Speak to Sir Kay in Camelot Castle.")
			.clueId(CLUE_SCROLL_EASY_2702)
			.npc("Sir Kay")
			.location(new ClueArea(2759, 3497, 0))
			.area("Camelot Castle, courtyard")
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2757, 3482, 0), GATE_26081)
			.pathObject(new WorldPoint(2758, 3482, 0), GATE_26082)
			.build(),
		CrypticClue.builder()
			.text("Speak to the bartender of the Blue Moon Inn in Varrock.")
			.clueId(CLUE_SCROLL_EASY_2686)
			.npc("Bartender")
			.location(new ClueArea(3226, 3399, 0))
			.area("Varrock, Blue Moon Inn")
			.teleport(STANDARD_VARROCK)
			.pathObject(new WorldPoint(3215, 3395, 0), DOOR_11775)
			.build(),
		CrypticClue.builder()
			.text("Speak to The Lady of the Lake.")
			.clueId(CLUE_SCROLL_EASY_12190)
			.npc("The Lady of the Lake")
			.location(new ClueArea(2924, 3405, 0))
			.area("Taverley, Lady of the Lake")
			.teleport(HOT_AIR_BALLOON_TAVERLEY)
			.teleport(TELEPORT_TO_HOUSE_TAVERLEY)
			.teleport(STANDARD_FALADOR)
			.build(),
		CrypticClue.builder()
			.text("Speak to the staff of Sinclair mansion.")
			.clueId(CLUE_SCROLL_EASY_3513)
			.npc("Louisa")
			.location(new ClueArea(2736, 3578, 0))
			.area("Sinclair Mansion")
			.teleport(FAIRY_RING_CJR)
			.teleport(STANDARD_SEERS)
			.teleport(STANDARD_CAMELOT)
			.pathObject(new WorldPoint(2741, 3555, 0), GATE_26130)
			.pathObject(new WorldPoint(2742, 3555, 0), GATE_26131)
			.pathObject(new WorldPoint(2740, 3572, 0), LARGE_DOOR_25748)
			.pathObject(new WorldPoint(2741, 3572, 0), LARGE_DOOR_25750)
			.build(),
		// Here
		CrypticClue.builder()
			.text("Strength potions with red spiders' eggs? He is quite a herbalist.")
			.clueId(CLUE_SCROLL_EASY_19817)
			.npc("Apothecary")
			.location(new ClueArea(3194, 3403, 0))
			.area("Talk to Apothecary in the South-western Varrock. (the) apothecary is just north-west of the Varrock Swordshop.")
			.build(),
		CrypticClue.builder()
			.text("Surrounded by white walls and gems.")
			.clueId(CLUE_SCROLL_EASY_19819)
			.npc("Herquin")
			.location(new ClueArea(2945, 3335, 0))
			.area("Talk to Herquin, the gem store owner in Falador.")
			.build(),
		CrypticClue.builder()
			.text("Talk to a party-goer in Falador.")
			.clueId(CLUE_SCROLL_EASY_12169)
			.npc("Lucy")
			.location(new ClueArea(3046, 3382, 1))
			.area("Lucy is the bartender on the first floor of the party room.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Ali the Leaflet Dropper north of the Al Kharid mine.")
			.clueId(CLUE_SCROLL_EASY_23164)
			.npc("Ali the Leaflet Dropper")
			.location(new ClueArea(3283, 3329, 0))
			.area("Ali the Leaflet Dropper can be found roaming north of the Al Kharid mine.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Ambassador Spanfipple in the White Knights Castle.")
			.clueId(CLUE_SCROLL_EASY_12182)
			.npc("Ambassador Spanfipple")
			.location(new ClueArea(2982, 3340, 1))
			.area("Ambassador Spanfipple can be found roaming on the first floor of the White Knights Castle.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Cassie in Falador.")
			.clueId(CLUE_SCROLL_EASY_12181)
			.npc("Cassie")
			.location(new ClueArea(2975, 3383, 0))
			.area("Cassie is found just south-east of the northern Falador gate.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Charles at Port Piscarilius.")
			.clueId(CLUE_SCROLL_EASY_23161)
			.npc("Charles")
			.location(new ClueArea(1821, 3690, 0))
			.area("Charles is found by Veos' ship in Port Piscarilius.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Ermin.")
			.clueId(CLUE_SCROLL_EASY_19828)
			.npc("Ermin")
			.location(new ClueArea(2488, 3409, 1))
			.area("Ermin can be found on the first floor of the tree house south-east of the Gnome Agility Course.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Morgan in his house at Draynor Village.")
			.clueId(CLUE_SCROLL_EASY_23162)
			.npc("Morgan")
			.location(new ClueArea(3098, 3268, 0))
			.area("Morgan can be found in the house with the quest start map icon.")
			.build(),
		CrypticClue.builder()
			.text("Talk to the barber in the Falador barber shop.")
			.clueId(CLUE_SCROLL_EASY_12183)
			.npc("Hairdresser")
			.location(new ClueArea(2945, 3379, 0))
			.area("The Hairdresser can be found in the barber shop, north of the west Falador bank.")
			.build(),
		CrypticClue.builder()
			.text("Talk to the bartender of the Rusty Anchor in Port Sarim.")
			.clueId(CLUE_SCROLL_EASY_2696)
			.npc("Bartender")
			.location(new ClueArea(3045, 3256, 0))
			.area("The Rusty Anchor is located in the north of Port Sarim.")
			.build(),
		CrypticClue.builder()
			.text("Talk to the cook in the Blue Moon Inn in Varrock.")
			.clueId(CLUE_SCROLL_EASY_23166)
			.npc("Cook")
			.location(new ClueArea(3230, 3401, 0))
			.area("The Blue Moon Inn can be found by the southern entrance to Varrock.")
			.build(),
		CrypticClue.builder()
			.text("Talk to the Doomsayer.")
			.clueId(CLUE_SCROLL_EASY_19830)
			.npc("Doomsayer")
			.location(new ClueArea(3232, 3228, 0))
			.area("Doomsayer can be found just north of Lumbridge Castle entrance.")
			.build(),
		CrypticClue.builder()
			.text("Talk to the mother of a basement dwelling son.")
			.clueId(CLUE_SCROLL_EASY_12173)
			.npc("Doris")
			.location(new ClueArea(3079, 3493, 0))
			.area("Evil Dave's mother, Doris is located in the house west of Edgeville bank.")
			.build(),
		CrypticClue.builder()
			.text("Talk to the Squire in the White Knights' castle in Falador.")
			.clueId(CLUE_SCROLL_EASY_2693)
			.npc("Squire")
			.location(new ClueArea(2977, 3343, 0))
			.area("The squire is located in the courtyard of the White Knights' Castle.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Turael in Burthorpe.")
			.clueId(CLUE_SCROLL_EASY_23165)
			.npc("Turael")
			.location(new ClueArea(2930, 3536, 0))
			.area("Turael is located in the small house east of the Toad and Chicken inn.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Wayne at Wayne's Chains in Falador.")
			.clueId(CLUE_SCROLL_EASY_23163)
			.npc("Wayne")
			.location(new ClueArea(2972, 3312, 0))
			.area("Wayne's shop is found directly south of the White Knights' Castle.")
			.build(),
		CrypticClue.builder()
			.text("Talk to Zeke in Al Kharid.")
			.clueId(CLUE_SCROLL_EASY_2683)
			.npc("Zeke")
			.location(new ClueArea(3287, 3190, 0))
			.area("Zeke is the owner of the scimitar shop in Al Kharid.")
			.build(),
		CrypticClue.builder()
			.text("Thanks, Grandma!")
			.clueId(CLUE_SCROLL_EASY_19821)
			.npc("Tynan")
			.location(new ClueArea(1836, 3786, 0))
			.area("Tynan can be found in the north-east corner of Port Piscarilius.")
			.build(),
		CrypticClue.builder()
			.text("The hand ain't listening.")
			.clueId(CLUE_SCROLL_EASY_19824)
			.npc("The Face")
			.location(new ClueArea(3019, 3232, 0))
			.area("Talk to The Face located by the manhole just north of the Port Sarim fishing shop.")
			.build(),

		// Medium
		CrypticClue.builder()
			.text("A town with a different sort of night-life is your destination. Search for some crates in one of the houses.")
			.clueId(CLUE_SCROLL_MEDIUM_3609)
			.objectId(CRATE_24344)
			.location(new ClueArea(3498, 3507, 0))
			.area("Search the crate inside of the clothes shop in Canifis.")
			.build(),
		CrypticClue.builder()
			.text("Find a crate close to the monks that like to paaarty!")
			.clueId(CLUE_SCROLL_MEDIUM_3610)
			.objectId(CRATE_354)
			.location(new ClueArea(2614, 3204, 0))
			.area("The crate is in the east side of the Ardougne monastery, near Brother Omad")
			.build(),
		CrypticClue.builder()
			.text("Go to the village being attacked by trolls, search the drawers in one of the houses.")
			.clueId(CLUE_SCROLL_MEDIUM_3607)
			.npc("Penda")
			.objectId(DRAWERS_350)
			.location(new ClueArea(2921, 3577, 0))
			.area("Go to Dunstan's house in the northeast corner of Burthorpe. Kill Penda in the Toad and Chicken to obtain the key.")
			.build(),
		CrypticClue.builder()
			.text("Go to this building to be illuminated, and check the drawers while you are there.")
			.clueId(CLUE_SCROLL_MEDIUM_7298)
			.npc("Market Guard")
			.objectId(DRAWERS_350)
			.location(new ClueArea(2512, 3641, 1))
			.area("Search the drawers in the first floor of the Lighthouse. Kill a Rellekka marketplace guard to obtain the key.")
			.build(),
		CrypticClue.builder()
			.text("In a town where everyone has perfect vision, seek some locked drawers in a house that sits opposite a workshop.")
			.clueId(CLUE_SCROLL_MEDIUM_2837)
			.npc("Chicken")
			.objectId(DRAWERS_25766)
			.location(new ClueArea(2709, 3478, 0))
			.area("The Seers' Village house south of the Elemental Workshop entrance. Kill any Chicken to obtain a key.")
			.build(),
		CrypticClue.builder()
			.text("In a town where the guards are armed with maces, search the upstairs rooms of the Public House.")
			.clueId(CLUE_SCROLL_MEDIUM_2833)
			.npc("Guard dog")
			.objectId(348)
			.location(new ClueArea(2574, 3326, 1))
			.area("Search the drawers upstairs in the pub north of Ardougne Castle. Kill a Guard dog at Handelmort Mansion to obtain the key.")
			.build(),
		CrypticClue.builder()
			.text("In a town where thieves steal from stalls, search for some drawers in the upstairs of a house near the bank.")
			.clueId(CLUE_SCROLL_MEDIUM_2835)
			.npc("Guard")
			.objectId(DRAWERS)
			.location(new ClueArea(2611, 3324, 1))
			.area("Kill any Guard located around East Ardougne for a medium key. Then search the drawers in the upstairs hallway of Jerico's house, which is the house with pigeon cages located south of the northern East Ardougne bank.")
			.build(),
		CrypticClue.builder()
			.text("In a town where wizards are known to gather, search upstairs in a large house to the north.")
			.clueId(CLUE_SCROLL_MEDIUM_2839)
			.npc("Man")
			.objectId(375)
			.location(new ClueArea(2593, 3108, 1))
			.area("Search the chest upstairs in the house north of Yanille Wizard's Guild. Kill a man for the key.")
			.build(),
		CrypticClue.builder()
			.text("In a village made of bamboo, look for some crates under one of the houses.")
			.clueId(CLUE_SCROLL_MEDIUM_3604)
			.objectId(CRATE_356)
			.location(new ClueArea(2800, 3074, 0))
			.area("Search the crate by the house at the northern point of the broken jungle fence in Tai Bwo Wannai.")
			.build(),
		CrypticClue.builder()
			.text("Probably filled with wizards socks.")
			.clueId(CLUE_SCROLL_MEDIUM_7301)
			.npc("Wizard")
			.objectId(DRAWERS_350)
			.location(new ClueArea(3116, 9562, 0))
			.area("Search the drawers in the basement of the Wizard's Tower south of Draynor Village. Kill one of the Wizards for the key. Fairy ring DIS")
			.build(),
		CrypticClue.builder()
			.text("Search the basket of apples in an orchard, south of the unknown grave surrounded by white roses.")
			.clueId(CLUE_SCROLL_MEDIUM_25783)
			.objectId(APPLE_BASKET)
			.location(new ClueArea(1718, 3626, 0))
			.area("Hosidius orchard")
			.build(),
		CrypticClue.builder()
			.clueId(CLUE_SCROLL_MEDIUM_3605)
			.text("Search the upstairs drawers of a house in a village where pirates are known to have a good time.")
			.npc("Pirate")
			.objectId(DRAWERS)
			.location(new ClueArea(2809, 3165, 1))
			.area("The house in the southeast corner of Brimhaven, northeast of Davon's Amulet Store. Kill any Pirate located around Brimhaven to obtain the key.")
			.build(),
		CrypticClue.builder()
			.text("Speak to a referee.")
			.clueId(CLUE_SCROLL_MEDIUM_2853)
			.npc("Gnome ball referee")
			.location(new ClueArea(2386, 3487, 0))
			.area("Talk to a Gnome ball referee found on the Gnome ball field in the Gnome Stronghold. Answer: 5096")
			.question("What is 57 x 89 + 23?")
			.build(),
		CrypticClue.builder()
			.text("Speak to Donovan, the Family Handyman.")
			.clueId(CLUE_SCROLL_MEDIUM_2855)
			.npc("Donovan the Family Handyman")
			.location(new ClueArea(2743, 3578, 1))
			.area("Donovan the Family Handyman is found on the first floor of Sinclair Mansion.")
			.build(),
		CrypticClue.builder()
			.text("Speak to Hajedy.")
			.clueId(CLUE_SCROLL_MEDIUM_2848)
			.npc("Hajedy")
			.location(new ClueArea(2779, 3211, 0))
			.area("Hajedy is found by the cart, located just south of the Brimhaven docks.")
			.build(),
		CrypticClue.builder()
			.text("Speak to Hazelmere.")
			.clueId(CLUE_SCROLL_MEDIUM_2841)
			.npc("Hazelmere")
			.location(new ClueArea(2677, 3088, 1))
			.area("Located upstairs in the house to the north of fairy ring CLS. Answer: 6859")
			.question("What is 19 to the power of 3?")
			.build(),
		CrypticClue.builder()
			.text("Speak to Kangai Mau.")
			.clueId(CLUE_SCROLL_MEDIUM_3617)
			.npc("Kangai Mau")
			.location(new ClueArea(2791, 3183, 0))
			.area("Kangai Mau is found in the Shrimp and Parrot in Brimhaven.")
			.build(),
		CrypticClue.builder()
			.text("Speak to Roavar.")
			.clueId(CLUE_SCROLL_MEDIUM_3615)
			.npc("Roavar")
			.location(new ClueArea(3494, 3474, 0))
			.area("Talk to Roavar in the Canifis tavern.")
			.build(),
		CrypticClue.builder()
			.text("Speak to Ulizius.")
			.clueId(CLUE_SCROLL_MEDIUM_3614)
			.npc("Ulizius")
			.location(new ClueArea(3444, 3461, 0))
			.area("Ulizius is the monk who guards the gate into Mort Myre Swamp. South of fairy ring CKS")
			.build(),
		CrypticClue.builder()
			.text("The dead, red dragon watches over this chest. He must really dig the view.")
			.clueId(CLUE_SCROLL_MEDIUM_7296)
			.npc("Barbarian")
			.objectId(375)
			.location(new ClueArea(3353, 3332, 0))
			.area("Search the chest underneath the Red Dragon's head in the Exam Centre. Kill a MALE Barbarian in Barbarian Village or Barbarian Outpost to receive the key.")
			.build(),
		CrypticClue.builder()
			.text("This crate holds a better reward than a broken arrow.")
			.clueId(CLUE_SCROLL_MEDIUM_7304)
			.objectId(CRATE_356)
			.location(new ClueArea(2671, 3437, 0))
			.area("Inside the Ranging Guild. Search the crate behind the northern most building.")
			.build(),
		CrypticClue.builder()
			.text("This crate is mine, all mine, even if it is in the middle of the desert.")
			.clueId(CLUE_SCROLL_MEDIUM_7303)
			.objectId(CRATE_18889)
			.location(new ClueArea(3289, 3022, 0))
			.area("Center of desert Mining Camp. Search the crates. Requires the metal key from Tourist Trap to enter.")
			.build(),
		CrypticClue.builder()
			.text("Try not to step on any aquatic nasties while searching this crate.")
			.clueId(CLUE_SCROLL_MEDIUM_7300)
			.objectId(CRATE_18204)
			.location(new ClueArea(2764, 3273, 0))
			.area("Search the crate in Bailey's house on the Fishing Platform.")
			.build(),
		CrypticClue.builder()
			.text("You'll need to look for a town with a central fountain. Look for a locked chest in the town's chapel.")
			.clueId(CLUE_SCROLL_MEDIUM_2831)
			.npc("Monk")
			.objectId(CLOSED_CHEST_5108)
			.location(new ClueArea(3256, 3487, 0))
			.area("Search the chest by the stairs in the Varrock church. Kill a Monk in Ardougne Monastery to obtain the key.")
			.build(),
		// TODO: A graceful man of many colours, his crates must be full of many delights.

		// Hard
		CrypticClue.builder()
			.text("'A bag belt only?', he asked his balding brothers.")
			.clueId(CLUE_SCROLL_HARD_2793)
			.npc("Abbot Langley")
			.location(new ClueArea(3058, 3487, 0))
			.area("Talk-to Abbot Langley in Monastery west of Edgeville")
			.build(),
		CrypticClue.builder()
			.text("'Small shoe.' Often found with rod on mushroom.")
			.clueId(CLUE_SCROLL_HARD_3577)
			.npc("Gnome trainer")
			.location(new ClueArea(2476, 3428, 0))
			.area("Talk to any Gnome trainer in the agility area of the Tree Gnome Stronghold.")
			.build(),
		CrypticClue.builder()
			.text("46 is my number. My body is the colour of burnt orange and crawls among those with eight. Three mouths I have, yet I cannot eat. My blinking blue eye hides my grave.")
			.clueId(CLUE_SCROLL_HARD_2788)
			.location(new ClueArea(3169, 3884, 3171, 3886, 0))
			.area("Sapphire respawn in the Spider's Nest, lvl 46 Wilderness. Dig under the sapphire spawn.")
			.build(),
		CrypticClue.builder()
			.text("A general who sets a 'shining' example.")
			.clueId(CLUE_SCROLL_HARD_3564)
			.npc("General Hining")
			.location(new ClueArea(2186, 3148, 0))
			.area("Talk to General Hining in Tyras Camp.")
			.build(),
		CrypticClue.builder()
			.text("A great view - watch the rapidly drying hides get splashed. Check the box you are sitting on.")
			.clueId(CLUE_SCROLL_HARD_3573)
			.objectId(BOXES)
			.location(new ClueArea(2523, 3493, 1))
			.area("Almera's House north of Baxtorian Falls, search boxes on the first floor.")
			.build(),
		CrypticClue.builder()
			.text("Aggie I see. Lonely and southern I feel. I am neither inside nor outside the house, yet no home would be complete without me. The treasure lies beneath me!")
			.clueId(CLUE_SCROLL_HARD_2780)
			.location(new ClueArea(3084, 3254, 3086, 3256, 0))
			.area("Dig outside the window of Aggie's house in Draynor Village.")
			.build(),
		CrypticClue.builder()
			.text("A I Q 0 4 4 0")
			.clueId(CLUE_SCROLL_HARD_19862)
			.location(new ClueArea(3000, 3110, 0))
			.area("Mudskipper Point (AIQ)")
			.build(),
		CrypticClue.builder()
			.text("A I R 2 3 3 1")
			.clueId(CLUE_SCROLL_HARD_19864)
			.location(new ClueArea(2702, 3246, 0))
			.area("Ardougne Island (AIR)")
			.build(),
		CrypticClue.builder()
			.text("A L P 1 1 4 0")
			.clueId(CLUE_SCROLL_HARD_19866)
			.location(new ClueArea(2504, 3633, 0))
			.area("Lighthouse (ALP)")
			.build(),
		CrypticClue.builder()
			.text("And so on, and so on, and so on. Walking from the land of many unimportant things leads to a choice of paths.")
			.clueId(CLUE_SCROLL_HARD_7243)
			.location(new ClueArea(2591, 3878, 2593, 3880, 0))
			.area("Dig on Etceteria next to the Evergreen tree in front of the castle walls.")
			.build(),
		// TODO: Center
		CrypticClue.builder()
			.text("Where the best are commemorated, and a celebratory cup, not just for beer.")
			.location(new ClueArea(3387, 3150, 3390, 3152, 0))
			.area("TODO Dig at the Clan Cup Trophy south-west of Citharede Abbey.")
			.build(),
		CrypticClue.builder()
			.text("B I P 7 0 1 3")
			.clueId(CLUE_SCROLL_HARD_19868)
			.location(new ClueArea(3407, 3330, 0))
			.area("Mort Myre Island (BIP)")
			.build(),
		CrypticClue.builder()
			.text("B J R 1 1 2 3")
			.clueId(CLUE_SCROLL_HARD_19870)
			.location(new ClueArea(2648, 4729, 0))
			.area("Fisher Realm (BJR)")
			.build(),
		CrypticClue.builder()
			.text("B L P 6 2 0 0")
			.clueId(CLUE_SCROLL_HARD_19872)
			.location(new ClueArea(2439, 5132, 0))
			.area("Mor Ul Rek (BLP)")
			.build(),
		CrypticClue.builder()
			.text("C I S 0 0 0 9")
			.clueId(CLUE_SCROLL_HARD_19880)
			.location(new ClueArea(1630, 3868, 0))
			.area("Northern Arceuus (CIS)")
			.build(),
		CrypticClue.builder()
			.text("Citric cellar.")
			.clueId(CLUE_SCROLL_HARD_3575)
			.npc("Heckel Funch")
			.location(new ClueArea(2490, 3488, 1))
			.area("Speak to Heckel Funch on the first floor in the Grand Tree.")
			.build(),
		CrypticClue.builder()
			.text("C K P 0 2 2 4")
			.clueId(CLUE_SCROLL_HARD_19874)
			.location(new ClueArea(2073, 4846, 0))
			.area("Cosmic Plane (CKP)")
			.build(),
		CrypticClue.builder()
			.text("Come have a cip with this great soot covered denizen.")
			.clueId(CLUE_SCROLL_HARD_19846)
			.npc("Miner Magnus")
			.location(new ClueArea(2527, 3891, 0))
			.area("Talk to Miner Magnus east of the fairy ring CIP. Answer: 8")
			.question("How many coal rocks are around here?")
			.build(),
		CrypticClue.builder()
			.text("Come to the evil ledge, Yew know yew want to. Try not to get stung.")
			.clueId(CLUE_SCROLL_HARD_2774)
			.location(new ClueArea(3088, 3468, 3089, 3470, 0))
			.area("Dig in Edgeville, just east of the Southern Yew tree.")
			.build(),
		CrypticClue.builder()
			.text("Covered in shadows, the centre of the circle is where you will find the answer.")
			.clueId(CLUE_SCROLL_HARD_7245)
			.location(new ClueArea(3486, 3285, 3490, 3289, 0))
			.area("Dig in the centre of Mort'ton, where the roads intersect")
			.build(),
		CrypticClue.builder()
			.text("Dig where 4 siblings and I all live with our evil overlord.")
			.clueId(CLUE_SCROLL_HARD_19848)
			.location(new ClueArea(3195, 3353, 3198, 3358, 0))
			.area("Dig in the chicken pen inside the Champions' Guild")
			.build(),
		CrypticClue.builder()
			.text("D I P 8 5 1 1")
			.clueId(CLUE_SCROLL_HARD_19876)
			.location(new ClueArea(3041, 4770, 0))
			.area("Abyssal Nexus (DIP)")
			.build(),
		CrypticClue.builder()
			.text("D K S 2 3 1 0")
			.clueId(CLUE_SCROLL_HARD_19878)
			.location(new ClueArea(2747, 3720, 0))
			.area("North-East of Rellekka (DKS)")
			.build(),
		CrypticClue.builder()
			.text("Four blades I have, yet draw no blood; Still I turn my prey to powder. If you are brave, come search my roof; It is there my blades are louder.")
			.clueId(CLUE_SCROLL_HARD_2785)
			.objectId(CRATE_12963)
			.location(new ClueArea(3166, 3309, 2))
			.area("Lumbridge windmill, search the crates on the top floor.")
			.build(),
		CrypticClue.builder()
			.text("Generally speaking, his nose was very bent.")
			.clueId(CLUE_SCROLL_HARD_2799)
			.npc("General Bentnoze")
			.location(new ClueArea(2957, 3511, 0))
			.area("Talk to General Bentnoze in the Goblin Village north of Falador.")
			.build(),
		CrypticClue.builder()
			.text("Gold I see, yet gold I require. Give me 875 if death you desire.")
			.clueId(CLUE_SCROLL_HARD_12578)
			.npc("Saniboch")
			.location(new ClueArea(2745, 3151, 0))
			.area("Speak to Saniboch at the Brimhaven Dungeon entrance.")
			.build(),
		CrypticClue.builder()
			.text("He knows just how easy it is to lose track of time.")
			.clueId(CLUE_SCROLL_HARD_19854)
			.npc("Brother Kojo")
			.location(new ClueArea(2570, 3250, 0))
			.area("Speak to Brother Kojo in the Clock Tower. Answer: 22")
			.question("On a clock, how many times a day do the minute hand and the hour hand overlap?")
			.build(),
		CrypticClue.builder()
			.text("His head might be hollow, but the crates nearby are filled with surprises.")
			.clueId(CLUE_SCROLL_HARD_7253)
			.objectId(CRATE_354)
			.location(new ClueArea(3478, 3091, 0))
			.area("Search the crates near the Clay golem in the ruins of Uzer.")
			.build(),
		CrypticClue.builder()
			.text("I am a token of the greatest love. I have no beginning or end. My eye is red, I can fit like a glove. Go to the place where it's money they lend, And dig by the gate to be my friend.")
			.clueId(CLUE_SCROLL_HARD_2776)
			.location(new ClueArea(3190, 9825, 3192, 9826, 0))
			.area("Dig by the gate in the basement of the West Varrock bank.")
			.build(),
		CrypticClue.builder()
			.text("I have many arms but legs, I have just one. I have little family but my seed you can grow on, I am not dead, yet I am but a spirit, and my power, on your quests, you will earn the right to free it.")
			.clueId(CLUE_SCROLL_HARD_19858)
			.objectId(NULL_1293)
			.location(new ClueArea(2544, 3170, 0))
			.area("Spirit Tree in Tree Gnome Village. Answer: 13112221")
			.question("What is the next number in the sequence? 1, 11, 21, 1211, 111221, 312211.")
			.build(),
		CrypticClue.builder()
			.text("I lie lonely and forgotten in mid wilderness, where the dead rise from their beds. Feel free to quarrel and wind me up, and dig while you shoot their heads.")
			.clueId(CLUE_SCROLL_HARD_2786)
			.location(new ClueArea(3173, 3662, 3175, 3664, 0))
			.area("Directly under the crossbow respawn in the Graveyard of Shadows in level 18 Wilderness.")
			.build(),
		CrypticClue.builder()
			.text("I watch the sea. I watch you fish. I watch your tree.")
			.clueId(CLUE_SCROLL_HARD_12581)
			.npc("Ellena")
			.location(new ClueArea(2860, 3431, 0))
			.area("Speak to Ellena at Catherby fruit tree patch.")
			.build(),
		CrypticClue.builder()
			.text("Identify the back of this over-acting brother. (He's a long way from home.)")
			.clueId(CLUE_SCROLL_HARD_3568)
			.npc("Hamid")
			.location(new ClueArea(3376, 3284, 0))
			.area("Talk to Hamid, the monk at the altar in the Duel Arena")
			.build(),
		CrypticClue.builder()
			.text("If a man carried my burden, he would break his back. I am not rich, but leave silver in my track. Speak to the keeper of my trail.")
			.clueId(CLUE_SCROLL_HARD_2778)
			.npc("Gerrant")
			.location(new ClueArea(3014, 3222, 0))
			.area("Speak to Gerrant in the fish shop in Port Sarim.")
			.build(),
		CrypticClue.builder()
			.text("If you look closely enough, it seems that the archers have lost more than their needles.")
			.clueId(CLUE_SCROLL_HARD_7254)
			.objectId(HAYSTACK)
			.location(new ClueArea(2672, 3416, 0))
			.area("Search the haystack by the south corner of the Rangers' Guild")
			.build(),
		CrypticClue.builder()
			.text("In the city where merchants are said to have lived, talk to a man with a splendid cape, but a hat dropped by goblins.")
			.clueId(CLUE_SCROLL_HARD_19853)
			.npc("Head chef")
			.location(new ClueArea(3143, 3445, 0))
			.area("Talk to the Head chef in Cooks' Guild west of Varrock. You will need a chef's hat, Varrock armour 3 or 4, or the Cooking cape to enter.")
			.build(),
		CrypticClue.builder()
			.text("It seems to have reached the end of the line, and it's still empty.")
			.objectId(MINE_CART_6045)
			.location(new ClueArea(3041, 9820, 0))
			.area("Search the carts in the northern part of the Dwarven Mine.")
			.build(),
		CrypticClue.builder()
			.text("Leader of the Yak City.")
			.clueId(CLUE_SCROLL_HARD_19856)
			.npc("Mawnis Burowgar")
			.location(new ClueArea(2336, 3799, 0))
			.area("Talk to Mawnis Burowgar in Neitiznot.")
			.build(),
		CrypticClue.builder()
			.text("Mine was the strangest birth under the sun. I left the crimson sack, yet life had not begun. Entered the world, and yet was seen by none.")
			.clueId(CLUE_SCROLL_HARD_3580)
			.location(new ClueArea(2831, 9585, 2833, 9587, 0))
			.area("Inside Karamja Volcano, dig directly underneath the Red spiders' eggs respawn.")
			.build(),
		CrypticClue.builder()
			.text("Must be full of railings.")
			.clueId(CLUE_SCROLL_HARD_3574)
			.objectId(BOXES_6176)
			.location(new ClueArea(2576, 3464, 0))
			.area("Search the boxes around the hut where the broken Dwarf Cannon is, close to the start of the Dwarf Cannon quest.")
			.build(),
		CrypticClue.builder()
			.text("My giant guardians below the market streets would be fans of rock and roll, if only they could grab hold of it. Dig near my green bubbles!")
			.clueId(CLUE_SCROLL_HARD_2790)
			.location(new ClueArea(3160, 9903, 3162, 9905, 0))
			.area("Dig near the cauldron by Moss Giants under Varrock Sewers")
			.build(),
		CrypticClue.builder()
			.text("My home is grey, and made of stone; A castle with a search for a meal. Hidden in some drawers I am, across from a wooden wheel.")
			.objectId(DRAWERS_5618)
			.location(new ClueArea(3213, 3216, 1))
			.area("Open the drawers inside the room with the spinning wheel on the first floor of Lumbridge Castle.")
			.build(),
		CrypticClue.builder()
			.text("My name is like a tree, yet it is spelt with a 'g'. Come see the fur which is right near me.")
			.clueId(CLUE_SCROLL_HARD_2797)
			.npc("Wilough")
			.location(new ClueArea(3221, 3435, 0))
			.area("Speak to Wilough, next to the Fur Merchant in Varrock Square.")
			.build(),
		CrypticClue.builder()
			.text("Often sought out by scholars of histories past, find me where words of wisdom speak volumes.")
			.clueId(CLUE_SCROLL_HARD_3566)
			.npc("Examiner")
			.location(new ClueArea(3362, 3341, 0))
			.area("Speak to an examiner at the Exam Centre.")
			.build(),
		CrypticClue.builder()
			.text("Probably filled with books on magic.")
			.clueId(CLUE_SCROLL_HARD_7249)
			.objectId(BOOKCASE_380)
			.location(new ClueArea(3096, 9572, 0))
			.area("Search the bookcase in the basement of Wizard's Tower. Fairy ring DIS")
			.build(),
		CrypticClue.builder()
			.text("Read 'How to breed scorpions.' By O.W.Thathurt.")
			.clueId(CLUE_SCROLL_HARD_3572)
			.objectId(BOOKCASE_380)
			.location(new ClueArea(2703, 3409, 1))
			.area("Search the northern bookcase on the first floor of the Sorcerer's Tower.")
			.build(),
		CrypticClue.builder()
			.text("Rotting next to a ditch. Dig next to the fish.")
			.clueId(CLUE_SCROLL_HARD_19850)
			.location(new ClueArea(3535, 3175, 3572, 3189, 0))
			.area("Dig next to a fishing spot on the south-east side of Burgh de Rott.")
			.build(),
		CrypticClue.builder()
			.text("Snah? I feel all confused, like one of those cakes...")
			.clueId(CLUE_SCROLL_HARD_2792)
			.npc("Hans")
			.location(new ClueArea(3211, 3219, 0))
			.area("Talk to Hans roaming around Lumbridge Castle.")
			.build(),
		CrypticClue.builder()
			.text("Surprising? I bet he is...")
			.clueId(CLUE_SCROLL_HARD_2796)
			.npc("Sir Prysin")
			.location(new ClueArea(3205, 3474, 0))
			.area("Talk to Sir Prysin in Varrock Palace.")
			.build(),
		CrypticClue.builder()
			.text("Surviving.")
			.clueId(CLUE_SCROLL_HARD_12584)
			.npc("Sir Vyvin")
			.location(new ClueArea(2983, 3338, 2))
			.area("Talk to Sir Vyvin on the second floor of Falador castle.")
			.build(),
		CrypticClue.builder()
			.text("The beasts to my east snap claws and tails, The rest to my west can slide and eat fish. The force to my north will jump and they'll wail, Come dig by my fire and make a wish.")
			.clueId(CLUE_SCROLL_HARD_2783)
			.location(new ClueArea(2597, 3266, 2599, 3268, 0))
			.area("Dig by the torch in the Ardougne Zoo, between the penguins and the scorpions.")
			.build(),
		// Needs full area
		CrypticClue.builder()
			.text("The Big High War God left his mark on this place.")
			.clueId(CLUE_SCROLL_HARD_26566)
			.location(new ClueArea(3572, 4372, 0))
			.area("Yu'biusk")
			.build(),
		CrypticClue.builder()
			.text("The cheapest water for miles around, but they react badly to religious icons.")
			.clueId(CLUE_SCROLL_HARD_7248)
			.objectId(CRATE_354)
			.location(new ClueArea(3178, 2987, 0))
			.area("Search the crates in the General Store tent in the Bandit Camp")
			.build(),
		CrypticClue.builder()
			.text("The effects of this fire are magnified.")
			.clueId(CLUE_SCROLL_HARD_23045)
			.location(new ClueArea(1171, 3621, 1183, 3633, 0))
			.area("Dig by the fire beside Ket'sal K'uk in the westernmost part of the Kebos Swamp. ")
			.build(),
		CrypticClue.builder()
			.text("The keeper of Melzars... Spare? Skeleton? Anar?")
			.clueId(CLUE_SCROLL_HARD_2794)
			.npc("Oziach")
			.location(new ClueArea(3068, 3516, 0))
			.area("Speak to Oziach in Edgeville")
			.build(),
		CrypticClue.builder()
			.text("The King's magic won't be wasted by me.")
			.clueId(CLUE_SCROLL_HARD_12587)
			.npc("Guardian mummy")
			.location(new ClueArea(1934, 4427, 0))
			.area("Talk to the Guardian mummy inside the Pyramid Plunder minigame in Sophanem")
			.build(),
		CrypticClue.builder()
			.text("The magic of 4 colours, an early experience you could learn. The large beast caged up top, rages, as his demised kin's loot now returns.")
			.clueId(CLUE_SCROLL_HARD_19857)
			.npc("Wizard Mizgog")
			.location(new ClueArea(3103, 3163, 2))
			.area("Speak to Wizard Mizgog at the top of the Wizard's Tower south of Draynor.")
			.build(),
		CrypticClue.builder()
			.text("The mother of the reptilian sacrifice.")
			.clueId(CLUE_SCROLL_HARD_19852)
			.npc("Zul-Cheray")
			.location(new ClueArea(2204, 3050, 0))
			.area("Talk to Zul-Cheray in a house near the sacrificial boat at Zul-Andra.")
			.build(),
		CrypticClue.builder()
			.text("THEY'RE EVERYWHERE!!!! But they were here first. Dig for treasure where the ground is rich with ore.")
			.clueId(CLUE_SCROLL_HARD_12590)
			.location(new ClueArea(3079, 3419, 3083, 3423, 0))
			.area("Dig at Barbarian Village, next to the Stronghold of Security.")
			.build(),
		// TODO: Fix talk to.
		CrypticClue.builder()
			.text("This aviator is at the peak of his profession.")
			.clueId(CLUE_SCROLL_HARD_3570)
			.npc("Captain Bleemadge")
			.location(new ClueArea(2849, 3500, 0))
			.area("Captain Bleemadge, the gnome glider pilot, is found at the top of White Wolf Mountain.")
			.build(),
		CrypticClue.builder()
			.text("This village has a problem with cartloads of the undead. Try checking the bookcase to find an answer.")
			.clueId(CLUE_SCROLL_HARD_7247)
			.objectId(BOOKCASE_394)
			.location(new ClueArea(2833, 2992, 0))
			.area("Search the bookcase by the doorway of the building just south east of the Shilo Village Gem Mine.")
			.build(),
		CrypticClue.builder()
			.text("Try not to let yourself be dazzled when you search these drawers.")
			.clueId(CLUE_SCROLL_HARD_7255)
			.objectId(DRAWERS_350)
			.location(new ClueArea(2561, 3323, 0))
			.area("East Ardougne, north-west of castle")
			.build(),
		CrypticClue.builder()
			.text("When no weapons are at hand, then is the time to reflect. In Saradomin's name, redemption draws closer...")
			.clueId(CLUE_SCROLL_HARD_3579)
			.objectId(DRAWERS_350)
			.location(new ClueArea(2818, 3351, 0))
			.area("On Entrana, search the southern drawer in the house with the cooking range.")
			.build(),
		CrypticClue.builder()
			.text("When you get tired of fighting, go deep, deep down until you need an antidote.")
			.clueId(CLUE_SCROLL_HARD_7252)
			.objectId(CRATE_357)
			.location(new ClueArea(2576, 9583, 0))
			.area("Go to Yanille Agility dungeon and fall into the place with the poison spiders by praying at the Chaos altar. Search the crate by the stairs leading up.")
			.build(),
		CrypticClue.builder()
			.text("You have all of the elements available to solve this clue. Fortunately you do not have to go as far as to stand in a draft.")
			.clueId(CLUE_SCROLL_HARD_7250)
			.objectId(CRATE_18506)
			.location(new ClueArea(2723, 9891, 0))
			.area("Search the crate, west of the Air Elementals, inside the Elemental Workshop.")
			.build(),
		CrypticClue.builder()
			.text("You will need to under-cook to solve this one.")
			.clueId(CLUE_SCROLL_HARD_2773)
			.objectId(CRATE_357)
			.location(new ClueArea(3219, 9617, 0))
			.area("Search the crate in the Lumbridge basement.")
			.build(),
		// TODO: Dig in the lair of red wings, within the temple of the Sun and Moon

		// Elite
		CrypticClue.builder()
			.text("'See you in your dreams' said the vegetable man.")
			.clueId(CLUE_SCROLL_ELITE_12157)
			.npc("Dominic Onion")
			.location(new ClueArea(2608, 3116, 0))
			.area("Speak to Dominic Onion at the Nightmare Zone teleport spot.")
			.build(),
		CrypticClue.builder()
			.text("A demon's best friend holds the next step of this clue.")
			.clueId(CLUE_SCROLL_ELITE_19797)
			.area("Kill a hellhound.")
			.build(),
		CrypticClue.builder()
			.text("A Guthixian ring lies between two peaks. Search the stones and you'll find what you seek.")
			.clueId(CLUE_SCROLL_ELITE_12156)
			.objectId(STONES_26633)
			.location(new ClueArea(2922, 3484, 0))
			.area("Search the stones several steps west of the Guthixian stone circle in Taverley")
			.build(),
		CrypticClue.builder()
			.text("A reck you say; let's pray there aren't any ghosts.")
			.clueId(CLUE_SCROLL_ELITE_12151)
			.npc("Father Aereck")
			.location(new ClueArea(3242, 3207, 0))
			.area("Speak to Father Aereck in Lumbridge.")
			.build(),
		CrypticClue.builder()
			.text("A ring of water surrounds 4 powerful rings, dig above the ladder located there.")
			.clueId(CLUE_SCROLL_ELITE_19809)
			.location(new ClueArea(1910, 4366, 1912, 4368, 0))
			.area("Dig by the ladder leading to the Dagannoth Kings room in the Waterbirth Island Dungeon. Bring a pet rock and rune thrownaxe.")
			.build(),
		CrypticClue.builder()
			.text("Desert insects is what I see. Taking care of them was my responsibility. Your solution is found by digging near me.")
			.clueId(CLUE_SCROLL_ELITE_12158)
			.location(new ClueArea(3306, 9504, 3308, 9505, 0))
			.area("Dig next to the Entomologist, Kalphite area, near Shantay Pass.")
			.build(),
		CrypticClue.builder()
			.text("Dig under Razorlor's toad batta.")
			.clueId(CLUE_SCROLL_ELITE_19810)
			.location(new ClueArea(3138, 4554, 3140, 4555, 0))
			.area("Dig on the toad batta spawn in Tarn's Lair.")
			.build(),
		CrypticClue.builder()
			.text("Dig where the forces of Zamorak and Saradomin collide.")
			.clueId(CLUE_SCROLL_ELITE_12150)
			.location(new ClueArea(3049, 4838, 3050, 4840, 0))
			.area("Dig next to the law rift in the Abyss")
			.build(),
		CrypticClue.builder()
			.text("Dobson is my last name, and with gardening I seek fame.")
			.clueId(CLUE_SCROLL_ELITE_12154)
			.npc("Horacio")
			.location(new ClueArea(2635, 3310, 0))
			.area("Horacio, located in the garden of the Handelmort Mansion in East Ardougne.")
			.build(),
		CrypticClue.builder()
			.text("Does one really need a fire to stay warm here?")
			.clueId(CLUE_SCROLL_ELITE_21525)
			.location(new ClueArea(3816, 3809, 3818, 3811, 0))
			.area("Dig next to the fire near the Volcanic Mine entrance.")
			.build(),
		CrypticClue.builder()
			.text("Even the seers say this clue goes right over their heads.")
			.objectId(CRATE_14934)
			.location(new ClueArea(2707, 3488, 2))
			.area("Search the crate on the Seers Agility Course in Seers Village")
			.build(),
		CrypticClue.builder()
			.text("Ghostly bones.")
			.clueId(CLUE_SCROLL_ELITE_19805)
			.area("Kill an Ankou.")
			.build(),
		CrypticClue.builder()
			.text("Green is the colour of my death as the winter-guise, I swoop towards the ground.")
			.clueId(CLUE_SCROLL_ELITE_12141)
			.location(new ClueArea(2778, 3783, 2780, 3785, 0))
			.area("Players need to slide down to where Trollweiss grows on Trollweiss Mountain. Bring a sled.")
			.build(),
		CrypticClue.builder()
			.text("Has no one told you it is rude to ask a lady her age?")
			.clueId(CLUE_SCROLL_ELITE_12140)
			.npc("Mawrth")
			.location(new ClueArea(2333, 3165, 0))
			.area("Talk to Mawrth in Lletya.")
			.build(),
		CrypticClue.builder()
			.text("His bark is worse than his bite.")
			.clueId(CLUE_SCROLL_ELITE_12155)
			.npc("Barker")
			.location(new ClueArea(3499, 3503, 0))
			.area("Speak to the Barker at Canifis's Barkers' Haberdashery.")
			.build(),
		CrypticClue.builder()
			.text("I am the one who watches the giants. The giants in turn watch me. I watch with two while they watch with one. Come seek where I may be.")
			.clueId(CLUE_SCROLL_ELITE_12144)
			.npc("Kamfreena")
			.location(new ClueArea(2845, 3539, 0))
			.area("Speak to Kamfreena on the top floor of the Warriors' Guild.")
			.build(),
		CrypticClue.builder()
			.text("I burn between heroes and legends.")
			.clueId(CLUE_SCROLL_ELITE_12152)
			.npc("Candle maker")
			.location(new ClueArea(2799, 3438, 0))
			.area("Speak to the Candle maker in Catherby.")
			.build(),
		CrypticClue.builder()
			.text("I live in a deserted crack collecting soles.")
			.clueId(CLUE_SCROLL_ELITE_12153)
			.npc("Genie")
			.location(new ClueArea(3371, 9320, 0))
			.area("Enter the crack west of Nardah Rug merchant, and talk to the Genie. You'll need a light source and a rope.")
			.requiresLight(true)
			.build(),
		CrypticClue.builder()
			.text("In a while...")
			.clueId(CLUE_SCROLL_ELITE_19804)
			.area("Kill a crocodile.")
			.build(),
		CrypticClue.builder()
			.text("Let's hope you don't meet a watery death when you encounter this fiend.")
			.clueId(CLUE_SCROLL_ELITE_19798)
			.area("Kill a waterfiend.")
			.build(),
		CrypticClue.builder()
			.text("Mix yellow with blue and add heat, make sure you bring protection.")
			.clueId(CLUE_SCROLL_ELITE_19799)
			.area("Kill a green or brutal green dragon.")
			.build(),
		CrypticClue.builder()
			.text("More resources than I can handle, but in a very dangerous area. Can't wait to strike gold!")
			.clueId(CLUE_SCROLL_ELITE_23144)
			.location(new ClueArea(3182, 3940, 3184, 3942, 0))
			.area("Dig between the three gold ores in the Wilderness Resource Area.")
			.build(),
		CrypticClue.builder()
			.text("Observing someone in a swamp, under the telescope lies treasure.")
			.clueId(CLUE_SCROLL_ELITE_23145)
			// Needs full area
			.location(new ClueArea(2221, 3091, 0))
			.area("Dig next to the telescope on Broken Handz's island in the poison wastes. (Accessible only through fairy ring DLR)")
			.build(),
		CrypticClue.builder()
			.text("Reflection is the weakness for these eyes of evil.")
			.clueId(CLUE_SCROLL_ELITE_19800)
			.area("Kill a basilisk.")
			.build(),
		CrypticClue.builder()
			.text("Right on the blessed border, cursed by the evil ones. On the spot inaccessible by both; I will be waiting. The bugs' imminent possession holds the answer.")
			.clueId(CLUE_SCROLL_ELITE_12146)
			.location(new ClueArea(3409, 3323, 3411, 3325, 0))
			.area("B I P. Dig right under the fairy ring.")
			.build(),
		CrypticClue.builder()
			.text("Scattered coins and gems fill the floor. The chest you seek is in the north east.")
			.clueId(CLUE_SCROLL_ELITE_19807)
			.npc("King Black Dragon")
			.objectId(CLOSED_CHEST_375)
			.location(new ClueArea(2288, 4702, 0))
			.area("Kill the King Black Dragon for a key (elite), and then open the closed chest in the NE corner of the lair.")
			.build(),
		CrypticClue.builder()
			.text("Speak to a Wyse man.")
			.clueId(CLUE_SCROLL_ELITE_12159)
			.npc("Wyson the gardener")
			.location(new ClueArea(3026, 3378, 0))
			.area("Talk to Wyson the gardener at Falador Park.")
			.build(),
		CrypticClue.builder()
			.text("Surround my bones in fire, ontop the wooden pyre. Finally lay me to rest, before my one last test.")
			.clueId(CLUE_SCROLL_ELITE_19806)
			.area("Kill a confused/lost barbarian to receive mangled bones. Construct and burn a pyre ship. Kill the ferocious barbarian spirit that spawns to receive a clue casket.")
			.build(),
		CrypticClue.builder()
			.text("The beasts retreat, for their Queen is gone; the song of this town still plays on. Dig near the birthplace of a blade, be careful not to melt your spade.")
			.clueId(CLUE_SCROLL_ELITE_12143)
			// Needs full area
			.location(new ClueArea(2342, 3677, 0))
			.area("Dig in front of the small furnace in the Piscatoris Fishing Colony.")
			.build(),
		CrypticClue.builder()
			.text("Three rule below and three sit at top. Come dig at my entrance.")
			.clueId(CLUE_SCROLL_ELITE_12142)
			.location(new ClueArea(2523, 3739, 2524, 3740, 0))
			.area("Dig in front of the entrance to the Waterbirth Island Dungeon.")
			.build(),
		CrypticClue.builder()
			.text("Varrock is where I reside, not the land of the dead, but I am so old, I should be there instead. Let's hope your reward is as good as it says, just 1 gold one and you can have it read.")
			.npc("Gypsy Aris")
			.location(new ClueArea(3203, 3424, 0))
			.area("Talk to Gypsy Aris, West of Varrock main square.")
			.build(),
		CrypticClue.builder()
			.text("W marks the spot.")
			.clueId(CLUE_SCROLL_ELITE_12148)
			.location(new ClueArea(2865, 3545, 2867, 3547, 0))
			.area("Dig in the middle of the Warriors' Guild entrance hall")
			.build(),
		CrypticClue.builder()
			.text("With a name like that, you'd expect a little more than just a few scimitars.")
			.clueId(CLUE_SCROLL_ELITE_19808)
			.npc("Daga")
			.location(new ClueArea(2759, 2775, 0))
			.area("Speak to Daga on Ape Atoll.")
			.build(),
		CrypticClue.builder()
			.text("You might have to turn over a few stones to progress.")
			.clueId(CLUE_SCROLL_ELITE_19796)
			.area("Kill a rock crab.")
			.build(),
		CrypticClue.builder()
			.text("You must be 100 to play with me.")
			.clueId(CLUE_SCROLL_ELITE_19811)
			.npc("Squire (Veteran)")
			.location(new ClueArea(2638, 2656, 0))
			.area("Speak to the Veteran boat squire at Pest Control")
			.build(),
		CrypticClue.builder()
			.text("You were 3 and I was the 6th. Come speak to me.")
			.clueId(CLUE_SCROLL_ELITE_12147)
			.npc("Vannaka")
			.location(new ClueArea(3146, 9913, 0))
			.area("Speak to Vannaka in Edgeville Dungeon.")
			.build(),
		CrypticClue.builder()
			.text("You will have to fly high where a sword cannot help you.")
			.clueId(CLUE_SCROLL_ELITE_19803)
			.area("Kill an Aviansie.")
			.build(),
		CrypticClue.builder()
			.text("You'll get licked.")
			.clueId(CLUE_SCROLL_ELITE_19801)
			.area("Kill a Bloodveld.")
			.build(),
		CrypticClue.builder()
			.text("You'll have to plug your nose if you use this source of herbs.")
			.clueId(CLUE_SCROLL_ELITE_19802)
			.area("Kill an Aberrant or Deviant spectre.")
			.build(),

		// Elite & Master
		// TODO
		CrypticClue.builder()
			.text("Show this to Sherlock.")
			.clueId(CLUE_SCROLL_ELITE_12122)
			.npc("Sherlock")
			.location(new ClueArea(2733, 3415, 0))
			.area("Sherlock is located to the east of the Sorcerer's tower in Seers' Village.")
			.build(),

		// Master
		CrypticClue.builder()
			.text("2 musical birds. Dig in front of the spinning light.")
			// Needs full area
			.location(new ClueArea(2671, 10396, 0))
			.area("Dig in front of the spinning light in Ping and Pong's room inside the Iceberg")
			.build(),
		CrypticClue.builder()
			.text("A chisel and hammer reside in his home, strange for one of magic. Impress him with your magical equipment.")
			.npc("Wizard Cromperty")
			.location(new ClueArea(2682, 3325, 0))
			.area("Wizard Cromperty, NE corner of East Ardougne. +100 magic attack bonus needed")
			.build(),
		CrypticClue.builder()
			.text("A dwarf, approaching death, but very much in the light.")
			.npc("Thorgel")
			.location(new ClueArea(1863, 4639, 0))
			.area("Thorgel at the entrance to the Death altar")
			.build(),
		CrypticClue.builder()
			.text("A massive battle rages beneath so be careful when you dig by the large broken crossbow.")
			// Needs full area
			.location(new ClueArea(2927, 3761, 0))
			.area("NE of the God Wars Dungeon entrance, climb the rocky handholds & dig by large crossbow.")
			.build(),
		CrypticClue.builder()
			.text("Anger Abbot Langley.")
			.npc("Abbot Langley")
			.location(new ClueArea(3058, 3487, 0))
			.area("Speak to Abbot Langley in the Edgeville Monastery while you have a negative prayer bonus (currently only possible with an Ancient staff).")
			.build(),
		CrypticClue.builder()
			.text("Anger those who adhere to Saradomin's edicts to prevent travel.")
			.npc("Monk of Entrana")
			.location(new ClueArea(3042, 3236, 0))
			.area("Port Sarim Docks, try to charter a ship to Entrana with armour or weapons equipped.")
			.build(),
		CrypticClue.builder()
			.text("Come brave adventurer, your sense is on fire. If you talk to me, it's an old god you desire.")
			.npc("Viggora")
			.area("Speak to Viggora while wearing a ring of visibility and a Ghostspeak amulet.")
			.build(),
		CrypticClue.builder()
			.text("Darkness wanders around me, but fills my mind with knowledge.")
			.npc("Biblia")
			.location(new ClueArea(1633, 3825, 2))
			.area("Speak to Biblia on the Arceuus Library's top floor.")
			.build(),
		CrypticClue.builder()
			.text("Dig in front of the icy arena where 1 of 4 was fought.")
			// Needs full area
			.location(new ClueArea(2874, 3757, 0))
			.area("Where you fought Kamil from Desert Treasure.")
			.build(),
		CrypticClue.builder()
			.text("Faint sounds of 'Arr', fire giants found deep, the eastern tip of a lake, are the rewards you could reap.")
			// Needs full area
			.location(new ClueArea(3055, 10338, 0))
			.area("Dig south of the pillar in the Deep Wilderness Dungeon in the room with the fire giants.")
			.build(),
		CrypticClue.builder()
			.text("Falo the bard wants to see you.")
			.npc("Falo the Bard")
			.location(new ClueArea(2689, 3550, 0))
			.area("Speak to Falo the Bard located between Seers' Village and Rellekka. Southwest of fairy ring CJR.")
			.build(),
		CrypticClue.builder()
			.text("Elvish onions.")
			// Needs full area
			.location(new ClueArea(3303, 6092, 0))
			.area("Dig in the onion patch east of the Prifddinas allotments.")
			.build(),
		CrypticClue.builder()
			.text("Fiendish cooks probably won't dig the dirty dishes.")
			.location(new ClueArea(3040, 4970, 3046, 4976, 1))
			.area("Dig by the fire in the Rogues' Den.")
			.build(),
		CrypticClue.builder()
			.text("Ghommal wishes to be impressed by how strong your equipment is.")
			.npc("Ghommal")
			.location(new ClueArea(2878, 3546, 0))
			.area("Speak to Ghommal at the Warriors' Guild with a total Melee Strength bonus of over 100.")
			.build(),
		CrypticClue.builder()
			.text("Great demons, dragons and spiders protect this blue rock, beneath which, you may find what you seek.")
			// Needs full area
			.location(new ClueArea(3045, 10265, 0))
			.area("Dig by the runite rock in the Lava Maze Dungeon")
			.build(),
		CrypticClue.builder()
			.text("Guthix left his mark in a fiery lake, dig at the tip of it.")
			// Needs full area
			.location(new ClueArea(3069, 3935, 0))
			.area("Dig at the tip of the lava lake that is shaped like a Guthixian symbol, west of the Mage Arena.")
			.build(),
		CrypticClue.builder()
			.text("Here, there are tears, but nobody is crying. Speak to the guardian and show off your alignment to balance.")
			.npc("Juna")
			.objectId(JUNA)
			.location(new ClueArea(3252, 9517, 2))
			.area("Talk to Juna while wearing three Guthix related items.")
			.build(),
		CrypticClue.builder()
			.text("Hopefully this set of armour will help you to keep surviving.")
			.npc("Sir Vyvin")
			.location(new ClueArea(2982, 3336, 2))
			.area("Speak to Sir Vyvin while wearing a white platebody, and platelegs.")
			.build(),
		CrypticClue.builder()
			.text("If you're feeling brave, dig beneath the dragon's eye.")
			// Needs full area
			.location(new ClueArea(2410, 4714, 0))
			.area("Dig below the mossy rock under the Viyeldi caves (Legends' Quest). Items needed: Pickaxe, unpowered orb, lockpick, spade, any charge orb spell, and either 79 agility or an axe and machete.")
			.build(),
		CrypticClue.builder()
			.text("I lie beneath the first descent to the holy encampment.")
			.location(new ClueArea(2914, 5299, 2917, 5300, 1))
			.area("Dig immediately after climbing down the first set of rocks towards Saradomin's encampment within the God Wars Dungeon.")
			.build(),
		CrypticClue.builder()
			.text("My life was spared but these voices remain, now guarding these iron gates is my bane.")
			.npc("Key Master")
			.location(new ClueArea(1310, 1251, 0))
			.area("Speak to the Key Master in Cerberus' Lair.")
			.build(),
		CrypticClue.builder()
			.text("One of several rhyming brothers, in business attire with an obsession for paper work.")
			.npc("Piles")
			.location(new ClueArea(3186, 3936, 0))
			.area("Speak to Piles in the Wilderness Resource Area. An entry fee of 7,500 coins is required, or less if Wilderness Diaries have been completed.")
			.build(),
		CrypticClue.builder()
			.text("Pentagrams and demons, burnt bones and remains, I wonder what the blood contains.")
			// Needs full area
			.location(new ClueArea(3297, 3890, 0))
			.area("Dig under the blood rune spawn next to the Demonic Ruins.")
			.build(),
		CrypticClue.builder()
			.text("Robin wishes to see your finest ranged equipment.")
			.npc("Robin")
			.location(new ClueArea(3673, 3492, 0))
			.area("Robin at the inn in Port Phasmatys. Speak to him with +182 in ranged attack bonus. Bonus granted by the toxic blowpipe is ignored.")
			.build(),
		CrypticClue.builder()
			.text("She's small but can build both literally and figuratively, as long as you have their favour.")
			.npc("Lovada")
			.location(new ClueArea(1486, 3834, 0))
			.area("Speak to Lovada by the entrance to the blast mine in Lovakengj.")
			.build(),
		CrypticClue.builder()
			.text("Shhhh!")
			.npc("Logosia")
			.location(new ClueArea(1633, 3808, 0))
			.area("Speak to Logosia in the Arceuus Library's ground floor.")
			.build(),
		CrypticClue.builder()
			.text("South of a river in a town surrounded by the undead, what lies beneath the furnace?")
			// Needs full area
			.location(new ClueArea(2857, 2966, 0))
			.area("Dig in front of the Shilo Village furnace.")
			.build(),
		CrypticClue.builder()
			.text("The far north eastern corner where 1 of 4 was defeated, the shadows still linger.")
			.location(new ClueArea(2742, 5112, 2746, 5116, 0))
			.area("Dig on the northeastern-most corner of the Shadow Dungeon. Bring a ring of visibility.")
			.build(),
		CrypticClue.builder()
			.text("This place sure is a mess.")
			.npc("Ewesey")
			.location(new ClueArea(1646, 3631, 0))
			.area("Ewesey is located in the mess hall in Hosidius.")
			.build(),
		CrypticClue.builder()
			.text("Under a giant robotic bird that cannot fly.")
			// Needs full area
			.location(new ClueArea(1756, 4940, 0))
			.area("Dig next to the terrorbird display in the south exhibit of Varrock Museum's basement.")
			.build(),
		CrypticClue.builder()
			.text("Where safe to speak, the man who offers the pouch of smallest size wishes to see your alignment.")
			.npc("Mage of Zamorak")
			.location(new ClueArea(3260, 3385, 0))
			.area("Speak to the Mage of Zamorak south of the Rune Shop in Varrock while wearing three zamorakian items")
			.build(),

		// X Marks the Spot
		// TODO
		CrypticClue.builder()
			.text("Within the town of Lumbridge lives a man named Bob. He walks out of his door and takes 1 step east, 7 steps north, 5 steps west and 1 step south. Once he arrives, he digs a hole and buries his treasure.")
			.location(new ClueArea(3230, 3209, 0))
			.area("TODO")
			.build()
	);

	private final String type = "Cryptic Clue";

	@Nullable
	public static CrypticClue forText(String text)
	{
		// TODO: Remove debug
		for (CrypticClue clue : CLUES)
		{
			if (text.equalsIgnoreCase(clue.getText())
				|| text.equalsIgnoreCase(clue.getQuestion())
				|| (clue.getText() != null && clue.getText().toLowerCase().startsWith(text)))
			{
				return clue;
			}
		}

		return null;
	}
}
